package iraspdf

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/go-pdf/fpdf"
)

const (
	fontFamily = "Helvetica"
	fontSize   = 8.0
	titleSize  = 18.0
	smallSize  = 7.0
	tinySize   = 6.0

	pageW    = 612.0 // Letter size
	pageH    = 792.0
	marginL  = 54.0
	marginR  = 54.0
	contentW = pageW - marginL - marginR
)

// irasBuilder provides IRAS form layout primitives.
type irasBuilder struct {
	pdf *fpdf.Fpdf
	y   float64
}

func newBuilder() *irasBuilder {
	pdf := fpdf.New("P", "pt", "Letter", "")
	pdf.SetAutoPageBreak(true, 40)
	pdf.SetFooterFunc(func() {
		pdf.SetY(-20)
		pdf.SetTextColor(136, 136, 136)
		pdf.SetFont(fontFamily, "", tinySize)
		pdf.CellFormat(0, 10,
			"Generated by AIStarlight | Draft computation for review purposes — not for official filing with IRAS",
			"", 0, "C", false, 0, "")
	})
	pdf.AddPage()
	return &irasBuilder{pdf: pdf, y: 0}
}

// titleBanner draws the IRAS-branded title banner.
func (b *irasBuilder) titleBanner(formNo, subtitle string) {
	// Dark red banner (IRAS brand color)
	b.pdf.SetFillColor(180, 32, 37)
	b.pdf.Rect(0, 0, pageW, 70, "F")

	b.pdf.SetTextColor(255, 255, 255)
	b.pdf.SetFont(fontFamily, "B", titleSize)
	b.centeredCell(16, 20, formNo)

	b.pdf.SetFont(fontFamily, "", 10)
	b.centeredCell(36, 14, subtitle)

	b.pdf.SetFont(fontFamily, "", smallSize)
	b.centeredCell(52, 12, "Inland Revenue Authority of Singapore (IRAS)")

	b.y = 90
}

func (b *irasBuilder) centeredCell(y, h float64, text string) {
	b.pdf.SetXY(0, y)
	b.pdf.CellFormat(pageW, h, text, "", 0, "C", false, 0, "")
}

// sectionHeader draws a section header bar.
func (b *irasBuilder) sectionHeader(text string) {
	b.pdf.SetFillColor(232, 237, 242)
	b.pdf.Rect(marginL, b.y, contentW, 18, "F")
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont(fontFamily, "B", 9)
	b.pdf.SetXY(marginL+6, b.y+2)
	b.pdf.CellFormat(contentW-12, 14, text, "", 0, "L", false, 0, "")
	b.y += 22
}

// infoBlock draws labeled info rows.
func (b *irasBuilder) infoBlock(items [][2]string) {
	b.pdf.SetTextColor(0, 0, 0)
	for _, item := range items {
		b.pdf.SetFont(fontFamily, "", fontSize)
		b.pdf.SetXY(marginL+6, b.y)
		b.pdf.CellFormat(134, 14, item[0]+":", "", 0, "L", false, 0, "")
		b.pdf.SetFont(fontFamily, "B", fontSize)
		b.pdf.SetXY(marginL+146, b.y)
		b.pdf.CellFormat(contentW-152, 14, item[1], "", 0, "L", false, 0, "")
		b.y += 14
	}
	b.y += 6
}

// lineItem draws a single line item (box number, label, S$ amount).
func (b *irasBuilder) lineItem(boxNo, label, value string, bold bool) {
	style := ""
	if bold {
		style = "B"
	}
	b.pdf.SetFont(fontFamily, style, fontSize)
	b.pdf.SetTextColor(0, 0, 0)

	if boxNo != "" {
		b.pdf.SetXY(marginL+6, b.y)
		b.pdf.CellFormat(36, 12, boxNo, "", 0, "L", false, 0, "")
	}
	b.pdf.SetXY(marginL+44, b.y)
	b.pdf.CellFormat(contentW-164, 12, label, "", 0, "L", false, 0, "")
	b.pdf.SetXY(pageW-marginR-120, b.y)
	b.pdf.CellFormat(120, 12, "S$ "+formatAmount(value), "", 0, "R", false, 0, "")

	b.pdf.SetDrawColor(204, 204, 204)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Line(marginL, b.y+12, pageW-marginR, b.y+12)
	b.y += 16
}

// totalHighlight draws a highlighted total row.
func (b *irasBuilder) totalHighlight(boxNo, label, value string) {
	b.y += 4
	b.pdf.SetFillColor(240, 244, 255)
	b.pdf.Rect(marginL, b.y, contentW, 22, "F")
	b.pdf.SetDrawColor(180, 32, 37)
	b.pdf.SetLineWidth(1)
	b.pdf.Rect(marginL, b.y, contentW, 22, "D")

	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont(fontFamily, "B", 10)
	b.pdf.SetXY(marginL+6, b.y+3)
	b.pdf.CellFormat(36, 16, boxNo, "", 0, "L", false, 0, "")
	b.pdf.SetXY(marginL+44, b.y+3)
	b.pdf.CellFormat(contentW-164, 16, label, "", 0, "L", false, 0, "")

	b.pdf.SetTextColor(180, 32, 37)
	b.pdf.SetXY(pageW-marginR-120, b.y+3)
	b.pdf.CellFormat(120, 16, "S$ "+formatAmount(value), "", 0, "R", false, 0, "")
	b.y += 28
}

// rateNote draws an informational note box.
func (b *irasBuilder) rateNote(text string) {
	b.y += 4
	b.pdf.SetFillColor(254, 243, 199)
	b.pdf.Rect(marginL, b.y, contentW, 18, "F")
	b.pdf.SetTextColor(146, 64, 14)
	b.pdf.SetFont(fontFamily, "", fontSize)
	b.pdf.SetXY(marginL+6, b.y+2)
	b.pdf.CellFormat(contentW-12, 14, text, "", 0, "L", false, 0, "")
	b.y += 22
}

// notes draws the IMPORTANT NOTES section.
func (b *irasBuilder) notes(lines []string) {
	b.y += 16
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont(fontFamily, "", smallSize)
	for _, line := range lines {
		b.pdf.SetXY(marginL+6, b.y)
		b.pdf.CellFormat(contentW-12, 10, line, "", 0, "L", false, 0, "")
		b.y += 10
	}
}

func (b *irasBuilder) gap(pts float64) {
	b.y += pts
}

func (b *irasBuilder) output(w io.Writer) error {
	return b.pdf.Output(w)
}

// formatAmount formats a numeric string as "1,234.56".
func formatAmount(value string) string {
	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return value
	}

	neg := f < 0
	if neg {
		f = -f
	}

	s := fmt.Sprintf("%.2f", f)
	parts := strings.Split(s, ".")
	integer, frac := parts[0], parts[1]

	n := len(integer)
	if n > 3 {
		var buf strings.Builder
		for i, ch := range integer {
			if i > 0 && (n-i)%3 == 0 {
				buf.WriteByte(',')
			}
			buf.WriteRune(ch)
		}
		integer = buf.String()
	}

	formatted := integer + "." + frac
	if neg {
		return "(" + formatted + ")"
	}
	return formatted
}

// getVal safely retrieves a value from data, trying multiple keys.
func getVal(data map[string]string, keys ...string) string {
	for _, k := range keys {
		if v, ok := data[k]; ok && v != "" {
			return v
		}
	}
	return "0"
}
