-- Supplemental knowledge_chunks from official BIR sources and authoritative references
-- Sources: BIR RR 24-2025, RMC 34-2025, RR 7-2024, NIRC, TRAIN Law, CREATE Law, EOPT Act

INSERT INTO knowledge_chunks (id, source, category, content, metadata) VALUES

-- ========== VAT (expanded) ==========

(uuid_generate_v4(), 'NIRC Section 109', 'vat',
'VAT-Exempt Transactions (Complete List): (A) Sale of agricultural/marine food products in original state. (B) Sale of fertilizers, seeds, seedlings, fingerlings, fish, prawn, livestock, poultry feeds. (C) Importation of personal/household effects of returning OFWs. (D) Importation of professional instruments by returning nationals. (E) Services by agricultural contract growers/milling for others of palay. (F) Medical, dental, hospital, veterinary services (except by professionals). (G) Educational services by accredited private educational institutions. (H) Sale of real property not primarily held for sale (capital asset). (I) Lease of residential units with monthly rental not exceeding PHP 15,000. (J) Sale of books, newspapers, magazines. (K) Transport of passengers by land (excluding toll fees). (L) Sale of power/fuel generated by renewable energy sources. (M) Sale of gold to BSP. (N) Sale of drugs/medicines for diabetes, high cholesterol, hypertension, cancer, mental illness, HIV/AIDS, kidney diseases.',
'{"section": "109", "law": "NIRC", "topic": "vat_exempt_list"}'),

(uuid_generate_v4(), 'NIRC Section 106(A)(2)', 'vat',
'Zero-Rated VAT Sales (Complete): (1) Export sales of goods. (2) Foreign currency denominated sales. (3) Sales to persons/entities with indirect tax exemption under special laws or international agreements. (4) Processing, manufacturing, or repacking of goods for export. (5) Services rendered to persons engaged in business outside the Philippines, paid in foreign currency. (6) Transport of passengers and cargo by air or sea from Philippines to foreign country. (7) Sale of power or fuel generated through renewable energy. (8) Services rendered to registered export enterprises. Zero-rated means 0% output VAT but input VAT credits are allowed.',
'{"section": "106(A)(2)", "law": "NIRC", "topic": "zero_rated"}'),

(uuid_generate_v4(), 'RR No. 16-2005 as amended', 'vat',
'Input VAT Credit Rules: (1) Input VAT on domestic purchases of goods/services directly attributable to zero-rated or effectively zero-rated sales may be refunded or converted to Tax Credit Certificate within 2 years. (2) Input VAT on capital goods exceeding PHP 1M amortized over useful life (max 60 months). (3) Transitional input tax of 2% of beginning inventory for newly VAT-registered. (4) Presumptive input tax of 4% for processors of sardines, mackerel, milk, refined sugar, cooking oil, flour. (5) Standard input tax of 7% for certain government purchases. (6) Input tax from VAT-registered suppliers only, supported by valid VAT invoices.',
'{"regulation": "RR 16-2005", "topic": "input_vat_credits"}'),

(uuid_generate_v4(), 'RA 12023 (Digital Services VAT Act)', 'vat',
'VAT on Digital Services (effective June 2, 2025): 12% VAT applies to digital services provided by Non-Resident Digital Service Providers (NDSPs) for services consumed in the Philippines. Digital services include: online licensing of software, online advertising, digital content streaming, online platforms/marketplaces, cloud services, data storage, search engines, social media. NDSPs must register with BIR if gross sales from PH-consumed digital services exceed PHP 3M within 12 months. NDSPs must file quarterly VAT returns and remit VAT collected.',
'{"law": "RA 12023", "topic": "digital_services_vat"}'),

(uuid_generate_v4(), 'RA 11976 (EOPT Act) - VAT Changes', 'vat',
'EOPT Act VAT Changes (effective 2024): (1) VAT filing simplified to quarterly only (BIR Form 2550Q) instead of monthly + quarterly. Monthly BIR 2550M eliminated for most taxpayers. (2) VAT threshold of PHP 3M may be adjusted every 3 years using PSA Consumer Price Index. (3) Unified invoicing: Official Receipts eliminated, only Sales Invoices required for both goods and services. (4) Penalties reduced for Micro and Small taxpayers: late filing penalty reduced to PHP 1,000 (max PHP 25,000/year), interest reduced to 6% (from 12%) for qualifying small enterprises.',
'{"law": "RA 11976", "regulation": "EOPT", "topic": "vat_simplification"}'),

(uuid_generate_v4(), 'BIR Form 2550Q Instructions', 'vat',
'BIR 2550Q (Quarterly VAT Return): Filed quarterly by VAT-registered taxpayers. Due on or before the 25th day following the close of each quarter (Q1: April 25, Q2: July 25, Q3: October 25, Q4: January 25). Schedule 1: Sales/Receipts breakdown (vatable, zero-rated, exempt, government). Schedule 2: Input tax details (from domestic purchases, importation, services, capital goods). Schedule 3: Tax credits and payments. Net VAT Payable = Output Tax - Allowable Input Tax - Tax Credits. Excess input tax may be carried over to next quarter.',
'{"form": "BIR_2550Q", "topic": "quarterly_vat_return"}'),

-- ========== Withholding Tax (expanded) ==========

(uuid_generate_v4(), 'RR No. 2-98 Sec. 2.57.2 (Complete EWT Rates)', 'withholding',
'Complete Expanded Withholding Tax Rate Table: (A) Professional fees, talent fees, etc.: 5% if individual gross income <= PHP 3M; 10% if individual gross income > PHP 3M or if payee is a corporation. (B) Professional fees paid to medical practitioners by hospitals/clinics: 10%. (C) Rentals: Real property - 5%; Personal property - 5%; Poles/satellites/transmission - 5%. (D) Cinematographic film rentals: 5%. (E) Income from franchises: 5%. (F) Interest income from deposit substitutes: 20% final. (G) Prizes exceeding PHP 10K: 20%. (H) Winning from PCSO/lotto (> PHP 10K): 20%. (I) Payments to contractors/subcontractors: 2%. (J) Income from real property: 1.5% on gross selling price or FMV. (K) Additional income payments to government personnel: 15%.',
'{"regulation": "RR 2-98", "topic": "ewt_rate_table"}'),

(uuid_generate_v4(), 'RR No. 24-2025 (Top Withholding Agents)', 'withholding',
'Top Withholding Agent (TWA) Rules (RR 24-2025, effective Sep 25, 2025): TWAs (private corporations or individuals designated by BIR) must withhold creditable tax on payments to local/resident suppliers not covered by other EWT rates: Supplier of goods: 1%. Supplier of services: 2%. Special reduced rate of 0.5% for gross payments to manufacturers and direct importers of: (a) motor vehicles in CBU/SKD units, motor vehicle parts and accessories; (b) medicine/pharmaceutical products; (c) solid or liquid fuels and related products. TWAs include: top 20,000 private corporations, top 10,000 individuals, and non-resident aliens engaged in trade/business in PH.',
'{"regulation": "RR 24-2025", "topic": "top_withholding_agents"}'),

(uuid_generate_v4(), 'NIRC Section 57(A) - Final Withholding Tax', 'withholding',
'Final Withholding Tax Rates: (1) Interest on bank deposits: 20%. (2) Royalties: 20% (books/literary works: 10%). (3) Prizes exceeding PHP 10,000: 20%. (4) PCSO/lotto winnings > PHP 10,000: 20%. (5) Dividends from domestic corporations to: Citizen/Resident: 10%; Non-resident alien engaged in trade: 20%; Non-resident alien not engaged: 25%; Non-resident foreign corporation: 25% (15% if country allows deemed-paid credit). (6) Capital gains from sale of shares not traded in stock exchange: 15%. (7) Capital gains from sale of real property: 6%. (8) Branch profit remittance tax: 15%. (9) Fringe benefits tax: 35% on grossed-up value (for managerial/supervisory employees).',
'{"section": "57(A)", "law": "NIRC", "topic": "final_withholding_tax"}'),

(uuid_generate_v4(), 'BIR ATC Codes (Common EWT)', 'withholding',
'Common Alphanumeric Tax Codes (ATC) for EWT: WI010 - EWT on professional fees (individuals): 5%/10%. WC010 - EWT on professional fees (corporations): 10%. WI100 - EWT on rent (real property): 5%. WI120 - EWT on contractors/subcontractors: 2%. WI157 - EWT on goods (TWA suppliers): 1%. WI158 - EWT on services (TWA suppliers): 2%. WC100 - EWT on rent paid to corporations: 5%. WC120 - EWT on contractors (corporations): 2%. WI640 - EWT on payments to partners by GPP: 10%/15%. WI010 requires TIN of payee. BIR Form 2307 must cite the correct ATC for each payment type.',
'{"topic": "atc_codes", "form": "BIR_2307"}'),

(uuid_generate_v4(), 'BIR Form 1601-EQ Instructions', 'withholding',
'BIR 1601-EQ (Quarterly Remittance Return of Creditable Income Taxes Withheld - Expanded): Filed quarterly by withholding agents. Due: last day of month following end of quarter (Q1: April 30, Q2: July 31, Q3: October 31, Q4: January 31). Must be accompanied by: (1) Quarterly Alphalist of Payees (QAP) in CSV format via eFPS/eBIRForms. (2) Summary List of Sales/Purchases if applicable. Monthly remittance via BIR 0619-E remains due on 10th of following month for first 2 months of each quarter.',
'{"form": "BIR_1601EQ", "topic": "quarterly_ewt_return"}'),

(uuid_generate_v4(), 'Withholding Tax on Compensation (Detailed)', 'withholding',
'Withholding Tax on Compensation: Employers withhold based on graduated income tax rates. Tax base = Gross compensation less: (1) Non-taxable 13th month pay and bonuses (up to PHP 90,000); (2) De minimis benefits within limits; (3) Mandatory contributions (SSS, PhilHealth, Pag-IBIG). Monthly withholding computed using annualized method. Minimum wage earners are EXEMPT from withholding tax. BIR 1601-C filed monthly (10th of following month). BIR 1604-CF annual reconciliation due January 31 of following year with attached BIR 2316 (Certificate of Compensation Payment/Tax Withheld) for each employee.',
'{"form": "BIR_1601C", "topic": "compensation_withholding"}'),

-- ========== Income Tax (expanded) ==========

(uuid_generate_v4(), 'TRAIN Law - 8% Flat Tax Option', 'income_tax',
'8% Flat Tax Option for Self-Employed: Available to self-employed individuals and professionals with gross sales/receipts not exceeding PHP 3,000,000. Tax = 8% of (Gross Sales/Receipts - PHP 250,000). Election is irrevocable for the taxable year. Must signify intent in first quarterly ITR (BIR 1701Q) or BIR registration (Form 1905). If gross sales exceed PHP 3M during the year, taxpayer automatically shifts to graduated rates for the entire year. Not available to VAT-registered taxpayers, partners in a GPP, or those subject to other percentage taxes. Simpler compliance: no bookkeeping requirements, no need to track expenses.',
'{"law": "TRAIN", "topic": "8_percent_flat_tax"}'),

(uuid_generate_v4(), 'NIRC Section 34 - Allowable Deductions', 'income_tax',
'Allowable Deductions for Income Tax: Two options: (A) Itemized Deductions: Ordinary and necessary business expenses including: salaries, rent, depreciation, repairs, bad debts, taxes, interest, losses, charitable contributions (max 5%/10% of taxable income), research and development, pension trusts. (B) Optional Standard Deduction (OSD): 40% of gross sales/receipts for individuals; 40% of gross income for corporations. OSD is irrevocable for the taxable year. Must be signified in the quarterly return. For married individuals filing separately, only one spouse can claim OSD.',
'{"section": "34", "law": "NIRC", "topic": "deductions"}'),

(uuid_generate_v4(), 'De Minimis Benefits (Tax-Exempt)', 'income_tax',
'De Minimis Benefits (Exempt from Income Tax and Withholding): (1) Monetized unused vacation leave credits max 10 days. (2) Medical cash allowance to dependents max PHP 1,500/semester or PHP 250/month. (3) Rice subsidy max PHP 2,000/month or 1 sack 50kg/month. (4) Uniform/clothing allowance max PHP 6,000/year. (5) Actual medical assistance max PHP 10,000/year. (6) Laundry allowance max PHP 300/month. (7) Achievement awards max PHP 10,000/year. (8) Christmas gifts max PHP 5,000/year. (9) Daily meal allowance during overtime max 25% of basic minimum wage. (10) CBA benefits max PHP 10,000/year. Excess de minimis added to 13th month/bonus threshold (PHP 90,000).',
'{"regulation": "RR 2-98 Sec 2.78.1", "topic": "de_minimis_benefits"}'),

(uuid_generate_v4(), 'CREATE MORE Act (RA 12066)', 'income_tax',
'CREATE MORE Act (October 2024): Amends original CREATE Law with enhanced incentives: (1) Corporate income tax reduced to 20% for registered business enterprises under Enhanced Deductions Regime (EDR). (2) 100% deduction for power costs (previously partial). (3) Net Operating Loss Carry-Over (NOLCO) extended. (4) Enhanced VAT zero-rating for directly attributable registered activities. (5) Additional deductions for depreciation of qualified capital expenditures. (6) Special tax rate of 5% on gross income for export enterprises. (7) Income Tax Holiday extended: 4-7 years for qualifying enterprises. (8) Duty exemption on importation of capital equipment and raw materials. Benefits administered through FIRB (Fiscal Incentives Review Board).',
'{"law": "RA 12066", "topic": "create_more_act"}'),

(uuid_generate_v4(), 'MCIT Rules (Minimum Corporate Income Tax)', 'income_tax',
'Minimum Corporate Income Tax (MCIT): 2% of gross income, applicable from the 4th taxable year of business operations. Payable when MCIT exceeds Regular Corporate Income Tax (RCIT). MCIT was temporarily reduced to 1% from July 2020 to June 2023 under CREATE Law Sec. 4. Any excess MCIT over RCIT can be carried forward and credited against RCIT for the next 3 consecutive taxable years. Gross income = Gross sales less sales returns/discounts/allowances and cost of goods sold. For service companies: gross income = gross receipts less direct costs.',
'{"section": "27(E)", "law": "NIRC", "topic": "mcit"}'),

(uuid_generate_v4(), 'Percentage Tax (Non-VAT)', 'income_tax',
'Percentage Tax for Non-VAT Registered: 3% on quarterly gross sales/receipts for persons not VAT-registered (annual gross sales <= PHP 3M). Filed quarterly using BIR Form 2551Q, due within 25 days after each quarter. EOPT Act: Micro and small taxpayers may file semi-annually. Cannot claim input tax credits. Persons registered as VAT cannot opt for percentage tax unless deregistered.',
'{"section": "116", "law": "NIRC", "topic": "percentage_tax"}'),

-- ========== Compliance (expanded) ==========

(uuid_generate_v4(), 'RMC No. 34-2025 (AITR Filing Guidelines)', 'compliance',
'Annual Income Tax Return Filing (RMC 34-2025): For CY 2024 AITR due April 15, 2025. Must file electronically via eFPS, eBIRForms v7.9.4.2, or Tax Software Providers (TSPs). Manual filing only for: (a) Micro/Small taxpayers using BIR 1701-MS, (b) system unavailability, (c) Commissioner-approved reasons. AITRs in eFPS: 1700, 1701A, 1701, 1702RT, 1702-EX, 1702-MX. Attachments submitted via eAFS system within 15 days of filing deadline. Payment via AABs, RCOs (cash up to PHP 20K), or ePay gateways: Landbank Link.BizPortal, DBP PayTax Online, UnionBank Online, Maya, MyEG (GCash, Maya, GrabPay, ShopeePay).',
'{"regulation": "RMC 34-2025", "topic": "aitr_filing_2024"}'),

(uuid_generate_v4(), 'RR No. 7-2024 (EOPT Invoicing)', 'compliance',
'Invoicing Requirements under EOPT Act (RR 7-2024): Implements unified invoicing. Official Receipts are eliminated; only Sales Invoices required for both goods and services. VAT Invoice must contain: (1) Seller TIN and business name. (2) Buyer TIN (for sales >= PHP 500). (3) Date of transaction. (4) Quantity/unit cost/description. (5) Total amount with VAT shown separately. (6) Words "VAT REGISTERED" and the invoice serial number. Non-VAT registered must print "NON-VAT REGISTERED". E-invoicing systems (CRM/POS/e-receipting) require BIR permit. Books of accounts must be preserved for 10 years from date of last entry (5 years under EOPT for Micro taxpayers).',
'{"regulation": "RR 7-2024", "law": "RA 11976", "topic": "invoicing_eopt"}'),

(uuid_generate_v4(), 'EOPT Taxpayer Classification', 'compliance',
'Taxpayer Classification under EOPT Act (RA 11976): (1) MICRO: Gross sales/receipts <= PHP 3,000,000. Simplified returns, reduced penalties, 5-year record retention. (2) SMALL: Gross sales > PHP 3M to PHP 20M. Simplified compliance requirements. (3) MEDIUM: Gross sales > PHP 20M to PHP 1B. Standard compliance. (4) LARGE: Gross sales > PHP 1B. Enhanced reporting, mandatory eFPS, top withholding agent designation. Classification determines: applicable filing methods, penalty rates, record retention period, and withholding agent obligations.',
'{"law": "RA 11976", "topic": "taxpayer_classification"}'),

(uuid_generate_v4(), 'BIR Registration Requirements', 'compliance',
'BIR Registration (RR 7-2024): All persons subject to internal revenue taxes must register with BIR. Registration date: within 30 days before start of business. Place: Revenue District Office (RDO) where principal office is located. Requirements: (1) BIR Form 1901 (self-employed/professional) or 1903 (corporation/partnership). (2) DTI certificate (sole proprietor) or SEC registration (corporation). (3) Barangay clearance. (4) Mayor/Business permit. Annual registration fee: ELIMINATED under EOPT Act. Certificate of Registration (COR/BIR Form 2303) must be posted conspicuously. For online businesses: proof of registration must be posted on website/e-commerce platform.',
'{"regulation": "RR 7-2024", "topic": "registration"}'),

(uuid_generate_v4(), 'Penalties and Interest (Detailed)', 'compliance',
'BIR Penalties and Interest (Detailed): (1) Surcharge: 25% for late filing, wrong venue, failure to file. 50% for willful neglect, fraud, false return. (2) Interest: 12% per annum (double legal interest) on unpaid tax from due date until payment. Under EOPT for Micro/Small: reduced to 6%. (3) Compromise penalties: vary by violation type, from PHP 200 to PHP 50,000. (4) Criminal penalties: PHP 10,000-100,000 fine and/or 1-10 years imprisonment for willful tax evasion. (5) Non-filing penalty: PHP 1,000 per unfiled return, max PHP 25,000/year. (6) Failure to withhold: withholding agent liable for tax plus 25% surcharge + interest.',
'{"section": "248-253", "law": "NIRC", "topic": "penalties_detailed"}'),

-- ========== BIR Forms (detailed) ==========

(uuid_generate_v4(), 'BIR Form 2316 Instructions', 'withholding',
'BIR 2316 (Certificate of Compensation Payment/Tax Withheld): Employer issues to each employee by January 31 of following year. Contains: Employee TIN, compensation details (basic pay, 13th month, other benefits), mandatory contributions (SSS, PhilHealth, Pag-IBIG), taxable income, tax due, tax withheld. Serves as the employee annual ITR (substituted filing) if: (a) single employer during the year, (b) tax properly withheld, (c) no other income. Employees with multiple employers or mixed income must file BIR 1700/1701 and attach all 2316s received.',
'{"form": "BIR_2316", "topic": "compensation_certificate"}'),

(uuid_generate_v4(), 'BIR Form 1701Q Instructions', 'income_tax',
'BIR 1701Q (Quarterly Income Tax Return for Self-Employed/Professionals): Filed within 60 days after each quarter (Q1: May 30, Q2: August 29, Q3: November 29). First quarter return must indicate choice of: (a) graduated rates with itemized deductions, (b) graduated rates with OSD, or (c) 8% flat tax. Election is irrevocable for the year. Compute: Gross sales/receipts - Cost of sales - Operating expenses = Taxable income. Apply graduated rates or 8%. Deduct prior quarter tax credits. Attach: BIR 2307s received during quarter.',
'{"form": "BIR_1701Q", "topic": "quarterly_itr_individual"}'),

-- ========== Recent Laws ==========

(uuid_generate_v4(), 'RA 12214 (Capital Markets Act)', 'general',
'Capital Markets Efficiency Promotion Act (RA 12214, 2024): (1) Stock Transaction Tax reduced from 0.6% to 0.1% of gross selling price. (2) Flat 20% Final Withholding Tax on all interest income (unified). (3) Capital Gains Tax on sale of shares not traded in stock exchange: 15% of net capital gains. (4) Documentary Stamp Tax on original issuance of shares: reduced from 1% to 0.75% of par value. (5) IPO Tax: 1-2% depending on proportion of shares sold. Effective for transactions starting January 1, 2025.',
'{"law": "RA 12214", "topic": "capital_markets_tax"}'),

(uuid_generate_v4(), 'BIR e-Invoicing System (RR 11-2025)', 'compliance',
'BIR Electronic Invoicing and Sales Reporting (RR 11-2025): BIR mandates e-invoicing for large taxpayers in phases. Electronic invoice must: (1) be generated by BIR-accredited e-invoicing system, (2) contain unique reference number, (3) be transmitted to BIR in near-real-time, (4) include digital signature/QR code. Taxpayers implementing e-invoicing may claim additional deductions for setup costs. Timeline: Large taxpayers first (2025), Medium (2026), Small/Micro (phased). E-invoicing replaces requirement for Authority to Print (ATP) for covered taxpayers.',
'{"regulation": "RR 11-2025", "topic": "e_invoicing"}'),

-- ========== Other Tax Types ==========

(uuid_generate_v4(), 'Estate Tax (RA 10963 TRAIN)', 'general',
'Estate Tax: Flat 6% of net estate value (simplified from previous six-bracket system under TRAIN Law). Net estate = Gross estate less: (1) Standard deduction of PHP 5,000,000. (2) Claims against estate. (3) Unpaid mortgages. (4) Property previously taxed (vanishing deduction). (5) Transfers for public use. (6) Family home up to PHP 10,000,000. (7) Amount received under RA 4917 (retirement benefits). Filing: BIR Form 1801 within 1 year of death (extendable by 30 days). Late filing: 25% surcharge + interest.',
'{"law": "TRAIN", "section": "84-97", "topic": "estate_tax"}'),

(uuid_generate_v4(), 'Donors Tax (RA 10963 TRAIN)', 'general',
'Donors Tax: Flat 6% on gifts exceeding PHP 250,000 aggregate per calendar year (simplified under TRAIN Law). Exempt donations: (1) Gifts to national government or political subdivision. (2) Gifts to accredited educational, charitable, religious, cultural, or social welfare institutions (max 30% of donor''s taxable income). (3) Prizes and awards in sports/scientific/educational/artistic achievement. Dowry or gift for wedding: first PHP 10,000 exempt. Filing: BIR Form 1800 within 30 days of donation.',
'{"law": "TRAIN", "section": "98-104", "topic": "donors_tax"}'),

(uuid_generate_v4(), 'Capital Gains Tax', 'general',
'Capital Gains Tax: (1) Sale of real property classified as capital asset: 6% of gross selling price or fair market value (whichever is higher). Filed via BIR Form 1706 within 30 days of sale. (2) Sale of shares of stock NOT traded in stock exchange: 15% of net capital gains. Filed via BIR Form 1707. (3) Sale of shares traded in stock exchange: 0.1% stock transaction tax (reduced from 0.6% under RA 12214). Capital gains tax is a FINAL tax - not creditable against income tax.',
'{"section": "24(C)(D)", "law": "NIRC", "topic": "capital_gains_tax"}'),

(uuid_generate_v4(), 'Documentary Stamp Tax', 'general',
'Documentary Stamp Tax (DST): Tax on documents, instruments, loan agreements evidencing transactions. Common rates: (1) Debt instruments: PHP 1.50 per PHP 200 (0.75%). (2) Original issuance of shares: PHP 2 per PHP 200 par value (reduced to 0.75% under RA 12214). (3) Transfer of shares: PHP 1.50 per PHP 200. (4) Bank checks: PHP 3 per check. (5) Bills of exchange/drafts: PHP 0.60 per PHP 200. (6) Life insurance policies: PHP 0.50 per PHP 200 of amount insured. (7) Deed of sale of real property: PHP 15 per PHP 1,000. Filed via BIR Form 2000/2000-OT within 5 days of making/signing document.',
'{"section": "173-201", "law": "NIRC", "topic": "documentary_stamp_tax"}'),

(uuid_generate_v4(), 'Local Business Tax', 'general',
'Local Business Tax (LBT): Imposed by LGUs (cities/municipalities) on businesses. Rates: 0.5% to 3% of gross sales/receipts (varies by LGU and business type). Payment: Usually annually (January 20) or quarterly. Requirements: Mayor''s/Business permit renewed annually. Real Property Tax: up to 1% (provinces) or 2% (Metro Manila cities) of assessed value + 1% Special Education Fund (SEF). Community Tax: PHP 5 base + PHP 1 per PHP 1,000 income for individuals; PHP 500 base + PHP 2 per PHP 5,000 gross receipts for corporations.',
'{"topic": "local_taxes", "law": "Local Government Code"}'),

-- ========== Tax Filing Calendar (Comprehensive) ==========

(uuid_generate_v4(), 'BIR Complete Filing Calendar 2025-2026', 'compliance',
'Complete BIR Filing Calendar: MONTHLY: (1) BIR 0619-E (EWT remittance): 10th of following month. (2) BIR 1601-C (Compensation tax): 10th of following month. (3) BIR 0619-F (Final tax remittance): 10th of following month. QUARTERLY: (4) BIR 2550Q (Quarterly VAT): 25th of month after quarter end. (5) BIR 1601-EQ (Quarterly EWT): last day of month after quarter. (6) BIR 1701Q/1702Q (Quarterly ITR): within 60 days after quarter end. (7) BIR 2551Q (Percentage Tax): 25th of month after quarter end. ANNUAL: (8) BIR 1604-CF (Compensation reconciliation): January 31. (9) BIR 1604-E (EWT reconciliation): March 1. (10) BIR 1701/1700 (Individual ITR): April 15. (11) BIR 1702 (Corporate ITR): 15th of 4th month after fiscal year end. (12) Business permit renewal: January 20. (13) BIR 2316 issuance to employees: January 31.',
'{"topic": "filing_calendar_complete"}')

ON CONFLICT DO NOTHING;
