-- Remove supplemental BIR knowledge chunks added in migration 013
DELETE FROM knowledge_chunks WHERE source IN (
    'NIRC Section 109',
    'NIRC Section 106(A)(2)',
    'RR No. 16-2005 as amended',
    'RA 12023 (Digital Services VAT Act)',
    'RA 11976 (EOPT Act) - VAT Changes',
    'BIR Form 2550Q Instructions',
    'RR No. 2-98 Sec. 2.57.2 (Complete EWT Rates)',
    'RR No. 24-2025 (Top Withholding Agents)',
    'NIRC Section 57(A) - Final Withholding Tax',
    'BIR ATC Codes (Common EWT)',
    'BIR Form 1601-EQ Instructions',
    'Withholding Tax on Compensation (Detailed)',
    'TRAIN Law - 8% Flat Tax Option',
    'NIRC Section 34 - Allowable Deductions',
    'De Minimis Benefits (Tax-Exempt)',
    'CREATE MORE Act (RA 12066)',
    'MCIT Rules (Minimum Corporate Income Tax)',
    'Percentage Tax (Non-VAT)',
    'RMC No. 34-2025 (AITR Filing Guidelines)',
    'RR No. 7-2024 (EOPT Invoicing)',
    'EOPT Taxpayer Classification',
    'BIR Registration Requirements',
    'Penalties and Interest (Detailed)',
    'BIR Form 2316 Instructions',
    'BIR Form 1701Q Instructions',
    'RA 12214 (Capital Markets Act)',
    'BIR e-Invoicing System (RR 11-2025)',
    'Estate Tax (RA 10963 TRAIN)',
    'Donors Tax (RA 10963 TRAIN)',
    'Capital Gains Tax',
    'Documentary Stamp Tax',
    'Local Business Tax',
    'BIR Complete Filing Calendar 2025-2026'
);
