// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounting_periods.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAccountingPeriod = `-- name: CloseAccountingPeriod :exec
UPDATE accounting_periods SET
    status = 'closed',
    closed_by = $2,
    closed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'open'
`

type CloseAccountingPeriodParams struct {
	ID       uuid.UUID   `json:"id"`
	ClosedBy pgtype.UUID `json:"closed_by"`
}

func (q *Queries) CloseAccountingPeriod(ctx context.Context, arg CloseAccountingPeriodParams) error {
	_, err := q.db.Exec(ctx, closeAccountingPeriod, arg.ID, arg.ClosedBy)
	return err
}

const createAccountingPeriod = `-- name: CreateAccountingPeriod :one
INSERT INTO accounting_periods (id, company_id, name, period_type, start_date, end_date, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'open', NOW(), NOW())
RETURNING id, company_id, name, period_type, start_date, end_date, status, closed_by, closed_at, created_at, updated_at
`

type CreateAccountingPeriodParams struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	Name       string      `json:"name"`
	PeriodType string      `json:"period_type"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateAccountingPeriod(ctx context.Context, arg CreateAccountingPeriodParams) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, createAccountingPeriod,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.PeriodType,
		arg.StartDate,
		arg.EndDate,
	)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.PeriodType,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPeriodByDate = `-- name: FindPeriodByDate :one
SELECT id, company_id, name, period_type, start_date, end_date, status, closed_by, closed_at, created_at, updated_at FROM accounting_periods
WHERE company_id = $1
    AND start_date <= $2
    AND end_date >= $2
    AND status = 'open'
LIMIT 1
`

type FindPeriodByDateParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) FindPeriodByDate(ctx context.Context, arg FindPeriodByDateParams) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, findPeriodByDate, arg.CompanyID, arg.StartDate)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.PeriodType,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountingPeriodByID = `-- name: GetAccountingPeriodByID :one
SELECT id, company_id, name, period_type, start_date, end_date, status, closed_by, closed_at, created_at, updated_at FROM accounting_periods WHERE id = $1
`

func (q *Queries) GetAccountingPeriodByID(ctx context.Context, id uuid.UUID) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, getAccountingPeriodByID, id)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.PeriodType,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountingPeriods = `-- name: ListAccountingPeriods :many
SELECT id, company_id, name, period_type, start_date, end_date, status, closed_by, closed_at, created_at, updated_at FROM accounting_periods
WHERE company_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListAccountingPeriods(ctx context.Context, companyID uuid.UUID) ([]AccountingPeriod, error) {
	rows, err := q.db.Query(ctx, listAccountingPeriods, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingPeriod{}
	for rows.Next() {
		var i AccountingPeriod
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.PeriodType,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenAccountingPeriod = `-- name: ReopenAccountingPeriod :exec
UPDATE accounting_periods SET
    status = 'open',
    closed_by = NULL,
    closed_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND status = 'closed'
`

func (q *Queries) ReopenAccountingPeriod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reopenAccountingPeriod, id)
	return err
}
