// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_mappings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAccountBySubType = `-- name: GetAccountBySubType :one
SELECT id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at FROM accounts
WHERE company_id = $1 AND sub_type = $2 AND is_active = true
LIMIT 1
`

type GetAccountBySubTypeParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	SubType   *string   `json:"sub_type"`
}

func (q *Queries) GetAccountBySubType(ctx context.Context, arg GetAccountBySubTypeParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountBySubType, arg.CompanyID, arg.SubType)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AccountNumber,
		&i.Name,
		&i.AccountType,
		&i.SubType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.IsSystem,
		&i.NormalBalance,
		&i.QboAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchedTransactionsWithoutJournal = `-- name: GetMatchedTransactionsWithoutJournal :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount, submitted_by, ref_number, account_code, tax_code, department, project FROM transactions
WHERE company_id = $1
  AND match_status IN ('matched', 'split_matched')
  AND journal_entry_id IS NULL
ORDER BY date ASC, row_index ASC
`

func (q *Queries) GetMatchedTransactionsWithoutJournal(ctx context.Context, companyID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getMatchedTransactionsWithoutJournal, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
			&i.SubmittedBy,
			&i.RefNumber,
			&i.AccountCode,
			&i.TaxCode,
			&i.Department,
			&i.Project,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
