// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalance = `-- name: AccountBalance :one
SELECT
    a.id,
    a.account_number,
    a.name,
    a.account_type,
    a.normal_balance,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(15,2) AS total_debit,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(15,2) AS total_credit
FROM accounts a
LEFT JOIN journal_lines jl ON jl.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
    AND je.status = 'posted'
    AND je.entry_date <= $2
WHERE a.id = $1
GROUP BY a.id
`

type AccountBalanceParams struct {
	ID        uuid.UUID   `json:"id"`
	EntryDate pgtype.Date `json:"entry_date"`
}

type AccountBalanceRow struct {
	ID            uuid.UUID      `json:"id"`
	AccountNumber string         `json:"account_number"`
	Name          string         `json:"name"`
	AccountType   string         `json:"account_type"`
	NormalBalance string         `json:"normal_balance"`
	TotalDebit    pgtype.Numeric `json:"total_debit"`
	TotalCredit   pgtype.Numeric `json:"total_credit"`
}

func (q *Queries) AccountBalance(ctx context.Context, arg AccountBalanceParams) (AccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, accountBalance, arg.ID, arg.EntryDate)
	var i AccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.Name,
		&i.AccountType,
		&i.NormalBalance,
		&i.TotalDebit,
		&i.TotalCredit,
	)
	return i, err
}

const countAccountsByCompany = `-- name: CountAccountsByCompany :one
SELECT COUNT(*) FROM accounts WHERE company_id = $1 AND is_active = true
`

func (q *Queries) CountAccountsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW())
RETURNING id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at
`

type CreateAccountParams struct {
	ID            uuid.UUID   `json:"id"`
	CompanyID     uuid.UUID   `json:"company_id"`
	AccountNumber string      `json:"account_number"`
	Name          string      `json:"name"`
	AccountType   string      `json:"account_type"`
	SubType       *string     `json:"sub_type"`
	ParentID      pgtype.UUID `json:"parent_id"`
	Description   *string     `json:"description"`
	IsActive      bool        `json:"is_active"`
	IsSystem      bool        `json:"is_system"`
	NormalBalance string      `json:"normal_balance"`
	QboAccountID  *string     `json:"qbo_account_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.CompanyID,
		arg.AccountNumber,
		arg.Name,
		arg.AccountType,
		arg.SubType,
		arg.ParentID,
		arg.Description,
		arg.IsActive,
		arg.IsSystem,
		arg.NormalBalance,
		arg.QboAccountID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AccountNumber,
		&i.Name,
		&i.AccountType,
		&i.SubType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.IsSystem,
		&i.NormalBalance,
		&i.QboAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSystemAccountsNotIn = `-- name: DeactivateSystemAccountsNotIn :exec
UPDATE accounts SET is_active = false, updated_at = NOW()
WHERE company_id = $1 AND is_system = true AND account_number != ALL($2::text[])
`

type DeactivateSystemAccountsNotInParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Column2   []string  `json:"column_2"`
}

func (q *Queries) DeactivateSystemAccountsNotIn(ctx context.Context, arg DeactivateSystemAccountsNotInParams) error {
	_, err := q.db.Exec(ctx, deactivateSystemAccountsNotIn, arg.CompanyID, arg.Column2)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AccountNumber,
		&i.Name,
		&i.AccountType,
		&i.SubType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.IsSystem,
		&i.NormalBalance,
		&i.QboAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByNumber = `-- name: GetAccountByNumber :one
SELECT id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at FROM accounts WHERE company_id = $1 AND account_number = $2
`

type GetAccountByNumberParams struct {
	CompanyID     uuid.UUID `json:"company_id"`
	AccountNumber string    `json:"account_number"`
}

func (q *Queries) GetAccountByNumber(ctx context.Context, arg GetAccountByNumberParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByNumber, arg.CompanyID, arg.AccountNumber)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AccountNumber,
		&i.Name,
		&i.AccountType,
		&i.SubType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.IsSystem,
		&i.NormalBalance,
		&i.QboAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByQBOID = `-- name: GetAccountByQBOID :one
SELECT id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at FROM accounts WHERE company_id = $1 AND qbo_account_id = $2
`

type GetAccountByQBOIDParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	QboAccountID *string   `json:"qbo_account_id"`
}

func (q *Queries) GetAccountByQBOID(ctx context.Context, arg GetAccountByQBOIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByQBOID, arg.CompanyID, arg.QboAccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AccountNumber,
		&i.Name,
		&i.AccountType,
		&i.SubType,
		&i.ParentID,
		&i.Description,
		&i.IsActive,
		&i.IsSystem,
		&i.NormalBalance,
		&i.QboAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByCompany = `-- name: ListAccountsByCompany :many
SELECT id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at FROM accounts
WHERE company_id = $1 AND is_active = true
ORDER BY account_number ASC
LIMIT $2 OFFSET $3
`

type ListAccountsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListAccountsByCompany(ctx context.Context, arg ListAccountsByCompanyParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.AccountNumber,
			&i.Name,
			&i.AccountType,
			&i.SubType,
			&i.ParentID,
			&i.Description,
			&i.IsActive,
			&i.IsSystem,
			&i.NormalBalance,
			&i.QboAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByType = `-- name: ListAccountsByType :many
SELECT id, company_id, account_number, name, account_type, sub_type, parent_id, description, is_active, is_system, normal_balance, qbo_account_id, created_at, updated_at FROM accounts
WHERE company_id = $1 AND account_type = $2 AND is_active = true
ORDER BY account_number ASC
`

type ListAccountsByTypeParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	AccountType string    `json:"account_type"`
}

func (q *Queries) ListAccountsByType(ctx context.Context, arg ListAccountsByTypeParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByType, arg.CompanyID, arg.AccountType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.AccountNumber,
			&i.Name,
			&i.AccountType,
			&i.SubType,
			&i.ParentID,
			&i.Description,
			&i.IsActive,
			&i.IsSystem,
			&i.NormalBalance,
			&i.QboAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET
    name = COALESCE($2, name),
    sub_type = $3,
    description = $4,
    is_active = COALESCE($5, is_active),
    qbo_account_id = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccountParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	SubType      *string   `json:"sub_type"`
	Description  *string   `json:"description"`
	IsActive     bool      `json:"is_active"`
	QboAccountID *string   `json:"qbo_account_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.SubType,
		arg.Description,
		arg.IsActive,
		arg.QboAccountID,
	)
	return err
}
