// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_threads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAgentThread = `-- name: ArchiveAgentThread :exec
UPDATE agent_threads SET status = 'archived', updated_at = NOW() WHERE id = $1
`

func (q *Queries) ArchiveAgentThread(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveAgentThread, id)
	return err
}

const createAgentActionLog = `-- name: CreateAgentActionLog :one
INSERT INTO agent_action_logs (id, thread_id, company_id, user_id, agent_id, action_name, action_input, action_result, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, thread_id, company_id, user_id, agent_id, action_name, action_input, action_result, status, created_at
`

type CreateAgentActionLogParams struct {
	ID           uuid.UUID   `json:"id"`
	ThreadID     pgtype.UUID `json:"thread_id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	UserID       uuid.UUID   `json:"user_id"`
	AgentID      string      `json:"agent_id"`
	ActionName   string      `json:"action_name"`
	ActionInput  []byte      `json:"action_input"`
	ActionResult []byte      `json:"action_result"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateAgentActionLog(ctx context.Context, arg CreateAgentActionLogParams) (AgentActionLog, error) {
	row := q.db.QueryRow(ctx, createAgentActionLog,
		arg.ID,
		arg.ThreadID,
		arg.CompanyID,
		arg.UserID,
		arg.AgentID,
		arg.ActionName,
		arg.ActionInput,
		arg.ActionResult,
		arg.Status,
	)
	var i AgentActionLog
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentID,
		&i.ActionName,
		&i.ActionInput,
		&i.ActionResult,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createAgentMessage = `-- name: CreateAgentMessage :one
INSERT INTO chat_messages (id, company_id, user_id, role, content, tool_calls, thread_id, agent_id, message_type, citations_json, action_results_json, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
RETURNING id, company_id, user_id, role, content, tool_calls, created_at, thread_id, agent_id, message_type, citations_json, action_results_json
`

type CreateAgentMessageParams struct {
	ID                uuid.UUID   `json:"id"`
	CompanyID         uuid.UUID   `json:"company_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Role              string      `json:"role"`
	Content           string      `json:"content"`
	ToolCalls         []byte      `json:"tool_calls"`
	ThreadID          pgtype.UUID `json:"thread_id"`
	AgentID           *string     `json:"agent_id"`
	MessageType       *string     `json:"message_type"`
	CitationsJson     []byte      `json:"citations_json"`
	ActionResultsJson []byte      `json:"action_results_json"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createAgentMessage,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ThreadID,
		arg.AgentID,
		arg.MessageType,
		arg.CitationsJson,
		arg.ActionResultsJson,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.CreatedAt,
		&i.ThreadID,
		&i.AgentID,
		&i.MessageType,
		&i.CitationsJson,
		&i.ActionResultsJson,
	)
	return i, err
}

const createAgentThread = `-- name: CreateAgentThread :one
INSERT INTO agent_threads (id, company_id, user_id, agent_id, workflow_type, entity_type, entity_id, title, status, context_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'active', $9)
RETURNING id, company_id, user_id, agent_id, workflow_type, entity_type, entity_id, title, status, context_json, created_at, updated_at
`

type CreateAgentThreadParams struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	UserID       uuid.UUID   `json:"user_id"`
	AgentID      string      `json:"agent_id"`
	WorkflowType *string     `json:"workflow_type"`
	EntityType   *string     `json:"entity_type"`
	EntityID     pgtype.UUID `json:"entity_id"`
	Title        *string     `json:"title"`
	ContextJson  []byte      `json:"context_json"`
}

func (q *Queries) CreateAgentThread(ctx context.Context, arg CreateAgentThreadParams) (AgentThread, error) {
	row := q.db.QueryRow(ctx, createAgentThread,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.AgentID,
		arg.WorkflowType,
		arg.EntityType,
		arg.EntityID,
		arg.Title,
		arg.ContextJson,
	)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentID,
		&i.WorkflowType,
		&i.EntityType,
		&i.EntityID,
		&i.Title,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAgentThread = `-- name: FindAgentThread :one
SELECT id, company_id, user_id, agent_id, workflow_type, entity_type, entity_id, title, status, context_json, created_at, updated_at FROM agent_threads
WHERE company_id = $1
  AND agent_id = $2
  AND ($3 = '' OR entity_type = $3)
  AND ($4::UUID IS NULL OR entity_id = $4)
  AND status = 'active'
ORDER BY updated_at DESC
LIMIT 1
`

type FindAgentThreadParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	AgentID   string      `json:"agent_id"`
	Column3   interface{} `json:"column_3"`
	Column4   uuid.UUID   `json:"column_4"`
}

func (q *Queries) FindAgentThread(ctx context.Context, arg FindAgentThreadParams) (AgentThread, error) {
	row := q.db.QueryRow(ctx, findAgentThread,
		arg.CompanyID,
		arg.AgentID,
		arg.Column3,
		arg.Column4,
	)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentID,
		&i.WorkflowType,
		&i.EntityType,
		&i.EntityID,
		&i.Title,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentThread = `-- name: GetAgentThread :one
SELECT id, company_id, user_id, agent_id, workflow_type, entity_type, entity_id, title, status, context_json, created_at, updated_at FROM agent_threads WHERE id = $1
`

func (q *Queries) GetAgentThread(ctx context.Context, id uuid.UUID) (AgentThread, error) {
	row := q.db.QueryRow(ctx, getAgentThread, id)
	var i AgentThread
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentID,
		&i.WorkflowType,
		&i.EntityType,
		&i.EntityID,
		&i.Title,
		&i.Status,
		&i.ContextJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentThreads = `-- name: ListAgentThreads :many
SELECT id, company_id, user_id, agent_id, workflow_type, entity_type, entity_id, title, status, context_json, created_at, updated_at FROM agent_threads
WHERE company_id = $1
  AND ($2 = '' OR agent_id = $2)
  AND status = 'active'
ORDER BY updated_at DESC
LIMIT $3 OFFSET $4
`

type ListAgentThreadsParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Column2   interface{} `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListAgentThreads(ctx context.Context, arg ListAgentThreadsParams) ([]AgentThread, error) {
	rows, err := q.db.Query(ctx, listAgentThreads,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentThread{}
	for rows.Next() {
		var i AgentThread
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AgentID,
			&i.WorkflowType,
			&i.EntityType,
			&i.EntityID,
			&i.Title,
			&i.Status,
			&i.ContextJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByThread = `-- name: ListMessagesByThread :many
SELECT id, company_id, user_id, role, content, tool_calls, created_at, thread_id, agent_id, message_type, citations_json, action_results_json FROM chat_messages
WHERE thread_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type ListMessagesByThreadParams struct {
	ThreadID pgtype.UUID `json:"thread_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListMessagesByThread(ctx context.Context, arg ListMessagesByThreadParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listMessagesByThread, arg.ThreadID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.ThreadID,
			&i.AgentID,
			&i.MessageType,
			&i.CitationsJson,
			&i.ActionResultsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentThread = `-- name: UpdateAgentThread :exec
UPDATE agent_threads
SET title = COALESCE(NULLIF($2, ''), title),
    context_json = COALESCE($3, context_json),
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentThreadParams struct {
	ID          uuid.UUID   `json:"id"`
	Column2     interface{} `json:"column_2"`
	ContextJson []byte      `json:"context_json"`
}

func (q *Queries) UpdateAgentThread(ctx context.Context, arg UpdateAgentThreadParams) error {
	_, err := q.db.Exec(ctx, updateAgentThread, arg.ID, arg.Column2, arg.ContextJson)
	return err
}
