// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsByCompany = `-- name: CountAuditLogsByCompany :one
SELECT COUNT(*) FROM audit_logs WHERE company_id = $1
`

func (q *Queries) CountAuditLogsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (id, company_id, user_id, entity_type, entity_id, action, changes, comment, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id, company_id, user_id, entity_type, entity_id, action, changes, comment, created_at, entry_hash, prev_hash, ip_address, user_agent
`

type CreateAuditLogParams struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	UserID     pgtype.UUID `json:"user_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Action     string      `json:"action"`
	Changes    []byte      `json:"changes"`
	Comment    *string     `json:"comment"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Changes,
		arg.Comment,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Changes,
		&i.Comment,
		&i.CreatedAt,
		&i.EntryHash,
		&i.PrevHash,
		&i.IpAddress,
		&i.UserAgent,
	)
	return i, err
}

const listAuditLogsByCompany = `-- name: ListAuditLogsByCompany :many
SELECT id, company_id, user_id, entity_type, entity_id, action, changes, comment, created_at, entry_hash, prev_hash, ip_address, user_agent FROM audit_logs WHERE company_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListAuditLogsByCompany(ctx context.Context, arg ListAuditLogsByCompanyParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Changes,
			&i.Comment,
			&i.CreatedAt,
			&i.EntryHash,
			&i.PrevHash,
			&i.IpAddress,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, company_id, user_id, entity_type, entity_id, action, changes, comment, created_at, entry_hash, prev_hash, ip_address, user_agent FROM audit_logs WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListAuditLogsByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Changes,
			&i.Comment,
			&i.CreatedAt,
			&i.EntryHash,
			&i.PrevHash,
			&i.IpAddress,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
