// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (id, company_id, user_id, role, content, tool_calls, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, company_id, user_id, role, content, tool_calls, created_at, thread_id, agent_id, message_type, citations_json, action_results_json
`

type CreateChatMessageParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	Content   string    `json:"content"`
	ToolCalls []byte    `json:"tool_calls"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.CreatedAt,
		&i.ThreadID,
		&i.AgentID,
		&i.MessageType,
		&i.CitationsJson,
		&i.ActionResultsJson,
	)
	return i, err
}

const listChatMessagesByCompany = `-- name: ListChatMessagesByCompany :many
SELECT id, company_id, user_id, role, content, tool_calls, created_at, thread_id, agent_id, message_type, citations_json, action_results_json FROM chat_messages
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListChatMessagesByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListChatMessagesByCompany(ctx context.Context, arg ListChatMessagesByCompanyParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesByCompany, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.CreatedAt,
			&i.ThreadID,
			&i.AgentID,
			&i.MessageType,
			&i.CitationsJson,
			&i.ActionResultsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
