// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cleaning_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCleaningTemplateByHash = `-- name: GetCleaningTemplateByHash :one
SELECT id, company_id, signature_hash, header_signature, ai_result, hit_count, created_at, updated_at
FROM cleaning_templates
WHERE company_id = $1 AND signature_hash = $2
`

type GetCleaningTemplateByHashParams struct {
	CompanyID     uuid.UUID `json:"company_id"`
	SignatureHash string    `json:"signature_hash"`
}

func (q *Queries) GetCleaningTemplateByHash(ctx context.Context, arg GetCleaningTemplateByHashParams) (CleaningTemplate, error) {
	row := q.db.QueryRow(ctx, getCleaningTemplateByHash, arg.CompanyID, arg.SignatureHash)
	var i CleaningTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SignatureHash,
		&i.HeaderSignature,
		&i.AiResult,
		&i.HitCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCleaningTemplateHitCount = `-- name: IncrementCleaningTemplateHitCount :exec
UPDATE cleaning_templates
SET hit_count = hit_count + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementCleaningTemplateHitCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementCleaningTemplateHitCount, id)
	return err
}

const listCleaningTemplatesByCompany = `-- name: ListCleaningTemplatesByCompany :many
SELECT id, company_id, signature_hash, header_signature, ai_result, hit_count, created_at, updated_at
FROM cleaning_templates
WHERE company_id = $1
ORDER BY hit_count DESC, updated_at DESC
LIMIT $2
`

type ListCleaningTemplatesByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListCleaningTemplatesByCompany(ctx context.Context, arg ListCleaningTemplatesByCompanyParams) ([]CleaningTemplate, error) {
	rows, err := q.db.Query(ctx, listCleaningTemplatesByCompany, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CleaningTemplate{}
	for rows.Next() {
		var i CleaningTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SignatureHash,
			&i.HeaderSignature,
			&i.AiResult,
			&i.HitCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCleaningTemplate = `-- name: UpsertCleaningTemplate :one
INSERT INTO cleaning_templates (company_id, signature_hash, header_signature, ai_result)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, signature_hash)
DO UPDATE SET
    ai_result = EXCLUDED.ai_result,
    hit_count = cleaning_templates.hit_count + 1,
    updated_at = NOW()
RETURNING id, company_id, signature_hash, header_signature, ai_result, hit_count, created_at, updated_at
`

type UpsertCleaningTemplateParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	SignatureHash   string    `json:"signature_hash"`
	HeaderSignature []byte    `json:"header_signature"`
	AiResult        []byte    `json:"ai_result"`
}

func (q *Queries) UpsertCleaningTemplate(ctx context.Context, arg UpsertCleaningTemplateParams) (CleaningTemplate, error) {
	row := q.db.QueryRow(ctx, upsertCleaningTemplate,
		arg.CompanyID,
		arg.SignatureHash,
		arg.HeaderSignature,
		arg.AiResult,
	)
	var i CleaningTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SignatureHash,
		&i.HeaderSignature,
		&i.AiResult,
		&i.HitCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
