// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCompanyMember = `-- name: AddCompanyMember :exec
INSERT INTO company_members (company_id, user_id, role, joined_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (company_id, user_id) DO NOTHING
`

type AddCompanyMemberParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddCompanyMember(ctx context.Context, arg AddCompanyMemberParams) error {
	_, err := q.db.Exec(ctx, addCompanyMember, arg.CompanyID, arg.UserID, arg.Role)
	return err
}

const countCompaniesByOrg = `-- name: CountCompaniesByOrg :one
SELECT COUNT(*) FROM companies WHERE organization_id = $1 AND is_active = true
`

func (q *Queries) CountCompaniesByOrg(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompaniesByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompaniesByUser = `-- name: CountCompaniesByUser :one
SELECT COUNT(DISTINCT c.id) FROM companies c
LEFT JOIN company_members cm ON c.id = cm.company_id
LEFT JOIN org_members om ON c.organization_id = om.organization_id
WHERE (cm.user_id = $1 OR om.user_id = $1) AND c.is_active = true
`

func (q *Queries) CountCompaniesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompaniesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, organization_id, company_name, tin_number, rdo_code, vat_classification, fiscal_year_end, industry, address, plan, settings, is_active, jurisdiction, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW(), NOW())
RETURNING id, organization_id, company_name, tin_number, rdo_code, vat_classification, fiscal_year_end, industry, address, plan, settings, is_active, created_at, updated_at, jurisdiction, base_currency
`

type CreateCompanyParams struct {
	ID                uuid.UUID   `json:"id"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
	CompanyName       string      `json:"company_name"`
	TinNumber         *string     `json:"tin_number"`
	RdoCode           *string     `json:"rdo_code"`
	VatClassification string      `json:"vat_classification"`
	FiscalYearEnd     string      `json:"fiscal_year_end"`
	Industry          *string     `json:"industry"`
	Address           *string     `json:"address"`
	Plan              string      `json:"plan"`
	Settings          []byte      `json:"settings"`
	IsActive          bool        `json:"is_active"`
	Jurisdiction      string      `json:"jurisdiction"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.OrganizationID,
		arg.CompanyName,
		arg.TinNumber,
		arg.RdoCode,
		arg.VatClassification,
		arg.FiscalYearEnd,
		arg.Industry,
		arg.Address,
		arg.Plan,
		arg.Settings,
		arg.IsActive,
		arg.Jurisdiction,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CompanyName,
		&i.TinNumber,
		&i.RdoCode,
		&i.VatClassification,
		&i.FiscalYearEnd,
		&i.Industry,
		&i.Address,
		&i.Plan,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Jurisdiction,
		&i.BaseCurrency,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, organization_id, company_name, tin_number, rdo_code, vat_classification, fiscal_year_end, industry, address, plan, settings, is_active, created_at, updated_at, jurisdiction, base_currency FROM companies WHERE id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CompanyName,
		&i.TinNumber,
		&i.RdoCode,
		&i.VatClassification,
		&i.FiscalYearEnd,
		&i.Industry,
		&i.Address,
		&i.Plan,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Jurisdiction,
		&i.BaseCurrency,
	)
	return i, err
}

const getCompanyMemberRole = `-- name: GetCompanyMemberRole :one
SELECT role FROM company_members WHERE company_id = $1 AND user_id = $2
`

type GetCompanyMemberRoleParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCompanyMemberRole(ctx context.Context, arg GetCompanyMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getCompanyMemberRole, arg.CompanyID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getEffectiveRole = `-- name: GetEffectiveRole :one
SELECT COALESCE(
    (SELECT cm.role FROM company_members cm WHERE cm.company_id = $2 AND cm.user_id = $1),
    CASE
        WHEN EXISTS (
            SELECT 1 FROM org_members om
            JOIN companies c ON c.organization_id = om.organization_id
            WHERE c.id = $2 AND om.user_id = $1 AND om.role IN ('org_owner', 'org_admin')
        ) THEN 'company_admin'
        WHEN EXISTS (
            SELECT 1 FROM org_members om
            JOIN companies c ON c.organization_id = om.organization_id
            WHERE c.id = $2 AND om.user_id = $1 AND om.role = 'org_member'
        ) THEN 'viewer'
        ELSE NULL
    END
) AS effective_role
`

type GetEffectiveRoleParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetEffectiveRole(ctx context.Context, arg GetEffectiveRoleParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getEffectiveRole, arg.UserID, arg.CompanyID)
	var effective_role interface{}
	err := row.Scan(&effective_role)
	return effective_role, err
}

const listAllCompanies = `-- name: ListAllCompanies :many
SELECT id, organization_id, company_name, tin_number, rdo_code, vat_classification, fiscal_year_end, industry, address, plan, settings, is_active, created_at, updated_at, jurisdiction, base_currency FROM companies WHERE is_active = true ORDER BY created_at
`

func (q *Queries) ListAllCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listAllCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CompanyName,
			&i.TinNumber,
			&i.RdoCode,
			&i.VatClassification,
			&i.FiscalYearEnd,
			&i.Industry,
			&i.Address,
			&i.Plan,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Jurisdiction,
			&i.BaseCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesByOrg = `-- name: ListCompaniesByOrg :many
SELECT id, organization_id, company_name, tin_number, rdo_code, vat_classification, fiscal_year_end, industry, address, plan, settings, is_active, created_at, updated_at, jurisdiction, base_currency FROM companies
WHERE organization_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCompaniesByOrgParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListCompaniesByOrg(ctx context.Context, arg ListCompaniesByOrgParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CompanyName,
			&i.TinNumber,
			&i.RdoCode,
			&i.VatClassification,
			&i.FiscalYearEnd,
			&i.Industry,
			&i.Address,
			&i.Plan,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Jurisdiction,
			&i.BaseCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesByUser = `-- name: ListCompaniesByUser :many
SELECT DISTINCT c.id, c.organization_id, c.company_name, c.tin_number, c.rdo_code, c.vat_classification, c.fiscal_year_end, c.industry, c.address, c.plan, c.settings, c.is_active, c.created_at, c.updated_at, c.jurisdiction, c.base_currency FROM companies c
LEFT JOIN company_members cm ON c.id = cm.company_id
LEFT JOIN org_members om ON c.organization_id = om.organization_id
WHERE (cm.user_id = $1 OR om.user_id = $1)
AND c.is_active = true
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListCompaniesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListCompaniesByUser(ctx context.Context, arg ListCompaniesByUserParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompaniesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CompanyName,
			&i.TinNumber,
			&i.RdoCode,
			&i.VatClassification,
			&i.FiscalYearEnd,
			&i.Industry,
			&i.Address,
			&i.Plan,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Jurisdiction,
			&i.BaseCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyMembers = `-- name: ListCompanyMembers :many
SELECT cm.company_id, cm.user_id, cm.role, cm.joined_at, u.email, u.full_name,
       u.telegram_username,
       CASE WHEN tu.telegram_id IS NOT NULL THEN true ELSE false END AS telegram_linked
FROM company_members cm
JOIN users u ON cm.user_id = u.id
LEFT JOIN telegram_users tu ON tu.user_id = cm.user_id AND tu.company_id = cm.company_id
WHERE cm.company_id = $1
ORDER BY cm.joined_at
`

type ListCompanyMembersRow struct {
	CompanyID        uuid.UUID `json:"company_id"`
	UserID           uuid.UUID `json:"user_id"`
	Role             string    `json:"role"`
	JoinedAt         time.Time `json:"joined_at"`
	Email            string    `json:"email"`
	FullName         *string   `json:"full_name"`
	TelegramUsername *string   `json:"telegram_username"`
	TelegramLinked   bool      `json:"telegram_linked"`
}

func (q *Queries) ListCompanyMembers(ctx context.Context, companyID uuid.UUID) ([]ListCompanyMembersRow, error) {
	rows, err := q.db.Query(ctx, listCompanyMembers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompanyMembersRow{}
	for rows.Next() {
		var i ListCompanyMembersRow
		if err := rows.Scan(
			&i.CompanyID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
			&i.TelegramUsername,
			&i.TelegramLinked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCompanyMember = `-- name: RemoveCompanyMember :exec
DELETE FROM company_members WHERE company_id = $1 AND user_id = $2
`

type RemoveCompanyMemberParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveCompanyMember(ctx context.Context, arg RemoveCompanyMemberParams) error {
	_, err := q.db.Exec(ctx, removeCompanyMember, arg.CompanyID, arg.UserID)
	return err
}

const updateCompany = `-- name: UpdateCompany :exec
UPDATE companies SET
    company_name = $2,
    tin_number = $3,
    rdo_code = $4,
    vat_classification = $5,
    fiscal_year_end = $6,
    industry = $7,
    address = $8,
    plan = $9,
    settings = $10,
    is_active = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCompanyParams struct {
	ID                uuid.UUID `json:"id"`
	CompanyName       string    `json:"company_name"`
	TinNumber         *string   `json:"tin_number"`
	RdoCode           *string   `json:"rdo_code"`
	VatClassification string    `json:"vat_classification"`
	FiscalYearEnd     string    `json:"fiscal_year_end"`
	Industry          *string   `json:"industry"`
	Address           *string   `json:"address"`
	Plan              string    `json:"plan"`
	Settings          []byte    `json:"settings"`
	IsActive          bool      `json:"is_active"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) error {
	_, err := q.db.Exec(ctx, updateCompany,
		arg.ID,
		arg.CompanyName,
		arg.TinNumber,
		arg.RdoCode,
		arg.VatClassification,
		arg.FiscalYearEnd,
		arg.Industry,
		arg.Address,
		arg.Plan,
		arg.Settings,
		arg.IsActive,
	)
	return err
}

const updateCompanyMemberRole = `-- name: UpdateCompanyMemberRole :exec
UPDATE company_members SET role = $3 WHERE company_id = $1 AND user_id = $2
`

type UpdateCompanyMemberRoleParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) UpdateCompanyMemberRole(ctx context.Context, arg UpdateCompanyMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateCompanyMemberRole, arg.CompanyID, arg.UserID, arg.Role)
	return err
}
