// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corrections.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCorrectionsByCompany = `-- name: CountCorrectionsByCompany :one
SELECT COUNT(*) FROM corrections WHERE company_id = $1
`

func (q *Queries) CountCorrectionsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCorrectionsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCorrection = `-- name: CreateCorrection :one
INSERT INTO corrections (id, company_id, user_id, entity_type, entity_id, field_name, old_value, new_value, reason, context_data, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
RETURNING id, company_id, user_id, entity_type, entity_id, field_name, old_value, new_value, reason, context_data, created_at
`

type CreateCorrectionParams struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	UserID      uuid.UUID `json:"user_id"`
	EntityType  string    `json:"entity_type"`
	EntityID    uuid.UUID `json:"entity_id"`
	FieldName   string    `json:"field_name"`
	OldValue    *string   `json:"old_value"`
	NewValue    string    `json:"new_value"`
	Reason      *string   `json:"reason"`
	ContextData []byte    `json:"context_data"`
}

func (q *Queries) CreateCorrection(ctx context.Context, arg CreateCorrectionParams) (Correction, error) {
	row := q.db.QueryRow(ctx, createCorrection,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
		arg.ContextData,
	)
	var i Correction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.Reason,
		&i.ContextData,
		&i.CreatedAt,
	)
	return i, err
}

const createCorrectionRule = `-- name: CreateCorrectionRule :one
INSERT INTO correction_rules (id, company_id, rule_type, match_criteria, correction_field, correction_value, confidence, source_correction_count, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, company_id, rule_type, match_criteria, correction_field, correction_value, confidence, source_correction_count, is_active, created_at, updated_at
`

type CreateCorrectionRuleParams struct {
	ID                    uuid.UUID      `json:"id"`
	CompanyID             uuid.UUID      `json:"company_id"`
	RuleType              string         `json:"rule_type"`
	MatchCriteria         []byte         `json:"match_criteria"`
	CorrectionField       string         `json:"correction_field"`
	CorrectionValue       string         `json:"correction_value"`
	Confidence            pgtype.Numeric `json:"confidence"`
	SourceCorrectionCount int32          `json:"source_correction_count"`
	IsActive              bool           `json:"is_active"`
}

func (q *Queries) CreateCorrectionRule(ctx context.Context, arg CreateCorrectionRuleParams) (CorrectionRule, error) {
	row := q.db.QueryRow(ctx, createCorrectionRule,
		arg.ID,
		arg.CompanyID,
		arg.RuleType,
		arg.MatchCriteria,
		arg.CorrectionField,
		arg.CorrectionValue,
		arg.Confidence,
		arg.SourceCorrectionCount,
		arg.IsActive,
	)
	var i CorrectionRule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.RuleType,
		&i.MatchCriteria,
		&i.CorrectionField,
		&i.CorrectionValue,
		&i.Confidence,
		&i.SourceCorrectionCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createValidationResult = `-- name: CreateValidationResult :one
INSERT INTO validation_results (id, report_id, company_id, overall_score, check_results, rag_findings, validated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, report_id, company_id, overall_score, check_results, rag_findings, validated_at
`

type CreateValidationResultParams struct {
	ID           uuid.UUID `json:"id"`
	ReportID     uuid.UUID `json:"report_id"`
	CompanyID    uuid.UUID `json:"company_id"`
	OverallScore int32     `json:"overall_score"`
	CheckResults []byte    `json:"check_results"`
	RagFindings  []byte    `json:"rag_findings"`
}

func (q *Queries) CreateValidationResult(ctx context.Context, arg CreateValidationResultParams) (ValidationResult, error) {
	row := q.db.QueryRow(ctx, createValidationResult,
		arg.ID,
		arg.ReportID,
		arg.CompanyID,
		arg.OverallScore,
		arg.CheckResults,
		arg.RagFindings,
	)
	var i ValidationResult
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.CompanyID,
		&i.OverallScore,
		&i.CheckResults,
		&i.RagFindings,
		&i.ValidatedAt,
	)
	return i, err
}

const findMatchingCorrectionRules = `-- name: FindMatchingCorrectionRules :many
SELECT id, company_id, rule_type, match_criteria, correction_field, correction_value, confidence, source_correction_count, is_active, created_at, updated_at FROM correction_rules
WHERE company_id = $1 AND rule_type = $2 AND correction_field = $3 AND is_active = true
ORDER BY confidence DESC
`

type FindMatchingCorrectionRulesParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	RuleType        string    `json:"rule_type"`
	CorrectionField string    `json:"correction_field"`
}

func (q *Queries) FindMatchingCorrectionRules(ctx context.Context, arg FindMatchingCorrectionRulesParams) ([]CorrectionRule, error) {
	rows, err := q.db.Query(ctx, findMatchingCorrectionRules, arg.CompanyID, arg.RuleType, arg.CorrectionField)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionRule{}
	for rows.Next() {
		var i CorrectionRule
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.RuleType,
			&i.MatchCriteria,
			&i.CorrectionField,
			&i.CorrectionValue,
			&i.Confidence,
			&i.SourceCorrectionCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestValidationByReport = `-- name: GetLatestValidationByReport :one
SELECT id, report_id, company_id, overall_score, check_results, rag_findings, validated_at FROM validation_results WHERE report_id = $1
ORDER BY validated_at DESC LIMIT 1
`

func (q *Queries) GetLatestValidationByReport(ctx context.Context, reportID uuid.UUID) (ValidationResult, error) {
	row := q.db.QueryRow(ctx, getLatestValidationByReport, reportID)
	var i ValidationResult
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.CompanyID,
		&i.OverallScore,
		&i.CheckResults,
		&i.RagFindings,
		&i.ValidatedAt,
	)
	return i, err
}

const listActiveCorrectionRulesByCompany = `-- name: ListActiveCorrectionRulesByCompany :many
SELECT id, company_id, rule_type, match_criteria, correction_field, correction_value, confidence, source_correction_count, is_active, created_at, updated_at FROM correction_rules
WHERE company_id = $1 AND is_active = true
ORDER BY confidence DESC
`

func (q *Queries) ListActiveCorrectionRulesByCompany(ctx context.Context, companyID uuid.UUID) ([]CorrectionRule, error) {
	rows, err := q.db.Query(ctx, listActiveCorrectionRulesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CorrectionRule{}
	for rows.Next() {
		var i CorrectionRule
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.RuleType,
			&i.MatchCriteria,
			&i.CorrectionField,
			&i.CorrectionValue,
			&i.Confidence,
			&i.SourceCorrectionCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorrectionsByCompany = `-- name: ListCorrectionsByCompany :many
SELECT id, company_id, user_id, entity_type, entity_id, field_name, old_value, new_value, reason, context_data, created_at FROM corrections WHERE company_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListCorrectionsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListCorrectionsByCompany(ctx context.Context, arg ListCorrectionsByCompanyParams) ([]Correction, error) {
	rows, err := q.db.Query(ctx, listCorrectionsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Correction{}
	for rows.Next() {
		var i Correction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.ContextData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorrectionsByEntity = `-- name: ListCorrectionsByEntity :many
SELECT id, company_id, user_id, entity_type, entity_id, field_name, old_value, new_value, reason, context_data, created_at FROM corrections WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListCorrectionsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListCorrectionsByEntity(ctx context.Context, arg ListCorrectionsByEntityParams) ([]Correction, error) {
	rows, err := q.db.Query(ctx, listCorrectionsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Correction{}
	for rows.Next() {
		var i Correction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.ContextData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValidationsByReport = `-- name: ListValidationsByReport :many
SELECT id, report_id, company_id, overall_score, check_results, rag_findings, validated_at FROM validation_results WHERE report_id = $1
ORDER BY validated_at DESC
`

func (q *Queries) ListValidationsByReport(ctx context.Context, reportID uuid.UUID) ([]ValidationResult, error) {
	rows, err := q.db.Query(ctx, listValidationsByReport, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ValidationResult{}
	for rows.Next() {
		var i ValidationResult
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.CompanyID,
			&i.OverallScore,
			&i.CheckResults,
			&i.RagFindings,
			&i.ValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorrectionRule = `-- name: UpdateCorrectionRule :exec
UPDATE correction_rules SET
    match_criteria = COALESCE($2, match_criteria),
    correction_value = COALESCE($3, correction_value),
    confidence = COALESCE($4, confidence),
    source_correction_count = COALESCE($5, source_correction_count),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $1
`

type UpdateCorrectionRuleParams struct {
	ID                    uuid.UUID      `json:"id"`
	MatchCriteria         []byte         `json:"match_criteria"`
	CorrectionValue       string         `json:"correction_value"`
	Confidence            pgtype.Numeric `json:"confidence"`
	SourceCorrectionCount int32          `json:"source_correction_count"`
	IsActive              bool           `json:"is_active"`
}

func (q *Queries) UpdateCorrectionRule(ctx context.Context, arg UpdateCorrectionRuleParams) error {
	_, err := q.db.Exec(ctx, updateCorrectionRule,
		arg.ID,
		arg.MatchCriteria,
		arg.CorrectionValue,
		arg.Confidence,
		arg.SourceCorrectionCount,
		arg.IsActive,
	)
	return err
}
