// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireExpenseReportNumberLock = `-- name: AcquireExpenseReportNumberLock :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || 'expense_report_number'))
`

func (q *Queries) AcquireExpenseReportNumberLock(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, acquireExpenseReportNumberLock, dollar_1)
	return err
}

const countExpenseItemsByReport = `-- name: CountExpenseItemsByReport :one
SELECT COUNT(*) FROM expense_items WHERE expense_report_id = $1
`

func (q *Queries) CountExpenseItemsByReport(ctx context.Context, expenseReportID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseItemsByReport, expenseReportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpenseReportsByStatus = `-- name: CountExpenseReportsByStatus :one
SELECT COUNT(*) FROM expense_reports
WHERE company_id = $1 AND status = $2
`

type CountExpenseReportsByStatusParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
}

func (q *Queries) CountExpenseReportsByStatus(ctx context.Context, arg CountExpenseReportsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseReportsByStatus, arg.CompanyID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpenseReportsBySubmitter = `-- name: CountExpenseReportsBySubmitter :one
SELECT COUNT(*) FROM expense_reports
WHERE company_id = $1 AND submitter_user_id = $2
    AND ($3::text = '' OR status = $3)
`

type CountExpenseReportsBySubmitterParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	SubmitterUserID uuid.UUID `json:"submitter_user_id"`
	Column3         string    `json:"column_3"`
}

func (q *Queries) CountExpenseReportsBySubmitter(ctx context.Context, arg CountExpenseReportsBySubmitterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseReportsBySubmitter, arg.CompanyID, arg.SubmitterUserID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingApprovalsForUser = `-- name: CountPendingApprovalsForUser :one
SELECT COUNT(*)
FROM expense_reports er
JOIN hr_payees hp ON hp.id = er.hr_payee_id
WHERE er.company_id = $1
    AND er.status = 'pending_approval'
    AND er.submitter_user_id != $2
    AND hp.department_name IN (
        SELECT ea.department_name FROM expense_approvers ea
        WHERE ea.company_id = $1 AND ea.approver_user_id = $2 AND ea.is_active = true
    )
`

type CountPendingApprovalsForUserParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	SubmitterUserID uuid.UUID `json:"submitter_user_id"`
}

func (q *Queries) CountPendingApprovalsForUser(ctx context.Context, arg CountPendingApprovalsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApprovalsForUser, arg.CompanyID, arg.SubmitterUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpenseApprover = `-- name: CreateExpenseApprover :one

INSERT INTO expense_approvers (
    id, company_id, department_name, approver_user_id, max_amount, priority, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, department_name, approver_user_id, max_amount, priority, is_active, created_at, updated_at
`

type CreateExpenseApproverParams struct {
	ID             uuid.UUID      `json:"id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	DepartmentName string         `json:"department_name"`
	ApproverUserID uuid.UUID      `json:"approver_user_id"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
	Priority       int32          `json:"priority"`
	IsActive       bool           `json:"is_active"`
}

// ===================== EXPENSE APPROVERS =====================
func (q *Queries) CreateExpenseApprover(ctx context.Context, arg CreateExpenseApproverParams) (ExpenseApprover, error) {
	row := q.db.QueryRow(ctx, createExpenseApprover,
		arg.ID,
		arg.CompanyID,
		arg.DepartmentName,
		arg.ApproverUserID,
		arg.MaxAmount,
		arg.Priority,
		arg.IsActive,
	)
	var i ExpenseApprover
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentName,
		&i.ApproverUserID,
		&i.MaxAmount,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpenseAuditLog = `-- name: CreateExpenseAuditLog :one

INSERT INTO expense_audit_log (
    id, expense_report_id, action, actor_user_id, actor_type, details
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, expense_report_id, action, actor_user_id, actor_type, details, created_at
`

type CreateExpenseAuditLogParams struct {
	ID              uuid.UUID   `json:"id"`
	ExpenseReportID pgtype.UUID `json:"expense_report_id"`
	Action          string      `json:"action"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	ActorType       string      `json:"actor_type"`
	Details         []byte      `json:"details"`
}

// ===================== EXPENSE AUDIT LOG =====================
func (q *Queries) CreateExpenseAuditLog(ctx context.Context, arg CreateExpenseAuditLogParams) (ExpenseAuditLog, error) {
	row := q.db.QueryRow(ctx, createExpenseAuditLog,
		arg.ID,
		arg.ExpenseReportID,
		arg.Action,
		arg.ActorUserID,
		arg.ActorType,
		arg.Details,
	)
	var i ExpenseAuditLog
	err := row.Scan(
		&i.ID,
		&i.ExpenseReportID,
		&i.Action,
		&i.ActorUserID,
		&i.ActorType,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const createExpenseItem = `-- name: CreateExpenseItem :one

INSERT INTO expense_items (
    id, expense_report_id, category, description, amount, currency,
    merchant_name, transaction_date, receipt_url, receipt_ocr_data,
    ai_category_confidence, gl_account_id, policy_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, expense_report_id, category, description, amount, currency, merchant_name, transaction_date, receipt_url, receipt_ocr_data, ai_category_confidence, gl_account_id, policy_id, created_at, updated_at
`

type CreateExpenseItemParams struct {
	ID                   uuid.UUID      `json:"id"`
	ExpenseReportID      uuid.UUID      `json:"expense_report_id"`
	Category             string         `json:"category"`
	Description          string         `json:"description"`
	Amount               pgtype.Numeric `json:"amount"`
	Currency             string         `json:"currency"`
	MerchantName         *string        `json:"merchant_name"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	ReceiptUrl           *string        `json:"receipt_url"`
	ReceiptOcrData       []byte         `json:"receipt_ocr_data"`
	AiCategoryConfidence pgtype.Numeric `json:"ai_category_confidence"`
	GlAccountID          pgtype.UUID    `json:"gl_account_id"`
	PolicyID             pgtype.UUID    `json:"policy_id"`
}

// ===================== EXPENSE ITEMS =====================
func (q *Queries) CreateExpenseItem(ctx context.Context, arg CreateExpenseItemParams) (ExpenseItem, error) {
	row := q.db.QueryRow(ctx, createExpenseItem,
		arg.ID,
		arg.ExpenseReportID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.MerchantName,
		arg.TransactionDate,
		arg.ReceiptUrl,
		arg.ReceiptOcrData,
		arg.AiCategoryConfidence,
		arg.GlAccountID,
		arg.PolicyID,
	)
	var i ExpenseItem
	err := row.Scan(
		&i.ID,
		&i.ExpenseReportID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.MerchantName,
		&i.TransactionDate,
		&i.ReceiptUrl,
		&i.ReceiptOcrData,
		&i.AiCategoryConfidence,
		&i.GlAccountID,
		&i.PolicyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpensePolicy = `-- name: CreateExpensePolicy :one


INSERT INTO expense_policies (
    id, company_id, name, category, max_amount, requires_receipt_above,
    auto_approve_below, ai_auto_approve, description, is_active
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, name, category, max_amount, requires_receipt_above, auto_approve_below, ai_auto_approve, description, is_active, created_at, updated_at
`

type CreateExpensePolicyParams struct {
	ID                   uuid.UUID      `json:"id"`
	CompanyID            uuid.UUID      `json:"company_id"`
	Name                 string         `json:"name"`
	Category             string         `json:"category"`
	MaxAmount            pgtype.Numeric `json:"max_amount"`
	RequiresReceiptAbove pgtype.Numeric `json:"requires_receipt_above"`
	AutoApproveBelow     pgtype.Numeric `json:"auto_approve_below"`
	AiAutoApprove        bool           `json:"ai_auto_approve"`
	Description          *string        `json:"description"`
	IsActive             bool           `json:"is_active"`
}

// queries/expenses.sql
// ===================== EXPENSE POLICIES =====================
func (q *Queries) CreateExpensePolicy(ctx context.Context, arg CreateExpensePolicyParams) (ExpensePolicy, error) {
	row := q.db.QueryRow(ctx, createExpensePolicy,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Category,
		arg.MaxAmount,
		arg.RequiresReceiptAbove,
		arg.AutoApproveBelow,
		arg.AiAutoApprove,
		arg.Description,
		arg.IsActive,
	)
	var i ExpensePolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Category,
		&i.MaxAmount,
		&i.RequiresReceiptAbove,
		&i.AutoApproveBelow,
		&i.AiAutoApprove,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpenseReport = `-- name: CreateExpenseReport :one

INSERT INTO expense_reports (
    id, company_id, submitter_user_id, hr_payee_id, report_number,
    title, status, total_amount, currency, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, submitter_user_id, hr_payee_id, report_number, title, status, total_amount, currency, submitted_at, ai_reviewed_at, ai_risk_score, ai_decision, ai_decision_reason, approver_user_id, approved_at, rejection_reason, reviewer_user_id, paid_at, payment_reference, accrual_journal_entry_id, payment_journal_entry_id, notes, created_at, updated_at
`

type CreateExpenseReportParams struct {
	ID              uuid.UUID      `json:"id"`
	CompanyID       uuid.UUID      `json:"company_id"`
	SubmitterUserID uuid.UUID      `json:"submitter_user_id"`
	HrPayeeID       pgtype.UUID    `json:"hr_payee_id"`
	ReportNumber    string         `json:"report_number"`
	Title           string         `json:"title"`
	Status          string         `json:"status"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	Currency        string         `json:"currency"`
	Notes           *string        `json:"notes"`
}

// ===================== EXPENSE REPORTS =====================
func (q *Queries) CreateExpenseReport(ctx context.Context, arg CreateExpenseReportParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, createExpenseReport,
		arg.ID,
		arg.CompanyID,
		arg.SubmitterUserID,
		arg.HrPayeeID,
		arg.ReportNumber,
		arg.Title,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.Notes,
	)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubmitterUserID,
		&i.HrPayeeID,
		&i.ReportNumber,
		&i.Title,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.SubmittedAt,
		&i.AiReviewedAt,
		&i.AiRiskScore,
		&i.AiDecision,
		&i.AiDecisionReason,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.ReviewerUserID,
		&i.PaidAt,
		&i.PaymentReference,
		&i.AccrualJournalEntryID,
		&i.PaymentJournalEntryID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateExpenseApprover = `-- name: DeactivateExpenseApprover :exec
UPDATE expense_approvers SET is_active = false, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type DeactivateExpenseApproverParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeactivateExpenseApprover(ctx context.Context, arg DeactivateExpenseApproverParams) error {
	_, err := q.db.Exec(ctx, deactivateExpenseApprover, arg.ID, arg.CompanyID)
	return err
}

const deactivateExpensePolicy = `-- name: DeactivateExpensePolicy :exec
UPDATE expense_policies SET is_active = false, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type DeactivateExpensePolicyParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeactivateExpensePolicy(ctx context.Context, arg DeactivateExpensePolicyParams) error {
	_, err := q.db.Exec(ctx, deactivateExpensePolicy, arg.ID, arg.CompanyID)
	return err
}

const deleteExpenseItem = `-- name: DeleteExpenseItem :exec
DELETE FROM expense_items WHERE id = $1
`

func (q *Queries) DeleteExpenseItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseItem, id)
	return err
}

const deleteExpenseReportDraft = `-- name: DeleteExpenseReportDraft :exec
DELETE FROM expense_reports WHERE id = $1 AND company_id = $2 AND status = 'draft'
`

type DeleteExpenseReportDraftParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteExpenseReportDraft(ctx context.Context, arg DeleteExpenseReportDraftParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseReportDraft, arg.ID, arg.CompanyID)
	return err
}

const findAdminApprovers = `-- name: FindAdminApprovers :many
SELECT cm.user_id AS approver_user_id,
    COALESCE(u.full_name, u.email) AS approver_name
FROM company_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.company_id = $1
    AND cm.role = 'company_admin'
    AND cm.user_id != $2
`

type FindAdminApproversParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type FindAdminApproversRow struct {
	ApproverUserID uuid.UUID `json:"approver_user_id"`
	ApproverName   string    `json:"approver_name"`
}

// Fallback: find company_admins who are not the submitter
func (q *Queries) FindAdminApprovers(ctx context.Context, arg FindAdminApproversParams) ([]FindAdminApproversRow, error) {
	rows, err := q.db.Query(ctx, findAdminApprovers, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAdminApproversRow{}
	for rows.Next() {
		var i FindAdminApproversRow
		if err := rows.Scan(&i.ApproverUserID, &i.ApproverName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDuplicateExpenseItems = `-- name: FindDuplicateExpenseItems :many
SELECT ei.id, ei.amount, ei.merchant_name, ei.transaction_date, er.report_number
FROM expense_items ei
JOIN expense_reports er ON er.id = ei.expense_report_id
WHERE er.company_id = $1
    AND er.submitter_user_id = $2
    AND ei.expense_report_id != $3
    AND ei.amount = $4
    AND ei.merchant_name = $5
    AND ei.transaction_date BETWEEN $6::date - INTERVAL '7 days' AND $6::date + INTERVAL '7 days'
    AND er.status NOT IN ('draft', 'rejected')
`

type FindDuplicateExpenseItemsParams struct {
	CompanyID       uuid.UUID      `json:"company_id"`
	SubmitterUserID uuid.UUID      `json:"submitter_user_id"`
	ExpenseReportID uuid.UUID      `json:"expense_report_id"`
	Amount          pgtype.Numeric `json:"amount"`
	MerchantName    *string        `json:"merchant_name"`
	Column6         pgtype.Date    `json:"column_6"`
}

type FindDuplicateExpenseItemsRow struct {
	ID              uuid.UUID      `json:"id"`
	Amount          pgtype.Numeric `json:"amount"`
	MerchantName    *string        `json:"merchant_name"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	ReportNumber    string         `json:"report_number"`
}

// Duplicate detection: same amount + merchant within 7 days
func (q *Queries) FindDuplicateExpenseItems(ctx context.Context, arg FindDuplicateExpenseItemsParams) ([]FindDuplicateExpenseItemsRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateExpenseItems,
		arg.CompanyID,
		arg.SubmitterUserID,
		arg.ExpenseReportID,
		arg.Amount,
		arg.MerchantName,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindDuplicateExpenseItemsRow{}
	for rows.Next() {
		var i FindDuplicateExpenseItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.MerchantName,
			&i.TransactionDate,
			&i.ReportNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findEligibleApprovers = `-- name: FindEligibleApprovers :many
SELECT ea.approver_user_id, ea.max_amount, ea.priority,
    COALESCE(u.full_name, u.email) AS approver_name
FROM expense_approvers ea
JOIN users u ON u.id = ea.approver_user_id
WHERE ea.company_id = $1
    AND ea.department_name = $2
    AND ea.approver_user_id != $3
    AND ea.is_active = true
    AND (ea.max_amount IS NULL OR ea.max_amount >= $4)
ORDER BY ea.priority ASC
`

type FindEligibleApproversParams struct {
	CompanyID      uuid.UUID      `json:"company_id"`
	DepartmentName string         `json:"department_name"`
	ApproverUserID uuid.UUID      `json:"approver_user_id"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
}

type FindEligibleApproversRow struct {
	ApproverUserID uuid.UUID      `json:"approver_user_id"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
	Priority       int32          `json:"priority"`
	ApproverName   string         `json:"approver_name"`
}

// Approver resolution: find eligible approvers for a department, excluding self
func (q *Queries) FindEligibleApprovers(ctx context.Context, arg FindEligibleApproversParams) ([]FindEligibleApproversRow, error) {
	rows, err := q.db.Query(ctx, findEligibleApprovers,
		arg.CompanyID,
		arg.DepartmentName,
		arg.ApproverUserID,
		arg.MaxAmount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEligibleApproversRow{}
	for rows.Next() {
		var i FindEligibleApproversRow
		if err := rows.Scan(
			&i.ApproverUserID,
			&i.MaxAmount,
			&i.Priority,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const generateExpenseReportNumber = `-- name: GenerateExpenseReportNumber :one
SELECT COALESCE(
    MAX(CAST(SUBSTRING(report_number FROM 'EXP-\d{6}-(\d+)') AS INT)), 0
) + 1 AS next_seq
FROM expense_reports
WHERE company_id = $1
    AND report_number LIKE 'EXP-' || to_char(now(), 'YYYYMM') || '-%'
`

// Report number generation (advisory lock)
func (q *Queries) GenerateExpenseReportNumber(ctx context.Context, companyID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, generateExpenseReportNumber, companyID)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const getExpenseApproverByID = `-- name: GetExpenseApproverByID :one
SELECT ea.id, ea.company_id, ea.department_name, ea.approver_user_id, ea.max_amount, ea.priority, ea.is_active, ea.created_at, ea.updated_at, u.email AS approver_email,
    COALESCE(u.full_name, u.email) AS approver_name
FROM expense_approvers ea
JOIN users u ON u.id = ea.approver_user_id
WHERE ea.id = $1 AND ea.company_id = $2
`

type GetExpenseApproverByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

type GetExpenseApproverByIDRow struct {
	ID             uuid.UUID      `json:"id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	DepartmentName string         `json:"department_name"`
	ApproverUserID uuid.UUID      `json:"approver_user_id"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
	Priority       int32          `json:"priority"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ApproverEmail  string         `json:"approver_email"`
	ApproverName   string         `json:"approver_name"`
}

func (q *Queries) GetExpenseApproverByID(ctx context.Context, arg GetExpenseApproverByIDParams) (GetExpenseApproverByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseApproverByID, arg.ID, arg.CompanyID)
	var i GetExpenseApproverByIDRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentName,
		&i.ApproverUserID,
		&i.MaxAmount,
		&i.Priority,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApproverEmail,
		&i.ApproverName,
	)
	return i, err
}

const getExpenseItemByID = `-- name: GetExpenseItemByID :one
SELECT ei.id, ei.expense_report_id, ei.category, ei.description, ei.amount, ei.currency, ei.merchant_name, ei.transaction_date, ei.receipt_url, ei.receipt_ocr_data, ei.ai_category_confidence, ei.gl_account_id, ei.policy_id, ei.created_at, ei.updated_at, er.company_id, er.status AS report_status
FROM expense_items ei
JOIN expense_reports er ON er.id = ei.expense_report_id
WHERE ei.id = $1
`

type GetExpenseItemByIDRow struct {
	ID                   uuid.UUID      `json:"id"`
	ExpenseReportID      uuid.UUID      `json:"expense_report_id"`
	Category             string         `json:"category"`
	Description          string         `json:"description"`
	Amount               pgtype.Numeric `json:"amount"`
	Currency             string         `json:"currency"`
	MerchantName         *string        `json:"merchant_name"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	ReceiptUrl           *string        `json:"receipt_url"`
	ReceiptOcrData       []byte         `json:"receipt_ocr_data"`
	AiCategoryConfidence pgtype.Numeric `json:"ai_category_confidence"`
	GlAccountID          pgtype.UUID    `json:"gl_account_id"`
	PolicyID             pgtype.UUID    `json:"policy_id"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CompanyID            uuid.UUID      `json:"company_id"`
	ReportStatus         string         `json:"report_status"`
}

func (q *Queries) GetExpenseItemByID(ctx context.Context, id uuid.UUID) (GetExpenseItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseItemByID, id)
	var i GetExpenseItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExpenseReportID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.MerchantName,
		&i.TransactionDate,
		&i.ReceiptUrl,
		&i.ReceiptOcrData,
		&i.AiCategoryConfidence,
		&i.GlAccountID,
		&i.PolicyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.ReportStatus,
	)
	return i, err
}

const getExpensePolicyByID = `-- name: GetExpensePolicyByID :one
SELECT id, company_id, name, category, max_amount, requires_receipt_above, auto_approve_below, ai_auto_approve, description, is_active, created_at, updated_at FROM expense_policies WHERE id = $1 AND company_id = $2
`

type GetExpensePolicyByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetExpensePolicyByID(ctx context.Context, arg GetExpensePolicyByIDParams) (ExpensePolicy, error) {
	row := q.db.QueryRow(ctx, getExpensePolicyByID, arg.ID, arg.CompanyID)
	var i ExpensePolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Category,
		&i.MaxAmount,
		&i.RequiresReceiptAbove,
		&i.AutoApproveBelow,
		&i.AiAutoApprove,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseReportByID = `-- name: GetExpenseReportByID :one
SELECT id, company_id, submitter_user_id, hr_payee_id, report_number, title, status, total_amount, currency, submitted_at, ai_reviewed_at, ai_risk_score, ai_decision, ai_decision_reason, approver_user_id, approved_at, rejection_reason, reviewer_user_id, paid_at, payment_reference, accrual_journal_entry_id, payment_journal_entry_id, notes, created_at, updated_at FROM expense_reports WHERE id = $1 AND company_id = $2
`

type GetExpenseReportByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetExpenseReportByID(ctx context.Context, arg GetExpenseReportByIDParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, getExpenseReportByID, arg.ID, arg.CompanyID)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubmitterUserID,
		&i.HrPayeeID,
		&i.ReportNumber,
		&i.Title,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.SubmittedAt,
		&i.AiReviewedAt,
		&i.AiRiskScore,
		&i.AiDecision,
		&i.AiDecisionReason,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.ReviewerUserID,
		&i.PaidAt,
		&i.PaymentReference,
		&i.AccrualJournalEntryID,
		&i.PaymentJournalEntryID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseReportForUpdate = `-- name: GetExpenseReportForUpdate :one
SELECT id, company_id, submitter_user_id, hr_payee_id, report_number, title, status, total_amount, currency, submitted_at, ai_reviewed_at, ai_risk_score, ai_decision, ai_decision_reason, approver_user_id, approved_at, rejection_reason, reviewer_user_id, paid_at, payment_reference, accrual_journal_entry_id, payment_journal_entry_id, notes, created_at, updated_at FROM expense_reports WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type GetExpenseReportForUpdateParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetExpenseReportForUpdate(ctx context.Context, arg GetExpenseReportForUpdateParams) (ExpenseReport, error) {
	row := q.db.QueryRow(ctx, getExpenseReportForUpdate, arg.ID, arg.CompanyID)
	var i ExpenseReport
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SubmitterUserID,
		&i.HrPayeeID,
		&i.ReportNumber,
		&i.Title,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.SubmittedAt,
		&i.AiReviewedAt,
		&i.AiRiskScore,
		&i.AiDecision,
		&i.AiDecisionReason,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.ReviewerUserID,
		&i.PaidAt,
		&i.PaymentReference,
		&i.AccrualJournalEntryID,
		&i.PaymentJournalEntryID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseSpendByCategory = `-- name: GetExpenseSpendByCategory :many

SELECT ei.category, SUM(ei.amount) AS total_amount, COUNT(*) AS item_count
FROM expense_items ei
JOIN expense_reports er ON er.id = ei.expense_report_id
WHERE er.company_id = $1
    AND er.status IN ('approved', 'paid')
    AND er.approved_at >= $2 AND er.approved_at < $3
GROUP BY ei.category
ORDER BY total_amount DESC
`

type GetExpenseSpendByCategoryParams struct {
	CompanyID    uuid.UUID          `json:"company_id"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	ApprovedAt_2 pgtype.Timestamptz `json:"approved_at_2"`
}

type GetExpenseSpendByCategoryRow struct {
	Category    string `json:"category"`
	TotalAmount int64  `json:"total_amount"`
	ItemCount   int64  `json:"item_count"`
}

// ===================== FINANCE ANALYTICS =====================
func (q *Queries) GetExpenseSpendByCategory(ctx context.Context, arg GetExpenseSpendByCategoryParams) ([]GetExpenseSpendByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getExpenseSpendByCategory, arg.CompanyID, arg.ApprovedAt, arg.ApprovedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpenseSpendByCategoryRow{}
	for rows.Next() {
		var i GetExpenseSpendByCategoryRow
		if err := rows.Scan(&i.Category, &i.TotalAmount, &i.ItemCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseSpendByDepartment = `-- name: GetExpenseSpendByDepartment :many
SELECT COALESCE(hp.department_name, 'Unknown') AS department,
    SUM(er.total_amount) AS total_amount, COUNT(*) AS report_count
FROM expense_reports er
LEFT JOIN hr_payees hp ON hp.id = er.hr_payee_id
WHERE er.company_id = $1
    AND er.status IN ('approved', 'paid')
    AND er.approved_at >= $2 AND er.approved_at < $3
GROUP BY department
ORDER BY total_amount DESC
`

type GetExpenseSpendByDepartmentParams struct {
	CompanyID    uuid.UUID          `json:"company_id"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	ApprovedAt_2 pgtype.Timestamptz `json:"approved_at_2"`
}

type GetExpenseSpendByDepartmentRow struct {
	Department  string `json:"department"`
	TotalAmount int64  `json:"total_amount"`
	ReportCount int64  `json:"report_count"`
}

func (q *Queries) GetExpenseSpendByDepartment(ctx context.Context, arg GetExpenseSpendByDepartmentParams) ([]GetExpenseSpendByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, getExpenseSpendByDepartment, arg.CompanyID, arg.ApprovedAt, arg.ApprovedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpenseSpendByDepartmentRow{}
	for rows.Next() {
		var i GetExpenseSpendByDepartmentRow
		if err := rows.Scan(&i.Department, &i.TotalAmount, &i.ReportCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseSpendSummary = `-- name: GetExpenseSpendSummary :one
SELECT
    COUNT(*) FILTER (WHERE status = 'approved') AS approved_count,
    COUNT(*) FILTER (WHERE status = 'paid') AS paid_count,
    COUNT(*) FILTER (WHERE status = 'pending_approval') AS pending_count,
    COALESCE(SUM(total_amount) FILTER (WHERE status IN ('approved', 'paid')), 0) AS total_approved,
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'paid'), 0) AS total_paid,
    COALESCE(SUM(total_amount) FILTER (WHERE status = 'pending_approval'), 0) AS total_pending
FROM expense_reports
WHERE company_id = $1
    AND created_at >= $2 AND created_at < $3
`

type GetExpenseSpendSummaryParams struct {
	CompanyID   uuid.UUID `json:"company_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type GetExpenseSpendSummaryRow struct {
	ApprovedCount int64       `json:"approved_count"`
	PaidCount     int64       `json:"paid_count"`
	PendingCount  int64       `json:"pending_count"`
	TotalApproved interface{} `json:"total_approved"`
	TotalPaid     interface{} `json:"total_paid"`
	TotalPending  interface{} `json:"total_pending"`
}

func (q *Queries) GetExpenseSpendSummary(ctx context.Context, arg GetExpenseSpendSummaryParams) (GetExpenseSpendSummaryRow, error) {
	row := q.db.QueryRow(ctx, getExpenseSpendSummary, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	var i GetExpenseSpendSummaryRow
	err := row.Scan(
		&i.ApprovedCount,
		&i.PaidCount,
		&i.PendingCount,
		&i.TotalApproved,
		&i.TotalPaid,
		&i.TotalPending,
	)
	return i, err
}

const getMerchantCategory = `-- name: GetMerchantCategory :one
SELECT category, COUNT(*) AS frequency
FROM expense_items ei
JOIN expense_reports er ON er.id = ei.expense_report_id
WHERE er.company_id = $1 AND ei.merchant_name = $2
GROUP BY category
ORDER BY frequency DESC
LIMIT 1
`

type GetMerchantCategoryParams struct {
	CompanyID    uuid.UUID `json:"company_id"`
	MerchantName *string   `json:"merchant_name"`
}

type GetMerchantCategoryRow struct {
	Category  string `json:"category"`
	Frequency int64  `json:"frequency"`
}

// Merchant classification cache lookup
func (q *Queries) GetMerchantCategory(ctx context.Context, arg GetMerchantCategoryParams) (GetMerchantCategoryRow, error) {
	row := q.db.QueryRow(ctx, getMerchantCategory, arg.CompanyID, arg.MerchantName)
	var i GetMerchantCategoryRow
	err := row.Scan(&i.Category, &i.Frequency)
	return i, err
}

const listExpenseApprovers = `-- name: ListExpenseApprovers :many
SELECT ea.id, ea.company_id, ea.department_name, ea.approver_user_id, ea.max_amount, ea.priority, ea.is_active, ea.created_at, ea.updated_at, u.email AS approver_email,
    COALESCE(u.full_name, u.email) AS approver_name
FROM expense_approvers ea
JOIN users u ON u.id = ea.approver_user_id
WHERE ea.company_id = $1 AND ea.is_active = true
ORDER BY ea.department_name, ea.priority
`

type ListExpenseApproversRow struct {
	ID             uuid.UUID      `json:"id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	DepartmentName string         `json:"department_name"`
	ApproverUserID uuid.UUID      `json:"approver_user_id"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
	Priority       int32          `json:"priority"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ApproverEmail  string         `json:"approver_email"`
	ApproverName   string         `json:"approver_name"`
}

func (q *Queries) ListExpenseApprovers(ctx context.Context, companyID uuid.UUID) ([]ListExpenseApproversRow, error) {
	rows, err := q.db.Query(ctx, listExpenseApprovers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpenseApproversRow{}
	for rows.Next() {
		var i ListExpenseApproversRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DepartmentName,
			&i.ApproverUserID,
			&i.MaxAmount,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApproverEmail,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseAuditLog = `-- name: ListExpenseAuditLog :many
SELECT eal.id, eal.expense_report_id, eal.action, eal.actor_user_id, eal.actor_type, eal.details, eal.created_at,
    COALESCE(u.full_name, u.email, '') AS actor_name
FROM expense_audit_log eal
LEFT JOIN users u ON u.id = eal.actor_user_id
WHERE eal.expense_report_id = $1
ORDER BY eal.created_at DESC
`

type ListExpenseAuditLogRow struct {
	ID              uuid.UUID   `json:"id"`
	ExpenseReportID pgtype.UUID `json:"expense_report_id"`
	Action          string      `json:"action"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	ActorType       string      `json:"actor_type"`
	Details         []byte      `json:"details"`
	CreatedAt       time.Time   `json:"created_at"`
	ActorName       string      `json:"actor_name"`
}

func (q *Queries) ListExpenseAuditLog(ctx context.Context, expenseReportID pgtype.UUID) ([]ListExpenseAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listExpenseAuditLog, expenseReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpenseAuditLogRow{}
	for rows.Next() {
		var i ListExpenseAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseReportID,
			&i.Action,
			&i.ActorUserID,
			&i.ActorType,
			&i.Details,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseItemsByReport = `-- name: ListExpenseItemsByReport :many
SELECT id, expense_report_id, category, description, amount, currency, merchant_name, transaction_date, receipt_url, receipt_ocr_data, ai_category_confidence, gl_account_id, policy_id, created_at, updated_at FROM expense_items
WHERE expense_report_id = $1
ORDER BY transaction_date, created_at
`

func (q *Queries) ListExpenseItemsByReport(ctx context.Context, expenseReportID uuid.UUID) ([]ExpenseItem, error) {
	rows, err := q.db.Query(ctx, listExpenseItemsByReport, expenseReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseItem{}
	for rows.Next() {
		var i ExpenseItem
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseReportID,
			&i.Category,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.MerchantName,
			&i.TransactionDate,
			&i.ReceiptUrl,
			&i.ReceiptOcrData,
			&i.AiCategoryConfidence,
			&i.GlAccountID,
			&i.PolicyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensePolicies = `-- name: ListExpensePolicies :many
SELECT id, company_id, name, category, max_amount, requires_receipt_above, auto_approve_below, ai_auto_approve, description, is_active, created_at, updated_at FROM expense_policies
WHERE company_id = $1 AND is_active = true
ORDER BY category, name
`

func (q *Queries) ListExpensePolicies(ctx context.Context, companyID uuid.UUID) ([]ExpensePolicy, error) {
	rows, err := q.db.Query(ctx, listExpensePolicies, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpensePolicy{}
	for rows.Next() {
		var i ExpensePolicy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Category,
			&i.MaxAmount,
			&i.RequiresReceiptAbove,
			&i.AutoApproveBelow,
			&i.AiAutoApprove,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensePoliciesByCategory = `-- name: ListExpensePoliciesByCategory :many
SELECT id, company_id, name, category, max_amount, requires_receipt_above, auto_approve_below, ai_auto_approve, description, is_active, created_at, updated_at FROM expense_policies
WHERE company_id = $1 AND category = $2 AND is_active = true
ORDER BY name
`

type ListExpensePoliciesByCategoryParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Category  string    `json:"category"`
}

func (q *Queries) ListExpensePoliciesByCategory(ctx context.Context, arg ListExpensePoliciesByCategoryParams) ([]ExpensePolicy, error) {
	rows, err := q.db.Query(ctx, listExpensePoliciesByCategory, arg.CompanyID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpensePolicy{}
	for rows.Next() {
		var i ExpensePolicy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Category,
			&i.MaxAmount,
			&i.RequiresReceiptAbove,
			&i.AutoApproveBelow,
			&i.AiAutoApprove,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseReportsByStatus = `-- name: ListExpenseReportsByStatus :many
SELECT id, company_id, submitter_user_id, hr_payee_id, report_number, title, status, total_amount, currency, submitted_at, ai_reviewed_at, ai_risk_score, ai_decision, ai_decision_reason, approver_user_id, approved_at, rejection_reason, reviewer_user_id, paid_at, payment_reference, accrual_journal_entry_id, payment_journal_entry_id, notes, created_at, updated_at FROM expense_reports
WHERE company_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListExpenseReportsByStatusParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListExpenseReportsByStatus(ctx context.Context, arg ListExpenseReportsByStatusParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listExpenseReportsByStatus,
		arg.CompanyID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SubmitterUserID,
			&i.HrPayeeID,
			&i.ReportNumber,
			&i.Title,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.SubmittedAt,
			&i.AiReviewedAt,
			&i.AiRiskScore,
			&i.AiDecision,
			&i.AiDecisionReason,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.ReviewerUserID,
			&i.PaidAt,
			&i.PaymentReference,
			&i.AccrualJournalEntryID,
			&i.PaymentJournalEntryID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseReportsBySubmitter = `-- name: ListExpenseReportsBySubmitter :many
SELECT id, company_id, submitter_user_id, hr_payee_id, report_number, title, status, total_amount, currency, submitted_at, ai_reviewed_at, ai_risk_score, ai_decision, ai_decision_reason, approver_user_id, approved_at, rejection_reason, reviewer_user_id, paid_at, payment_reference, accrual_journal_entry_id, payment_journal_entry_id, notes, created_at, updated_at FROM expense_reports
WHERE company_id = $1 AND submitter_user_id = $2
    AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListExpenseReportsBySubmitterParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	SubmitterUserID uuid.UUID `json:"submitter_user_id"`
	Column3         string    `json:"column_3"`
	Limit           int32     `json:"limit"`
	Offset          int32     `json:"offset"`
}

func (q *Queries) ListExpenseReportsBySubmitter(ctx context.Context, arg ListExpenseReportsBySubmitterParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listExpenseReportsBySubmitter,
		arg.CompanyID,
		arg.SubmitterUserID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SubmitterUserID,
			&i.HrPayeeID,
			&i.ReportNumber,
			&i.Title,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.SubmittedAt,
			&i.AiReviewedAt,
			&i.AiRiskScore,
			&i.AiDecision,
			&i.AiDecisionReason,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.ReviewerUserID,
			&i.PaidAt,
			&i.PaymentReference,
			&i.AccrualJournalEntryID,
			&i.PaymentJournalEntryID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsForUser = `-- name: ListPendingApprovalsForUser :many
SELECT er.id, er.company_id, er.submitter_user_id, er.hr_payee_id, er.report_number, er.title, er.status, er.total_amount, er.currency, er.submitted_at, er.ai_reviewed_at, er.ai_risk_score, er.ai_decision, er.ai_decision_reason, er.approver_user_id, er.approved_at, er.rejection_reason, er.reviewer_user_id, er.paid_at, er.payment_reference, er.accrual_journal_entry_id, er.payment_journal_entry_id, er.notes, er.created_at, er.updated_at
FROM expense_reports er
JOIN hr_payees hp ON hp.id = er.hr_payee_id
WHERE er.company_id = $1
    AND er.status = 'pending_approval'
    AND er.submitter_user_id != $2
    AND hp.department_name IN (
        SELECT ea.department_name FROM expense_approvers ea
        WHERE ea.company_id = $1 AND ea.approver_user_id = $2 AND ea.is_active = true
    )
ORDER BY er.created_at ASC
LIMIT $3 OFFSET $4
`

type ListPendingApprovalsForUserParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	SubmitterUserID uuid.UUID `json:"submitter_user_id"`
	Limit           int32     `json:"limit"`
	Offset          int32     `json:"offset"`
}

// Approval queue: list pending reports for departments where user is an approver
func (q *Queries) ListPendingApprovalsForUser(ctx context.Context, arg ListPendingApprovalsForUserParams) ([]ExpenseReport, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalsForUser,
		arg.CompanyID,
		arg.SubmitterUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseReport{}
	for rows.Next() {
		var i ExpenseReport
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SubmitterUserID,
			&i.HrPayeeID,
			&i.ReportNumber,
			&i.Title,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.SubmittedAt,
			&i.AiReviewedAt,
			&i.AiRiskScore,
			&i.AiDecision,
			&i.AiDecisionReason,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.ReviewerUserID,
			&i.PaidAt,
			&i.PaymentReference,
			&i.AccrualJournalEntryID,
			&i.PaymentJournalEntryID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpenseItemsByReport = `-- name: SumExpenseItemsByReport :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2) AS total
FROM expense_items WHERE expense_report_id = $1
`

func (q *Queries) SumExpenseItemsByReport(ctx context.Context, expenseReportID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumExpenseItemsByReport, expenseReportID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const updateExpenseApprover = `-- name: UpdateExpenseApprover :exec
UPDATE expense_approvers SET
    department_name = $3, max_amount = $4, priority = $5, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateExpenseApproverParams struct {
	ID             uuid.UUID      `json:"id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	DepartmentName string         `json:"department_name"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
	Priority       int32          `json:"priority"`
}

func (q *Queries) UpdateExpenseApprover(ctx context.Context, arg UpdateExpenseApproverParams) error {
	_, err := q.db.Exec(ctx, updateExpenseApprover,
		arg.ID,
		arg.CompanyID,
		arg.DepartmentName,
		arg.MaxAmount,
		arg.Priority,
	)
	return err
}

const updateExpenseItem = `-- name: UpdateExpenseItem :exec
UPDATE expense_items SET
    category = $2, description = $3, amount = $4, merchant_name = $5,
    transaction_date = $6, gl_account_id = $7, policy_id = $8, updated_at = now()
WHERE id = $1
`

type UpdateExpenseItemParams struct {
	ID              uuid.UUID      `json:"id"`
	Category        string         `json:"category"`
	Description     string         `json:"description"`
	Amount          pgtype.Numeric `json:"amount"`
	MerchantName    *string        `json:"merchant_name"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	GlAccountID     pgtype.UUID    `json:"gl_account_id"`
	PolicyID        pgtype.UUID    `json:"policy_id"`
}

func (q *Queries) UpdateExpenseItem(ctx context.Context, arg UpdateExpenseItemParams) error {
	_, err := q.db.Exec(ctx, updateExpenseItem,
		arg.ID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.MerchantName,
		arg.TransactionDate,
		arg.GlAccountID,
		arg.PolicyID,
	)
	return err
}

const updateExpenseItemOCRFields = `-- name: UpdateExpenseItemOCRFields :exec
UPDATE expense_items SET
    merchant_name = $2, amount = $3, transaction_date = $4, category = $5,
    ai_category_confidence = $6, receipt_ocr_data = $7, updated_at = now()
WHERE id = $1
`

type UpdateExpenseItemOCRFieldsParams struct {
	ID                   uuid.UUID      `json:"id"`
	MerchantName         *string        `json:"merchant_name"`
	Amount               pgtype.Numeric `json:"amount"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	Category             string         `json:"category"`
	AiCategoryConfidence pgtype.Numeric `json:"ai_category_confidence"`
	ReceiptOcrData       []byte         `json:"receipt_ocr_data"`
}

func (q *Queries) UpdateExpenseItemOCRFields(ctx context.Context, arg UpdateExpenseItemOCRFieldsParams) error {
	_, err := q.db.Exec(ctx, updateExpenseItemOCRFields,
		arg.ID,
		arg.MerchantName,
		arg.Amount,
		arg.TransactionDate,
		arg.Category,
		arg.AiCategoryConfidence,
		arg.ReceiptOcrData,
	)
	return err
}

const updateExpenseItemReceipt = `-- name: UpdateExpenseItemReceipt :exec
UPDATE expense_items SET
    receipt_url = $2, receipt_ocr_data = $3, ai_category_confidence = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateExpenseItemReceiptParams struct {
	ID                   uuid.UUID      `json:"id"`
	ReceiptUrl           *string        `json:"receipt_url"`
	ReceiptOcrData       []byte         `json:"receipt_ocr_data"`
	AiCategoryConfidence pgtype.Numeric `json:"ai_category_confidence"`
}

func (q *Queries) UpdateExpenseItemReceipt(ctx context.Context, arg UpdateExpenseItemReceiptParams) error {
	_, err := q.db.Exec(ctx, updateExpenseItemReceipt,
		arg.ID,
		arg.ReceiptUrl,
		arg.ReceiptOcrData,
		arg.AiCategoryConfidence,
	)
	return err
}

const updateExpensePolicy = `-- name: UpdateExpensePolicy :exec
UPDATE expense_policies SET
    name = $3, category = $4, max_amount = $5, requires_receipt_above = $6,
    auto_approve_below = $7, ai_auto_approve = $8, description = $9,
    updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateExpensePolicyParams struct {
	ID                   uuid.UUID      `json:"id"`
	CompanyID            uuid.UUID      `json:"company_id"`
	Name                 string         `json:"name"`
	Category             string         `json:"category"`
	MaxAmount            pgtype.Numeric `json:"max_amount"`
	RequiresReceiptAbove pgtype.Numeric `json:"requires_receipt_above"`
	AutoApproveBelow     pgtype.Numeric `json:"auto_approve_below"`
	AiAutoApprove        bool           `json:"ai_auto_approve"`
	Description          *string        `json:"description"`
}

func (q *Queries) UpdateExpensePolicy(ctx context.Context, arg UpdateExpensePolicyParams) error {
	_, err := q.db.Exec(ctx, updateExpensePolicy,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Category,
		arg.MaxAmount,
		arg.RequiresReceiptAbove,
		arg.AutoApproveBelow,
		arg.AiAutoApprove,
		arg.Description,
	)
	return err
}

const updateExpenseReportAIReview = `-- name: UpdateExpenseReportAIReview :exec
UPDATE expense_reports SET
    status = $3, ai_reviewed_at = now(), ai_risk_score = $4,
    ai_decision = $5, ai_decision_reason = $6, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateExpenseReportAIReviewParams struct {
	ID               uuid.UUID `json:"id"`
	CompanyID        uuid.UUID `json:"company_id"`
	Status           string    `json:"status"`
	AiRiskScore      *int32    `json:"ai_risk_score"`
	AiDecision       *string   `json:"ai_decision"`
	AiDecisionReason *string   `json:"ai_decision_reason"`
}

func (q *Queries) UpdateExpenseReportAIReview(ctx context.Context, arg UpdateExpenseReportAIReviewParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportAIReview,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.AiRiskScore,
		arg.AiDecision,
		arg.AiDecisionReason,
	)
	return err
}

const updateExpenseReportApprove = `-- name: UpdateExpenseReportApprove :exec
UPDATE expense_reports SET
    status = 'approved', approver_user_id = $3, approved_at = now(),
    accrual_journal_entry_id = $4, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateExpenseReportApproveParams struct {
	ID                    uuid.UUID   `json:"id"`
	CompanyID             uuid.UUID   `json:"company_id"`
	ApproverUserID        pgtype.UUID `json:"approver_user_id"`
	AccrualJournalEntryID pgtype.UUID `json:"accrual_journal_entry_id"`
}

func (q *Queries) UpdateExpenseReportApprove(ctx context.Context, arg UpdateExpenseReportApproveParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportApprove,
		arg.ID,
		arg.CompanyID,
		arg.ApproverUserID,
		arg.AccrualJournalEntryID,
	)
	return err
}

const updateExpenseReportDraft = `-- name: UpdateExpenseReportDraft :exec
UPDATE expense_reports SET
    title = $3, notes = $4, updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'draft'
`

type UpdateExpenseReportDraftParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Title     string    `json:"title"`
	Notes     *string   `json:"notes"`
}

func (q *Queries) UpdateExpenseReportDraft(ctx context.Context, arg UpdateExpenseReportDraftParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportDraft,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Notes,
	)
	return err
}

const updateExpenseReportPaid = `-- name: UpdateExpenseReportPaid :exec
UPDATE expense_reports SET
    status = 'paid', reviewer_user_id = $3, paid_at = now(),
    payment_reference = $4, payment_journal_entry_id = $5, updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'approved'
`

type UpdateExpenseReportPaidParams struct {
	ID                    uuid.UUID   `json:"id"`
	CompanyID             uuid.UUID   `json:"company_id"`
	ReviewerUserID        pgtype.UUID `json:"reviewer_user_id"`
	PaymentReference      *string     `json:"payment_reference"`
	PaymentJournalEntryID pgtype.UUID `json:"payment_journal_entry_id"`
}

func (q *Queries) UpdateExpenseReportPaid(ctx context.Context, arg UpdateExpenseReportPaidParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportPaid,
		arg.ID,
		arg.CompanyID,
		arg.ReviewerUserID,
		arg.PaymentReference,
		arg.PaymentJournalEntryID,
	)
	return err
}

const updateExpenseReportReject = `-- name: UpdateExpenseReportReject :exec
UPDATE expense_reports SET
    status = 'rejected', approver_user_id = $3, rejection_reason = $4,
    updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateExpenseReportRejectParams struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	ApproverUserID  pgtype.UUID `json:"approver_user_id"`
	RejectionReason *string     `json:"rejection_reason"`
}

func (q *Queries) UpdateExpenseReportReject(ctx context.Context, arg UpdateExpenseReportRejectParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportReject,
		arg.ID,
		arg.CompanyID,
		arg.ApproverUserID,
		arg.RejectionReason,
	)
	return err
}

const updateExpenseReportRejectToDraft = `-- name: UpdateExpenseReportRejectToDraft :exec
UPDATE expense_reports SET
    status = 'draft', rejection_reason = NULL, approver_user_id = NULL,
    ai_risk_score = NULL, ai_decision = NULL, ai_decision_reason = NULL,
    ai_reviewed_at = NULL, submitted_at = NULL, updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'rejected'
`

type UpdateExpenseReportRejectToDraftParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) UpdateExpenseReportRejectToDraft(ctx context.Context, arg UpdateExpenseReportRejectToDraftParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportRejectToDraft, arg.ID, arg.CompanyID)
	return err
}

const updateExpenseReportStatus = `-- name: UpdateExpenseReportStatus :exec
UPDATE expense_reports SET status = $3, updated_at = now()
WHERE id = $1 AND company_id = $2
`

type UpdateExpenseReportStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateExpenseReportStatus(ctx context.Context, arg UpdateExpenseReportStatusParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportStatus, arg.ID, arg.CompanyID, arg.Status)
	return err
}

const updateExpenseReportSubmit = `-- name: UpdateExpenseReportSubmit :exec
UPDATE expense_reports SET
    status = 'submitted', total_amount = $3, submitted_at = now(), updated_at = now()
WHERE id = $1 AND company_id = $2 AND status = 'draft'
`

type UpdateExpenseReportSubmitParams struct {
	ID          uuid.UUID      `json:"id"`
	CompanyID   uuid.UUID      `json:"company_id"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) UpdateExpenseReportSubmit(ctx context.Context, arg UpdateExpenseReportSubmitParams) error {
	_, err := q.db.Exec(ctx, updateExpenseReportSubmit, arg.ID, arg.CompanyID, arg.TotalAmount)
	return err
}
