// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoicesByCompany = `-- name: CountInvoicesByCompany :one
SELECT COUNT(*) FROM invoices
WHERE company_id = $1
  AND ($2::varchar = '' OR $2::varchar IS NULL OR status = $2)
  AND ($3::varchar = '' OR $3::varchar IS NULL OR invoice_type = $3)
`

type CountInvoicesByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Column2   string    `json:"column_2"`
	Column3   string    `json:"column_3"`
}

func (q *Queries) CountInvoicesByCompany(ctx context.Context, arg CountInvoicesByCompanyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoicesByCompany, arg.CompanyID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvoicesByEISStatus = `-- name: CountInvoicesByEISStatus :many
SELECT COALESCE(eis_status, 'not_submitted') AS eis_status, COUNT(*) AS count
FROM invoices
WHERE company_id = $1
GROUP BY COALESCE(eis_status, 'not_submitted')
`

type CountInvoicesByEISStatusRow struct {
	EisStatus string `json:"eis_status"`
	Count     int64  `json:"count"`
}

func (q *Queries) CountInvoicesByEISStatus(ctx context.Context, companyID uuid.UUID) ([]CountInvoicesByEISStatusRow, error) {
	rows, err := q.db.Query(ctx, countInvoicesByEISStatus, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountInvoicesByEISStatusRow{}
	for rows.Next() {
		var i CountInvoicesByEISStatusRow
		if err := rows.Scan(&i.EisStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    company_id, invoice_number, invoice_type, status,
    customer_name, customer_tin, customer_address,
    invoice_date, due_date,
    subtotal, vat_amount, discount_amount, total_amount,
    vatable_sales, vat_exempt_sales, zero_rated_sales,
    reference_number, notes, vendor_id, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
) RETURNING id, company_id, invoice_number, invoice_type, status, customer_name, customer_tin, customer_address, invoice_date, due_date, subtotal, vat_amount, discount_amount, total_amount, vatable_sales, vat_exempt_sales, zero_rated_sales, eis_submission_id, eis_status, eis_submitted_at, eis_response, reference_number, notes, vendor_id, created_by, created_at, updated_at
`

type CreateInvoiceParams struct {
	CompanyID       uuid.UUID      `json:"company_id"`
	InvoiceNumber   string         `json:"invoice_number"`
	InvoiceType     string         `json:"invoice_type"`
	Status          string         `json:"status"`
	CustomerName    string         `json:"customer_name"`
	CustomerTin     *string        `json:"customer_tin"`
	CustomerAddress *string        `json:"customer_address"`
	InvoiceDate     pgtype.Date    `json:"invoice_date"`
	DueDate         pgtype.Date    `json:"due_date"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	VatAmount       pgtype.Numeric `json:"vat_amount"`
	DiscountAmount  pgtype.Numeric `json:"discount_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	VatableSales    pgtype.Numeric `json:"vatable_sales"`
	VatExemptSales  pgtype.Numeric `json:"vat_exempt_sales"`
	ZeroRatedSales  pgtype.Numeric `json:"zero_rated_sales"`
	ReferenceNumber *string        `json:"reference_number"`
	Notes           *string        `json:"notes"`
	VendorID        pgtype.UUID    `json:"vendor_id"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.CompanyID,
		arg.InvoiceNumber,
		arg.InvoiceType,
		arg.Status,
		arg.CustomerName,
		arg.CustomerTin,
		arg.CustomerAddress,
		arg.InvoiceDate,
		arg.DueDate,
		arg.Subtotal,
		arg.VatAmount,
		arg.DiscountAmount,
		arg.TotalAmount,
		arg.VatableSales,
		arg.VatExemptSales,
		arg.ZeroRatedSales,
		arg.ReferenceNumber,
		arg.Notes,
		arg.VendorID,
		arg.CreatedBy,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InvoiceNumber,
		&i.InvoiceType,
		&i.Status,
		&i.CustomerName,
		&i.CustomerTin,
		&i.CustomerAddress,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.VatAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.VatableSales,
		&i.VatExemptSales,
		&i.ZeroRatedSales,
		&i.EisSubmissionID,
		&i.EisStatus,
		&i.EisSubmittedAt,
		&i.EisResponse,
		&i.ReferenceNumber,
		&i.Notes,
		&i.VendorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (
    invoice_id, line_number, description, quantity, unit_price,
    amount, vat_type, vat_rate, vat_amount, discount, atc_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, invoice_id, line_number, description, quantity, unit_price, amount, vat_type, vat_rate, vat_amount, discount, atc_code, created_at
`

type CreateInvoiceItemParams struct {
	InvoiceID   uuid.UUID      `json:"invoice_id"`
	LineNumber  int32          `json:"line_number"`
	Description string         `json:"description"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Amount      pgtype.Numeric `json:"amount"`
	VatType     string         `json:"vat_type"`
	VatRate     pgtype.Numeric `json:"vat_rate"`
	VatAmount   pgtype.Numeric `json:"vat_amount"`
	Discount    pgtype.Numeric `json:"discount"`
	AtcCode     *string        `json:"atc_code"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.InvoiceID,
		arg.LineNumber,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.Amount,
		arg.VatType,
		arg.VatRate,
		arg.VatAmount,
		arg.Discount,
		arg.AtcCode,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.LineNumber,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.Amount,
		&i.VatType,
		&i.VatRate,
		&i.VatAmount,
		&i.Discount,
		&i.AtcCode,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1 AND company_id = $2
`

type DeleteInvoiceParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteInvoice(ctx context.Context, arg DeleteInvoiceParams) error {
	_, err := q.db.Exec(ctx, deleteInvoice, arg.ID, arg.CompanyID)
	return err
}

const deleteInvoiceItems = `-- name: DeleteInvoiceItems :exec
DELETE FROM invoice_items WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceItems(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItems, invoiceID)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, company_id, invoice_number, invoice_type, status, customer_name, customer_tin, customer_address, invoice_date, due_date, subtotal, vat_amount, discount_amount, total_amount, vatable_sales, vat_exempt_sales, zero_rated_sales, eis_submission_id, eis_status, eis_submitted_at, eis_response, reference_number, notes, vendor_id, created_by, created_at, updated_at FROM invoices WHERE id = $1 AND company_id = $2
`

type GetInvoiceByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, arg.ID, arg.CompanyID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InvoiceNumber,
		&i.InvoiceType,
		&i.Status,
		&i.CustomerName,
		&i.CustomerTin,
		&i.CustomerAddress,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.VatAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.VatableSales,
		&i.VatExemptSales,
		&i.ZeroRatedSales,
		&i.EisSubmissionID,
		&i.EisStatus,
		&i.EisSubmittedAt,
		&i.EisResponse,
		&i.ReferenceNumber,
		&i.Notes,
		&i.VendorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextInvoiceNumber = `-- name: GetNextInvoiceNumber :one
SELECT COALESCE(MAX(CAST(REGEXP_REPLACE(invoice_number, '[^0-9]', '', 'g') AS INTEGER)), 0) + 1 AS next_number
FROM invoices WHERE company_id = $1
`

func (q *Queries) GetNextInvoiceNumber(ctx context.Context, companyID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextInvoiceNumber, companyID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const listInvoiceItems = `-- name: ListInvoiceItems :many
SELECT id, invoice_id, line_number, description, quantity, unit_price, amount, vat_type, vat_rate, vat_amount, discount, atc_code, created_at FROM invoice_items WHERE invoice_id = $1 ORDER BY line_number
`

func (q *Queries) ListInvoiceItems(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listInvoiceItems, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceItem{}
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.LineNumber,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.Amount,
			&i.VatType,
			&i.VatRate,
			&i.VatAmount,
			&i.Discount,
			&i.AtcCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByCompany = `-- name: ListInvoicesByCompany :many
SELECT id, company_id, invoice_number, invoice_type, status, customer_name, customer_tin, customer_address, invoice_date, due_date, subtotal, vat_amount, discount_amount, total_amount, vatable_sales, vat_exempt_sales, zero_rated_sales, eis_submission_id, eis_status, eis_submitted_at, eis_response, reference_number, notes, vendor_id, created_by, created_at, updated_at FROM invoices
WHERE company_id = $1
  AND ($4::varchar = '' OR $4::varchar IS NULL OR status = $4)
  AND ($5::varchar = '' OR $5::varchar IS NULL OR invoice_type = $5)
ORDER BY invoice_date DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
	Column4   string    `json:"column_4"`
	Column5   string    `json:"column_5"`
}

func (q *Queries) ListInvoicesByCompany(ctx context.Context, arg ListInvoicesByCompanyParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByCompany,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.InvoiceNumber,
			&i.InvoiceType,
			&i.Status,
			&i.CustomerName,
			&i.CustomerTin,
			&i.CustomerAddress,
			&i.InvoiceDate,
			&i.DueDate,
			&i.Subtotal,
			&i.VatAmount,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.VatableSales,
			&i.VatExemptSales,
			&i.ZeroRatedSales,
			&i.EisSubmissionID,
			&i.EisStatus,
			&i.EisSubmittedAt,
			&i.EisResponse,
			&i.ReferenceNumber,
			&i.Notes,
			&i.VendorID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices SET
    invoice_number = COALESCE($3, invoice_number),
    invoice_type = COALESCE($4, invoice_type),
    status = COALESCE($5, status),
    customer_name = COALESCE($6, customer_name),
    customer_tin = COALESCE($7, customer_tin),
    customer_address = COALESCE($8, customer_address),
    invoice_date = COALESCE($9, invoice_date),
    due_date = COALESCE($10, due_date),
    subtotal = COALESCE($11, subtotal),
    vat_amount = COALESCE($12, vat_amount),
    discount_amount = COALESCE($13, discount_amount),
    total_amount = COALESCE($14, total_amount),
    vatable_sales = COALESCE($15, vatable_sales),
    vat_exempt_sales = COALESCE($16, vat_exempt_sales),
    zero_rated_sales = COALESCE($17, zero_rated_sales),
    reference_number = COALESCE($18, reference_number),
    notes = COALESCE($19, notes),
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, invoice_number, invoice_type, status, customer_name, customer_tin, customer_address, invoice_date, due_date, subtotal, vat_amount, discount_amount, total_amount, vatable_sales, vat_exempt_sales, zero_rated_sales, eis_submission_id, eis_status, eis_submitted_at, eis_response, reference_number, notes, vendor_id, created_by, created_at, updated_at
`

type UpdateInvoiceParams struct {
	ID              uuid.UUID      `json:"id"`
	CompanyID       uuid.UUID      `json:"company_id"`
	InvoiceNumber   string         `json:"invoice_number"`
	InvoiceType     string         `json:"invoice_type"`
	Status          string         `json:"status"`
	CustomerName    string         `json:"customer_name"`
	CustomerTin     *string        `json:"customer_tin"`
	CustomerAddress *string        `json:"customer_address"`
	InvoiceDate     pgtype.Date    `json:"invoice_date"`
	DueDate         pgtype.Date    `json:"due_date"`
	Subtotal        pgtype.Numeric `json:"subtotal"`
	VatAmount       pgtype.Numeric `json:"vat_amount"`
	DiscountAmount  pgtype.Numeric `json:"discount_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	VatableSales    pgtype.Numeric `json:"vatable_sales"`
	VatExemptSales  pgtype.Numeric `json:"vat_exempt_sales"`
	ZeroRatedSales  pgtype.Numeric `json:"zero_rated_sales"`
	ReferenceNumber *string        `json:"reference_number"`
	Notes           *string        `json:"notes"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.ID,
		arg.CompanyID,
		arg.InvoiceNumber,
		arg.InvoiceType,
		arg.Status,
		arg.CustomerName,
		arg.CustomerTin,
		arg.CustomerAddress,
		arg.InvoiceDate,
		arg.DueDate,
		arg.Subtotal,
		arg.VatAmount,
		arg.DiscountAmount,
		arg.TotalAmount,
		arg.VatableSales,
		arg.VatExemptSales,
		arg.ZeroRatedSales,
		arg.ReferenceNumber,
		arg.Notes,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InvoiceNumber,
		&i.InvoiceType,
		&i.Status,
		&i.CustomerName,
		&i.CustomerTin,
		&i.CustomerAddress,
		&i.InvoiceDate,
		&i.DueDate,
		&i.Subtotal,
		&i.VatAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.VatableSales,
		&i.VatExemptSales,
		&i.ZeroRatedSales,
		&i.EisSubmissionID,
		&i.EisStatus,
		&i.EisSubmittedAt,
		&i.EisResponse,
		&i.ReferenceNumber,
		&i.Notes,
		&i.VendorID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoiceEISStatus = `-- name: UpdateInvoiceEISStatus :exec
UPDATE invoices SET
    eis_submission_id = $3,
    eis_status = $4,
    eis_submitted_at = $5,
    eis_response = $6,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
`

type UpdateInvoiceEISStatusParams struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	EisSubmissionID *string            `json:"eis_submission_id"`
	EisStatus       *string            `json:"eis_status"`
	EisSubmittedAt  pgtype.Timestamptz `json:"eis_submitted_at"`
	EisResponse     []byte             `json:"eis_response"`
}

func (q *Queries) UpdateInvoiceEISStatus(ctx context.Context, arg UpdateInvoiceEISStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceEISStatus,
		arg.ID,
		arg.CompanyID,
		arg.EisSubmissionID,
		arg.EisStatus,
		arg.EisSubmittedAt,
		arg.EisResponse,
	)
	return err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoices SET status = $3, updated_at = NOW()
WHERE id = $1 AND company_id = $2
`

type UpdateInvoiceStatusParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.ID, arg.CompanyID, arg.Status)
	return err
}
