// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_entries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalancesByPrefix = `-- name: AccountBalancesByPrefix :many
SELECT
    a.id AS account_id,
    a.account_number,
    a.name AS account_name,
    a.account_type,
    a.sub_type,
    a.normal_balance,
    a.cash_flow_category,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(15,2) AS total_debit,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(15,2) AS total_credit
FROM accounts a
LEFT JOIN journal_lines jl ON jl.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
    AND je.company_id = $1
    AND je.status = 'posted'
    AND je.entry_date <= $2
WHERE a.company_id = $1
    AND a.is_active = true
    AND a.account_number LIKE $3 || '%'
GROUP BY a.id, a.account_number, a.name, a.account_type, a.sub_type, a.normal_balance, a.cash_flow_category
HAVING COALESCE(SUM(jl.debit), 0) > 0 OR COALESCE(SUM(jl.credit), 0) > 0
ORDER BY a.account_number ASC
`

type AccountBalancesByPrefixParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	AsOfDate  pgtype.Date `json:"as_of_date"`
	Prefix    *string     `json:"prefix"`
}

type AccountBalancesByPrefixRow struct {
	AccountID        uuid.UUID      `json:"account_id"`
	AccountNumber    string         `json:"account_number"`
	AccountName      string         `json:"account_name"`
	AccountType      string         `json:"account_type"`
	SubType          *string        `json:"sub_type"`
	NormalBalance    string         `json:"normal_balance"`
	CashFlowCategory *string        `json:"cash_flow_category"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// Returns aggregated debit/credit for all accounts matching a number prefix,
// for posted entries up to a given date.
func (q *Queries) AccountBalancesByPrefix(ctx context.Context, arg AccountBalancesByPrefixParams) ([]AccountBalancesByPrefixRow, error) {
	rows, err := q.db.Query(ctx, accountBalancesByPrefix, arg.CompanyID, arg.AsOfDate, arg.Prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalancesByPrefixRow{}
	for rows.Next() {
		var i AccountBalancesByPrefixRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountName,
			&i.AccountType,
			&i.SubType,
			&i.NormalBalance,
			&i.CashFlowCategory,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountLedger = `-- name: AccountLedger :many
SELECT
    je.id AS journal_entry_id,
    je.entry_number,
    je.entry_date,
    je.reference,
    jl.description,
    jl.debit,
    jl.credit
FROM journal_lines jl
JOIN journal_entries je ON je.id = jl.journal_entry_id
WHERE jl.account_id = $1
    AND je.company_id = $2
    AND je.status = 'posted'
    AND je.entry_date >= $3
    AND je.entry_date <= $4
ORDER BY je.entry_date ASC, je.entry_number ASC
`

type AccountLedgerParams struct {
	AccountID   uuid.UUID   `json:"account_id"`
	CompanyID   uuid.UUID   `json:"company_id"`
	EntryDate   pgtype.Date `json:"entry_date"`
	EntryDate_2 pgtype.Date `json:"entry_date_2"`
}

type AccountLedgerRow struct {
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	EntryNumber    *int32         `json:"entry_number"`
	EntryDate      pgtype.Date    `json:"entry_date"`
	Reference      *string        `json:"reference"`
	Description    *string        `json:"description"`
	Debit          pgtype.Numeric `json:"debit"`
	Credit         pgtype.Numeric `json:"credit"`
}

func (q *Queries) AccountLedger(ctx context.Context, arg AccountLedgerParams) ([]AccountLedgerRow, error) {
	rows, err := q.db.Query(ctx, accountLedger,
		arg.AccountID,
		arg.CompanyID,
		arg.EntryDate,
		arg.EntryDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountLedgerRow{}
	for rows.Next() {
		var i AccountLedgerRow
		if err := rows.Scan(
			&i.JournalEntryID,
			&i.EntryNumber,
			&i.EntryDate,
			&i.Reference,
			&i.Description,
			&i.Debit,
			&i.Credit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allAccountBalancesAsOf = `-- name: AllAccountBalancesAsOf :many
SELECT
    a.id AS account_id,
    a.account_number,
    a.name AS account_name,
    a.account_type,
    a.sub_type,
    a.normal_balance,
    a.cash_flow_category,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(15,2) AS total_debit,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(15,2) AS total_credit
FROM accounts a
LEFT JOIN journal_lines jl ON jl.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
    AND je.company_id = $1
    AND je.status = 'posted'
    AND je.entry_date <= $2
WHERE a.company_id = $1 AND a.is_active = true
GROUP BY a.id, a.account_number, a.name, a.account_type, a.sub_type, a.normal_balance, a.cash_flow_category
HAVING COALESCE(SUM(jl.debit), 0) > 0 OR COALESCE(SUM(jl.credit), 0) > 0
ORDER BY a.account_number ASC
`

type AllAccountBalancesAsOfParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	AsOfDate  pgtype.Date `json:"as_of_date"`
}

type AllAccountBalancesAsOfRow struct {
	AccountID        uuid.UUID      `json:"account_id"`
	AccountNumber    string         `json:"account_number"`
	AccountName      string         `json:"account_name"`
	AccountType      string         `json:"account_type"`
	SubType          *string        `json:"sub_type"`
	NormalBalance    string         `json:"normal_balance"`
	CashFlowCategory *string        `json:"cash_flow_category"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// Returns aggregated balances for ALL active accounts up to a date (for balance sheet).
func (q *Queries) AllAccountBalancesAsOf(ctx context.Context, arg AllAccountBalancesAsOfParams) ([]AllAccountBalancesAsOfRow, error) {
	rows, err := q.db.Query(ctx, allAccountBalancesAsOf, arg.CompanyID, arg.AsOfDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllAccountBalancesAsOfRow{}
	for rows.Next() {
		var i AllAccountBalancesAsOfRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountName,
			&i.AccountType,
			&i.SubType,
			&i.NormalBalance,
			&i.CashFlowCategory,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDraftEntriesByPeriod = `-- name: CountDraftEntriesByPeriod :one
SELECT COUNT(*) FROM journal_entries
WHERE period_id = $1 AND status = 'draft'
`

func (q *Queries) CountDraftEntriesByPeriod(ctx context.Context, periodID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftEntriesByPeriod, periodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJournalEntries = `-- name: CountJournalEntries :one
SELECT COUNT(*) FROM journal_entries WHERE company_id = $1
`

func (q *Queries) CountJournalEntries(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalEntries, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJournalEntriesByDateRange = `-- name: CountJournalEntriesByDateRange :one
SELECT COUNT(*) FROM journal_entries
WHERE company_id = $1 AND entry_date >= $2 AND entry_date <= $3
`

type CountJournalEntriesByDateRangeParams struct {
	CompanyID   uuid.UUID   `json:"company_id"`
	EntryDate   pgtype.Date `json:"entry_date"`
	EntryDate_2 pgtype.Date `json:"entry_date_2"`
}

func (q *Queries) CountJournalEntriesByDateRange(ctx context.Context, arg CountJournalEntriesByDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJournalEntriesByDateRange, arg.CompanyID, arg.EntryDate, arg.EntryDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (id, company_id, period_id, entry_date, reference, description, source_type, source_id, status, memo, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'draft', $9, $10, NOW(), NOW())
RETURNING id, company_id, period_id, entry_number, entry_date, reference, description, source_type, source_id, status, posted_by, posted_at, reversed_by_id, reverses_id, memo, created_by, created_at, updated_at, currency_code, company_seq_no, entry_hash, prev_hash, journal_book
`

type CreateJournalEntryParams struct {
	ID          uuid.UUID   `json:"id"`
	CompanyID   uuid.UUID   `json:"company_id"`
	PeriodID    pgtype.UUID `json:"period_id"`
	EntryDate   pgtype.Date `json:"entry_date"`
	Reference   *string     `json:"reference"`
	Description *string     `json:"description"`
	SourceType  *string     `json:"source_type"`
	SourceID    pgtype.UUID `json:"source_id"`
	Memo        *string     `json:"memo"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.ID,
		arg.CompanyID,
		arg.PeriodID,
		arg.EntryDate,
		arg.Reference,
		arg.Description,
		arg.SourceType,
		arg.SourceID,
		arg.Memo,
		arg.CreatedBy,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.EntryDate,
		&i.Reference,
		&i.Description,
		&i.SourceType,
		&i.SourceID,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.ReversedByID,
		&i.ReversesID,
		&i.Memo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrencyCode,
		&i.CompanySeqNo,
		&i.EntryHash,
		&i.PrevHash,
		&i.JournalBook,
	)
	return i, err
}

const createJournalLine = `-- name: CreateJournalLine :one
INSERT INTO journal_lines (id, journal_entry_id, account_id, line_number, description, debit, credit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, journal_entry_id, account_id, line_number, description, debit, credit, currency_code, exchange_rate, home_debit, home_credit, tax_code, tax_amount
`

type CreateJournalLineParams struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	LineNumber     int32          `json:"line_number"`
	Description    *string        `json:"description"`
	Debit          pgtype.Numeric `json:"debit"`
	Credit         pgtype.Numeric `json:"credit"`
}

func (q *Queries) CreateJournalLine(ctx context.Context, arg CreateJournalLineParams) (JournalLine, error) {
	row := q.db.QueryRow(ctx, createJournalLine,
		arg.ID,
		arg.JournalEntryID,
		arg.AccountID,
		arg.LineNumber,
		arg.Description,
		arg.Debit,
		arg.Credit,
	)
	var i JournalLine
	err := row.Scan(
		&i.ID,
		&i.JournalEntryID,
		&i.AccountID,
		&i.LineNumber,
		&i.Description,
		&i.Debit,
		&i.Credit,
		&i.CurrencyCode,
		&i.ExchangeRate,
		&i.HomeDebit,
		&i.HomeCredit,
		&i.TaxCode,
		&i.TaxAmount,
	)
	return i, err
}

const findJournalEntryBySourceRef = `-- name: FindJournalEntryBySourceRef :one
SELECT id, company_id, period_id, entry_number, entry_date, reference, description, source_type, source_id, status, posted_by, posted_at, reversed_by_id, reverses_id, memo, created_by, created_at, updated_at, currency_code, company_seq_no, entry_hash, prev_hash, journal_book FROM journal_entries
WHERE company_id = $1
    AND source_type = $2
    AND reference = $3
    AND status IN ('draft', 'posted')
ORDER BY created_at DESC
LIMIT 1
`

type FindJournalEntryBySourceRefParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	SourceType *string   `json:"source_type"`
	Reference  *string   `json:"reference"`
}

func (q *Queries) FindJournalEntryBySourceRef(ctx context.Context, arg FindJournalEntryBySourceRefParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, findJournalEntryBySourceRef, arg.CompanyID, arg.SourceType, arg.Reference)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.EntryDate,
		&i.Reference,
		&i.Description,
		&i.SourceType,
		&i.SourceID,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.ReversedByID,
		&i.ReversesID,
		&i.Memo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrencyCode,
		&i.CompanySeqNo,
		&i.EntryHash,
		&i.PrevHash,
		&i.JournalBook,
	)
	return i, err
}

const getJournalEntryByID = `-- name: GetJournalEntryByID :one
SELECT id, company_id, period_id, entry_number, entry_date, reference, description, source_type, source_id, status, posted_by, posted_at, reversed_by_id, reverses_id, memo, created_by, created_at, updated_at, currency_code, company_seq_no, entry_hash, prev_hash, journal_book FROM journal_entries WHERE id = $1
`

func (q *Queries) GetJournalEntryByID(ctx context.Context, id uuid.UUID) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByID, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.EntryDate,
		&i.Reference,
		&i.Description,
		&i.SourceType,
		&i.SourceID,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.ReversedByID,
		&i.ReversesID,
		&i.Memo,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrencyCode,
		&i.CompanySeqNo,
		&i.EntryHash,
		&i.PrevHash,
		&i.JournalBook,
	)
	return i, err
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, company_id, period_id, entry_number, entry_date, reference, description, source_type, source_id, status, posted_by, posted_at, reversed_by_id, reverses_id, memo, created_by, created_at, updated_at, currency_code, company_seq_no, entry_hash, prev_hash, journal_book FROM journal_entries
WHERE company_id = $1
ORDER BY entry_date DESC, entry_number DESC
LIMIT $2 OFFSET $3
`

type ListJournalEntriesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PeriodID,
			&i.EntryNumber,
			&i.EntryDate,
			&i.Reference,
			&i.Description,
			&i.SourceType,
			&i.SourceID,
			&i.Status,
			&i.PostedBy,
			&i.PostedAt,
			&i.ReversedByID,
			&i.ReversesID,
			&i.Memo,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrencyCode,
			&i.CompanySeqNo,
			&i.EntryHash,
			&i.PrevHash,
			&i.JournalBook,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntriesByDateRange = `-- name: ListJournalEntriesByDateRange :many
SELECT id, company_id, period_id, entry_number, entry_date, reference, description, source_type, source_id, status, posted_by, posted_at, reversed_by_id, reverses_id, memo, created_by, created_at, updated_at, currency_code, company_seq_no, entry_hash, prev_hash, journal_book FROM journal_entries
WHERE company_id = $1
    AND entry_date >= $2
    AND entry_date <= $3
ORDER BY entry_date DESC, entry_number DESC
LIMIT $4 OFFSET $5
`

type ListJournalEntriesByDateRangeParams struct {
	CompanyID   uuid.UUID   `json:"company_id"`
	EntryDate   pgtype.Date `json:"entry_date"`
	EntryDate_2 pgtype.Date `json:"entry_date_2"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListJournalEntriesByDateRange(ctx context.Context, arg ListJournalEntriesByDateRangeParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntriesByDateRange,
		arg.CompanyID,
		arg.EntryDate,
		arg.EntryDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.PeriodID,
			&i.EntryNumber,
			&i.EntryDate,
			&i.Reference,
			&i.Description,
			&i.SourceType,
			&i.SourceID,
			&i.Status,
			&i.PostedBy,
			&i.PostedAt,
			&i.ReversedByID,
			&i.ReversesID,
			&i.Memo,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrencyCode,
			&i.CompanySeqNo,
			&i.EntryHash,
			&i.PrevHash,
			&i.JournalBook,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalLinesByEntry = `-- name: ListJournalLinesByEntry :many
SELECT jl.id, jl.journal_entry_id, jl.account_id, jl.line_number, jl.description, jl.debit, jl.credit, jl.currency_code, jl.exchange_rate, jl.home_debit, jl.home_credit, jl.tax_code, jl.tax_amount, a.name AS account_name, a.account_number
FROM journal_lines jl
JOIN accounts a ON a.id = jl.account_id
WHERE jl.journal_entry_id = $1
ORDER BY jl.line_number ASC
`

type ListJournalLinesByEntryRow struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	LineNumber     int32          `json:"line_number"`
	Description    *string        `json:"description"`
	Debit          pgtype.Numeric `json:"debit"`
	Credit         pgtype.Numeric `json:"credit"`
	CurrencyCode   *string        `json:"currency_code"`
	ExchangeRate   pgtype.Numeric `json:"exchange_rate"`
	HomeDebit      pgtype.Numeric `json:"home_debit"`
	HomeCredit     pgtype.Numeric `json:"home_credit"`
	TaxCode        *string        `json:"tax_code"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	AccountName    string         `json:"account_name"`
	AccountNumber  string         `json:"account_number"`
}

func (q *Queries) ListJournalLinesByEntry(ctx context.Context, journalEntryID uuid.UUID) ([]ListJournalLinesByEntryRow, error) {
	rows, err := q.db.Query(ctx, listJournalLinesByEntry, journalEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalLinesByEntryRow{}
	for rows.Next() {
		var i ListJournalLinesByEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalEntryID,
			&i.AccountID,
			&i.LineNumber,
			&i.Description,
			&i.Debit,
			&i.Credit,
			&i.CurrencyCode,
			&i.ExchangeRate,
			&i.HomeDebit,
			&i.HomeCredit,
			&i.TaxCode,
			&i.TaxAmount,
			&i.AccountName,
			&i.AccountNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodAccountBalances = `-- name: PeriodAccountBalances :many
SELECT
    a.id AS account_id,
    a.account_number,
    a.name AS account_name,
    a.account_type,
    a.sub_type,
    a.normal_balance,
    a.cash_flow_category,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(15,2) AS total_debit,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(15,2) AS total_credit
FROM accounts a
LEFT JOIN journal_lines jl ON jl.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
    AND je.company_id = $1
    AND je.status = 'posted'
    AND je.entry_date >= $2
    AND je.entry_date <= $3
WHERE a.company_id = $1
    AND a.is_active = true
    AND a.account_number LIKE $4 || '%'
GROUP BY a.id, a.account_number, a.name, a.account_type, a.sub_type, a.normal_balance, a.cash_flow_category
HAVING COALESCE(SUM(jl.debit), 0) > 0 OR COALESCE(SUM(jl.credit), 0) > 0
ORDER BY a.account_number ASC
`

type PeriodAccountBalancesParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
	Prefix    *string     `json:"prefix"`
}

type PeriodAccountBalancesRow struct {
	AccountID        uuid.UUID      `json:"account_id"`
	AccountNumber    string         `json:"account_number"`
	AccountName      string         `json:"account_name"`
	AccountType      string         `json:"account_type"`
	SubType          *string        `json:"sub_type"`
	NormalBalance    string         `json:"normal_balance"`
	CashFlowCategory *string        `json:"cash_flow_category"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// Returns aggregated debit/credit for all accounts matching a number prefix,
// for posted entries within a date range.
func (q *Queries) PeriodAccountBalances(ctx context.Context, arg PeriodAccountBalancesParams) ([]PeriodAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, periodAccountBalances,
		arg.CompanyID,
		arg.FromDate,
		arg.ToDate,
		arg.Prefix,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeriodAccountBalancesRow{}
	for rows.Next() {
		var i PeriodAccountBalancesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountName,
			&i.AccountType,
			&i.SubType,
			&i.NormalBalance,
			&i.CashFlowCategory,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const periodAllAccountBalances = `-- name: PeriodAllAccountBalances :many
SELECT
    a.id AS account_id,
    a.account_number,
    a.name AS account_name,
    a.account_type,
    a.sub_type,
    a.normal_balance,
    a.cash_flow_category,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(15,2) AS total_debit,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(15,2) AS total_credit
FROM accounts a
LEFT JOIN journal_lines jl ON jl.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
    AND je.company_id = $1
    AND je.status = 'posted'
    AND je.entry_date >= $2
    AND je.entry_date <= $3
WHERE a.company_id = $1 AND a.is_active = true
GROUP BY a.id, a.account_number, a.name, a.account_type, a.sub_type, a.normal_balance, a.cash_flow_category
HAVING COALESCE(SUM(jl.debit), 0) > 0 OR COALESCE(SUM(jl.credit), 0) > 0
ORDER BY a.account_number ASC
`

type PeriodAllAccountBalancesParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
}

type PeriodAllAccountBalancesRow struct {
	AccountID        uuid.UUID      `json:"account_id"`
	AccountNumber    string         `json:"account_number"`
	AccountName      string         `json:"account_name"`
	AccountType      string         `json:"account_type"`
	SubType          *string        `json:"sub_type"`
	NormalBalance    string         `json:"normal_balance"`
	CashFlowCategory *string        `json:"cash_flow_category"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// Returns aggregated balances for ALL active accounts within a date range (for income statement).
func (q *Queries) PeriodAllAccountBalances(ctx context.Context, arg PeriodAllAccountBalancesParams) ([]PeriodAllAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, periodAllAccountBalances, arg.CompanyID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeriodAllAccountBalancesRow{}
	for rows.Next() {
		var i PeriodAllAccountBalancesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountName,
			&i.AccountType,
			&i.SubType,
			&i.NormalBalance,
			&i.CashFlowCategory,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postJournalEntry = `-- name: PostJournalEntry :exec
UPDATE journal_entries SET
    status = 'posted',
    posted_by = $2,
    posted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'draft'
`

type PostJournalEntryParams struct {
	ID       uuid.UUID   `json:"id"`
	PostedBy pgtype.UUID `json:"posted_by"`
}

func (q *Queries) PostJournalEntry(ctx context.Context, arg PostJournalEntryParams) error {
	_, err := q.db.Exec(ctx, postJournalEntry, arg.ID, arg.PostedBy)
	return err
}

const reverseJournalEntry = `-- name: ReverseJournalEntry :exec
UPDATE journal_entries SET
    status = 'reversed',
    reversed_by_id = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'posted'
`

type ReverseJournalEntryParams struct {
	ID           uuid.UUID   `json:"id"`
	ReversedByID pgtype.UUID `json:"reversed_by_id"`
}

func (q *Queries) ReverseJournalEntry(ctx context.Context, arg ReverseJournalEntryParams) error {
	_, err := q.db.Exec(ctx, reverseJournalEntry, arg.ID, arg.ReversedByID)
	return err
}

const sumJournalLines = `-- name: SumJournalLines :one
SELECT
    COALESCE(SUM(debit), 0)::NUMERIC(15,2) AS total_debit,
    COALESCE(SUM(credit), 0)::NUMERIC(15,2) AS total_credit
FROM journal_lines
WHERE journal_entry_id = $1
`

type SumJournalLinesRow struct {
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
}

func (q *Queries) SumJournalLines(ctx context.Context, journalEntryID uuid.UUID) (SumJournalLinesRow, error) {
	row := q.db.QueryRow(ctx, sumJournalLines, journalEntryID)
	var i SumJournalLinesRow
	err := row.Scan(&i.TotalDebit, &i.TotalCredit)
	return i, err
}

const trialBalance = `-- name: TrialBalance :many
SELECT
    a.id AS account_id,
    a.account_number,
    a.name AS account_name,
    a.account_type,
    COALESCE(SUM(jl.debit), 0)::NUMERIC(15,2) AS debit_balance,
    COALESCE(SUM(jl.credit), 0)::NUMERIC(15,2) AS credit_balance
FROM accounts a
LEFT JOIN journal_lines jl ON jl.account_id = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_entry_id
    AND je.company_id = $1
    AND je.status = 'posted'
    AND je.entry_date >= $2
    AND je.entry_date <= $3
WHERE a.company_id = $1 AND a.is_active = true
GROUP BY a.id, a.account_number, a.name, a.account_type
HAVING COALESCE(SUM(jl.debit), 0) > 0 OR COALESCE(SUM(jl.credit), 0) > 0
ORDER BY a.account_number ASC
`

type TrialBalanceParams struct {
	CompanyID   uuid.UUID   `json:"company_id"`
	EntryDate   pgtype.Date `json:"entry_date"`
	EntryDate_2 pgtype.Date `json:"entry_date_2"`
}

type TrialBalanceRow struct {
	AccountID     uuid.UUID      `json:"account_id"`
	AccountNumber string         `json:"account_number"`
	AccountName   string         `json:"account_name"`
	AccountType   string         `json:"account_type"`
	DebitBalance  pgtype.Numeric `json:"debit_balance"`
	CreditBalance pgtype.Numeric `json:"credit_balance"`
}

func (q *Queries) TrialBalance(ctx context.Context, arg TrialBalanceParams) ([]TrialBalanceRow, error) {
	rows, err := q.db.Query(ctx, trialBalance, arg.CompanyID, arg.EntryDate, arg.EntryDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrialBalanceRow{}
	for rows.Next() {
		var i TrialBalanceRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountNumber,
			&i.AccountName,
			&i.AccountType,
			&i.DebitBalance,
			&i.CreditBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
