// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	pgvector "github.com/pgvector/pgvector-go"
)

const countKnowledgeChunks = `-- name: CountKnowledgeChunks :one
SELECT COUNT(*) FROM knowledge_chunks
`

func (q *Queries) CountKnowledgeChunks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeChunks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledgeChunksByCategory = `-- name: CountKnowledgeChunksByCategory :many
SELECT COALESCE(category, 'uncategorized') as category, COUNT(*) as count
FROM knowledge_chunks
GROUP BY category
`

type CountKnowledgeChunksByCategoryRow struct {
	Category string `json:"category"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountKnowledgeChunksByCategory(ctx context.Context) ([]CountKnowledgeChunksByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countKnowledgeChunksByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountKnowledgeChunksByCategoryRow{}
	for rows.Next() {
		var i CountKnowledgeChunksByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countKnowledgeChunksWithEmbedding = `-- name: CountKnowledgeChunksWithEmbedding :one
SELECT COUNT(*) FROM knowledge_chunks WHERE embedding IS NOT NULL
`

func (q *Queries) CountKnowledgeChunksWithEmbedding(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeChunksWithEmbedding)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKnowledgeChunk = `-- name: CreateKnowledgeChunk :one
INSERT INTO knowledge_chunks (id, source, category, content, embedding, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, source, category, content, embedding, metadata, created_at
`

type CreateKnowledgeChunkParams struct {
	ID        uuid.UUID        `json:"id"`
	Source    *string          `json:"source"`
	Category  *string          `json:"category"`
	Content   string           `json:"content"`
	Embedding *pgvector.Vector `json:"embedding"`
	Metadata  []byte           `json:"metadata"`
}

func (q *Queries) CreateKnowledgeChunk(ctx context.Context, arg CreateKnowledgeChunkParams) (KnowledgeChunk, error) {
	row := q.db.QueryRow(ctx, createKnowledgeChunk,
		arg.ID,
		arg.Source,
		arg.Category,
		arg.Content,
		arg.Embedding,
		arg.Metadata,
	)
	var i KnowledgeChunk
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Category,
		&i.Content,
		&i.Embedding,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAllKnowledgeChunks = `-- name: ListAllKnowledgeChunks :many
SELECT id, source, category, content, (embedding IS NOT NULL) as has_embedding, created_at
FROM knowledge_chunks
ORDER BY created_at DESC
LIMIT $1
`

type ListAllKnowledgeChunksRow struct {
	ID           uuid.UUID   `json:"id"`
	Source       *string     `json:"source"`
	Category     *string     `json:"category"`
	Content      string      `json:"content"`
	HasEmbedding interface{} `json:"has_embedding"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) ListAllKnowledgeChunks(ctx context.Context, limit int32) ([]ListAllKnowledgeChunksRow, error) {
	rows, err := q.db.Query(ctx, listAllKnowledgeChunks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllKnowledgeChunksRow{}
	for rows.Next() {
		var i ListAllKnowledgeChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Category,
			&i.Content,
			&i.HasEmbedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeByCategory = `-- name: ListKnowledgeByCategory :many
SELECT id, source, category, content, (embedding IS NOT NULL) as has_embedding, created_at
FROM knowledge_chunks
WHERE category = $1
ORDER BY created_at DESC
`

type ListKnowledgeByCategoryRow struct {
	ID           uuid.UUID   `json:"id"`
	Source       *string     `json:"source"`
	Category     *string     `json:"category"`
	Content      string      `json:"content"`
	HasEmbedding interface{} `json:"has_embedding"`
	CreatedAt    time.Time   `json:"created_at"`
}

func (q *Queries) ListKnowledgeByCategory(ctx context.Context, category *string) ([]ListKnowledgeByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listKnowledgeByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnowledgeByCategoryRow{}
	for rows.Next() {
		var i ListKnowledgeByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Category,
			&i.Content,
			&i.HasEmbedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSimilarChunks = `-- name: SearchSimilarChunks :many
SELECT id, source, category, content, metadata, created_at,
       embedding <=> $1::vector AS distance
FROM knowledge_chunks
ORDER BY embedding <=> $1::vector
LIMIT $2
`

type SearchSimilarChunksParams struct {
	Column1 pgvector.Vector `json:"column_1"`
	Limit   int32           `json:"limit"`
}

type SearchSimilarChunksRow struct {
	ID        uuid.UUID   `json:"id"`
	Source    *string     `json:"source"`
	Category  *string     `json:"category"`
	Content   string      `json:"content"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
	Distance  interface{} `json:"distance"`
}

func (q *Queries) SearchSimilarChunks(ctx context.Context, arg SearchSimilarChunksParams) ([]SearchSimilarChunksRow, error) {
	rows, err := q.db.Query(ctx, searchSimilarChunks, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSimilarChunksRow{}
	for rows.Next() {
		var i SearchSimilarChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Category,
			&i.Content,
			&i.Metadata,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
