// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLinkToken = `-- name: CreateLinkToken :one
INSERT INTO link_tokens (user_id, company_id, token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, company_id, token, expires_at, used, created_at
`

type CreateLinkTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateLinkToken(ctx context.Context, arg CreateLinkTokenParams) (LinkToken, error) {
	row := q.db.QueryRow(ctx, createLinkToken,
		arg.UserID,
		arg.CompanyID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i LinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :execrows
DELETE FROM link_tokens WHERE expires_at < NOW() OR used = true
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getValidLinkToken = `-- name: GetValidLinkToken :one
SELECT id, user_id, company_id, token, expires_at, used, created_at FROM link_tokens
WHERE token = $1 AND used = false AND expires_at > NOW()
`

func (q *Queries) GetValidLinkToken(ctx context.Context, token string) (LinkToken, error) {
	row := q.db.QueryRow(ctx, getValidLinkToken, token)
	var i LinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markLinkTokenUsed = `-- name: MarkLinkTokenUsed :exec
UPDATE link_tokens SET used = true WHERE id = $1
`

func (q *Queries) MarkLinkTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markLinkTokenUsed, id)
	return err
}
