// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: misc.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanExpiredTokens = `-- name: CleanExpiredTokens :exec
DELETE FROM revoked_tokens WHERE expires_at < NOW()
`

func (q *Queries) CleanExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanExpiredTokens)
	return err
}

const countBankReconBatchesByCompany = `-- name: CountBankReconBatchesByCompany :one
SELECT COUNT(*) FROM bank_reconciliation_batches WHERE company_id = $1
`

func (q *Queries) CountBankReconBatchesByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBankReconBatchesByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedUnlinkedReceipts = `-- name: CountCompletedUnlinkedReceipts :one
SELECT COUNT(*) FROM receipt_batches
WHERE company_id = $1
    AND status = 'completed'
    AND (transaction_ids IS NULL OR transaction_ids = '{}')
`

func (q *Queries) CountCompletedUnlinkedReceipts(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedUnlinkedReceipts, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReceiptBatchesByCompany = `-- name: CountReceiptBatchesByCompany :one
SELECT COUNT(*) FROM receipt_batches WHERE company_id = $1
`

func (q *Queries) CountReceiptBatchesByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReceiptBatchesByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankReconBatch = `-- name: CreateBankReconBatch :one

INSERT INTO bank_reconciliation_batches (id, company_id, created_by, session_id, status, source_files, total_entries, amount_tolerance, date_tolerance_days, period, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, company_id, created_by, session_id, status, source_files, total_entries, parse_summary, match_result, ai_suggestions, ai_explanations, amount_tolerance, date_tolerance_days, period, error_message, created_at, updated_at
`

type CreateBankReconBatchParams struct {
	ID                uuid.UUID      `json:"id"`
	CompanyID         uuid.UUID      `json:"company_id"`
	CreatedBy         uuid.UUID      `json:"created_by"`
	SessionID         pgtype.UUID    `json:"session_id"`
	Status            string         `json:"status"`
	SourceFiles       []byte         `json:"source_files"`
	TotalEntries      int32          `json:"total_entries"`
	AmountTolerance   pgtype.Numeric `json:"amount_tolerance"`
	DateToleranceDays int32          `json:"date_tolerance_days"`
	Period            string         `json:"period"`
}

// ---- Bank Reconciliation Batches ----
func (q *Queries) CreateBankReconBatch(ctx context.Context, arg CreateBankReconBatchParams) (BankReconciliationBatch, error) {
	row := q.db.QueryRow(ctx, createBankReconBatch,
		arg.ID,
		arg.CompanyID,
		arg.CreatedBy,
		arg.SessionID,
		arg.Status,
		arg.SourceFiles,
		arg.TotalEntries,
		arg.AmountTolerance,
		arg.DateToleranceDays,
		arg.Period,
	)
	var i BankReconciliationBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.SessionID,
		&i.Status,
		&i.SourceFiles,
		&i.TotalEntries,
		&i.ParseSummary,
		&i.MatchResult,
		&i.AiSuggestions,
		&i.AiExplanations,
		&i.AmountTolerance,
		&i.DateToleranceDays,
		&i.Period,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCorrectionHistory = `-- name: CreateCorrectionHistory :exec

INSERT INTO correction_history (id, company_id, report_type, field_name, old_value, new_value, reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
`

type CreateCorrectionHistoryParams struct {
	ID         uuid.UUID `json:"id"`
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
	FieldName  *string   `json:"field_name"`
	OldValue   *string   `json:"old_value"`
	NewValue   *string   `json:"new_value"`
	Reason     *string   `json:"reason"`
}

// ---- Correction History (legacy) ----
func (q *Queries) CreateCorrectionHistory(ctx context.Context, arg CreateCorrectionHistoryParams) error {
	_, err := q.db.Exec(ctx, createCorrectionHistory,
		arg.ID,
		arg.CompanyID,
		arg.ReportType,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
	)
	return err
}

const createReceiptBatch = `-- name: CreateReceiptBatch :one

INSERT INTO receipt_batches (id, company_id, user_id, status, total_images, processed_count, session_id, report_id, report_type, period, results, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
RETURNING id, company_id, user_id, status, total_images, processed_count, session_id, report_id, report_type, period, results, error_message, created_at, updated_at, transaction_ids
`

type CreateReceiptBatchParams struct {
	ID             uuid.UUID   `json:"id"`
	CompanyID      uuid.UUID   `json:"company_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Status         string      `json:"status"`
	TotalImages    int32       `json:"total_images"`
	ProcessedCount int32       `json:"processed_count"`
	SessionID      pgtype.UUID `json:"session_id"`
	ReportID       pgtype.UUID `json:"report_id"`
	ReportType     string      `json:"report_type"`
	Period         string      `json:"period"`
	Results        []byte      `json:"results"`
}

// ---- Receipt Batches ----
func (q *Queries) CreateReceiptBatch(ctx context.Context, arg CreateReceiptBatchParams) (ReceiptBatch, error) {
	row := q.db.QueryRow(ctx, createReceiptBatch,
		arg.ID,
		arg.CompanyID,
		arg.UserID,
		arg.Status,
		arg.TotalImages,
		arg.ProcessedCount,
		arg.SessionID,
		arg.ReportID,
		arg.ReportType,
		arg.Period,
		arg.Results,
	)
	var i ReceiptBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Status,
		&i.TotalImages,
		&i.ProcessedCount,
		&i.SessionID,
		&i.ReportID,
		&i.ReportType,
		&i.Period,
		&i.Results,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionIds,
	)
	return i, err
}

const createRevokedToken = `-- name: CreateRevokedToken :exec

INSERT INTO revoked_tokens (id, jti, user_id, revoked_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRevokedTokenParams struct {
	ID        uuid.UUID `json:"id"`
	Jti       string    `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	RevokedAt time.Time `json:"revoked_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ---- Revoked Tokens ----
func (q *Queries) CreateRevokedToken(ctx context.Context, arg CreateRevokedTokenParams) error {
	_, err := q.db.Exec(ctx, createRevokedToken,
		arg.ID,
		arg.Jti,
		arg.UserID,
		arg.RevokedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteUserPreference = `-- name: DeleteUserPreference :exec
DELETE FROM user_preferences
WHERE company_id = $1 AND report_type = $2
`

type DeleteUserPreferenceParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
}

func (q *Queries) DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteUserPreference, arg.CompanyID, arg.ReportType)
	return err
}

const getBankReconBatchByID = `-- name: GetBankReconBatchByID :one
SELECT id, company_id, created_by, session_id, status, source_files, total_entries, parse_summary, match_result, ai_suggestions, ai_explanations, amount_tolerance, date_tolerance_days, period, error_message, created_at, updated_at FROM bank_reconciliation_batches WHERE id = $1
`

func (q *Queries) GetBankReconBatchByID(ctx context.Context, id uuid.UUID) (BankReconciliationBatch, error) {
	row := q.db.QueryRow(ctx, getBankReconBatchByID, id)
	var i BankReconciliationBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.SessionID,
		&i.Status,
		&i.SourceFiles,
		&i.TotalEntries,
		&i.ParseSummary,
		&i.MatchResult,
		&i.AiSuggestions,
		&i.AiExplanations,
		&i.AmountTolerance,
		&i.DateToleranceDays,
		&i.Period,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompletedUnlinkedReceipts = `-- name: GetCompletedUnlinkedReceipts :many

SELECT id, company_id, user_id, status, total_images, processed_count, session_id, report_id, report_type, period, results, error_message, created_at, updated_at, transaction_ids FROM receipt_batches
WHERE company_id = $1
    AND status = 'completed'
    AND (transaction_ids IS NULL OR transaction_ids = '{}')
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type GetCompletedUnlinkedReceiptsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

// ---- Receipt Bridge Queries ----
func (q *Queries) GetCompletedUnlinkedReceipts(ctx context.Context, arg GetCompletedUnlinkedReceiptsParams) ([]ReceiptBatch, error) {
	rows, err := q.db.Query(ctx, getCompletedUnlinkedReceipts, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptBatch{}
	for rows.Next() {
		var i ReceiptBatch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Status,
			&i.TotalImages,
			&i.ProcessedCount,
			&i.SessionID,
			&i.ReportID,
			&i.ReportType,
			&i.Period,
			&i.Results,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFormSchemaByType = `-- name: GetFormSchemaByType :one

SELECT id, form_type, version, name, frequency, is_active, schema_def, calculation_rules, created_at, updated_at FROM form_schemas WHERE form_type = $1 AND is_active = true
`

// ---- Form Schemas ----
func (q *Queries) GetFormSchemaByType(ctx context.Context, formType string) (FormSchema, error) {
	row := q.db.QueryRow(ctx, getFormSchemaByType, formType)
	var i FormSchema
	err := row.Scan(
		&i.ID,
		&i.FormType,
		&i.Version,
		&i.Name,
		&i.Frequency,
		&i.IsActive,
		&i.SchemaDef,
		&i.CalculationRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReceiptBatchByID = `-- name: GetReceiptBatchByID :one
SELECT id, company_id, user_id, status, total_images, processed_count, session_id, report_id, report_type, period, results, error_message, created_at, updated_at, transaction_ids FROM receipt_batches WHERE id = $1
`

func (q *Queries) GetReceiptBatchByID(ctx context.Context, id uuid.UUID) (ReceiptBatch, error) {
	row := q.db.QueryRow(ctx, getReceiptBatchByID, id)
	var i ReceiptBatch
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Status,
		&i.TotalImages,
		&i.ProcessedCount,
		&i.SessionID,
		&i.ReportID,
		&i.ReportType,
		&i.Period,
		&i.Results,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionIds,
	)
	return i, err
}

const getUserPreferenceByCompanyAndType = `-- name: GetUserPreferenceByCompanyAndType :one
SELECT id, company_id, report_type, column_mappings, format_rules, auto_fill_rules, updated_at FROM user_preferences
WHERE company_id = $1 AND report_type = $2
`

type GetUserPreferenceByCompanyAndTypeParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
}

func (q *Queries) GetUserPreferenceByCompanyAndType(ctx context.Context, arg GetUserPreferenceByCompanyAndTypeParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferenceByCompanyAndType, arg.CompanyID, arg.ReportType)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReportType,
		&i.ColumnMappings,
		&i.FormatRules,
		&i.AutoFillRules,
		&i.UpdatedAt,
	)
	return i, err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS(SELECT 1 FROM revoked_tokens WHERE jti = $1) AS is_revoked
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var is_revoked bool
	err := row.Scan(&is_revoked)
	return is_revoked, err
}

const linkReceiptToTransactions = `-- name: LinkReceiptToTransactions :exec
UPDATE receipt_batches SET
    transaction_ids = $2,
    updated_at = NOW()
WHERE id = $1
`

type LinkReceiptToTransactionsParams struct {
	ID             uuid.UUID   `json:"id"`
	TransactionIds []uuid.UUID `json:"transaction_ids"`
}

func (q *Queries) LinkReceiptToTransactions(ctx context.Context, arg LinkReceiptToTransactionsParams) error {
	_, err := q.db.Exec(ctx, linkReceiptToTransactions, arg.ID, arg.TransactionIds)
	return err
}

const listActiveFormSchemas = `-- name: ListActiveFormSchemas :many
SELECT id, form_type, version, name, frequency, is_active, schema_def, calculation_rules, created_at, updated_at FROM form_schemas WHERE is_active = true ORDER BY form_type
`

func (q *Queries) ListActiveFormSchemas(ctx context.Context) ([]FormSchema, error) {
	rows, err := q.db.Query(ctx, listActiveFormSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormSchema{}
	for rows.Next() {
		var i FormSchema
		if err := rows.Scan(
			&i.ID,
			&i.FormType,
			&i.Version,
			&i.Name,
			&i.Frequency,
			&i.IsActive,
			&i.SchemaDef,
			&i.CalculationRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankReconBatchesByCompany = `-- name: ListBankReconBatchesByCompany :many
SELECT id, company_id, created_by, session_id, status, source_files, total_entries, parse_summary, match_result, ai_suggestions, ai_explanations, amount_tolerance, date_tolerance_days, period, error_message, created_at, updated_at FROM bank_reconciliation_batches WHERE company_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListBankReconBatchesByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListBankReconBatchesByCompany(ctx context.Context, arg ListBankReconBatchesByCompanyParams) ([]BankReconciliationBatch, error) {
	rows, err := q.db.Query(ctx, listBankReconBatchesByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankReconciliationBatch{}
	for rows.Next() {
		var i BankReconciliationBatch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CreatedBy,
			&i.SessionID,
			&i.Status,
			&i.SourceFiles,
			&i.TotalEntries,
			&i.ParseSummary,
			&i.MatchResult,
			&i.AiSuggestions,
			&i.AiExplanations,
			&i.AmountTolerance,
			&i.DateToleranceDays,
			&i.Period,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceiptBatchesByCompany = `-- name: ListReceiptBatchesByCompany :many
SELECT id, company_id, user_id, status, total_images, processed_count, session_id, report_id, report_type, period, results, error_message, created_at, updated_at, transaction_ids FROM receipt_batches WHERE company_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListReceiptBatchesByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListReceiptBatchesByCompany(ctx context.Context, arg ListReceiptBatchesByCompanyParams) ([]ReceiptBatch, error) {
	rows, err := q.db.Query(ctx, listReceiptBatchesByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptBatch{}
	for rows.Next() {
		var i ReceiptBatch
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Status,
			&i.TotalImages,
			&i.ProcessedCount,
			&i.SessionID,
			&i.ReportID,
			&i.ReportType,
			&i.Period,
			&i.Results,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPreferencesByCompany = `-- name: ListUserPreferencesByCompany :many
SELECT id, company_id, report_type, column_mappings, format_rules, auto_fill_rules, updated_at FROM user_preferences
WHERE company_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListUserPreferencesByCompany(ctx context.Context, companyID uuid.UUID) ([]UserPreference, error) {
	rows, err := q.db.Query(ctx, listUserPreferencesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPreference{}
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReportType,
			&i.ColumnMappings,
			&i.FormatRules,
			&i.AutoFillRules,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankReconBatch = `-- name: UpdateBankReconBatch :exec
UPDATE bank_reconciliation_batches SET
    status = COALESCE($2, status),
    parse_summary = $3,
    match_result = $4,
    ai_suggestions = $5,
    ai_explanations = $6,
    total_entries = COALESCE($7, total_entries),
    error_message = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateBankReconBatchParams struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	ParseSummary   []byte    `json:"parse_summary"`
	MatchResult    []byte    `json:"match_result"`
	AiSuggestions  []byte    `json:"ai_suggestions"`
	AiExplanations []byte    `json:"ai_explanations"`
	TotalEntries   int32     `json:"total_entries"`
	ErrorMessage   *string   `json:"error_message"`
}

func (q *Queries) UpdateBankReconBatch(ctx context.Context, arg UpdateBankReconBatchParams) error {
	_, err := q.db.Exec(ctx, updateBankReconBatch,
		arg.ID,
		arg.Status,
		arg.ParseSummary,
		arg.MatchResult,
		arg.AiSuggestions,
		arg.AiExplanations,
		arg.TotalEntries,
		arg.ErrorMessage,
	)
	return err
}

const updateReceiptBatch = `-- name: UpdateReceiptBatch :exec
UPDATE receipt_batches SET
    status = COALESCE($2, status),
    processed_count = COALESCE($3, processed_count),
    results = COALESCE($4, results),
    error_message = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateReceiptBatchParams struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	ProcessedCount int32     `json:"processed_count"`
	Results        []byte    `json:"results"`
	ErrorMessage   *string   `json:"error_message"`
}

func (q *Queries) UpdateReceiptBatch(ctx context.Context, arg UpdateReceiptBatchParams) error {
	_, err := q.db.Exec(ctx, updateReceiptBatch,
		arg.ID,
		arg.Status,
		arg.ProcessedCount,
		arg.Results,
		arg.ErrorMessage,
	)
	return err
}

const upsertFormSchema = `-- name: UpsertFormSchema :exec
INSERT INTO form_schemas (id, form_type, version, name, frequency, is_active, schema_def, calculation_rules, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
ON CONFLICT (form_type) DO UPDATE SET
    version = EXCLUDED.version,
    name = EXCLUDED.name,
    frequency = EXCLUDED.frequency,
    is_active = EXCLUDED.is_active,
    schema_def = EXCLUDED.schema_def,
    calculation_rules = EXCLUDED.calculation_rules,
    updated_at = NOW()
`

type UpsertFormSchemaParams struct {
	ID               uuid.UUID `json:"id"`
	FormType         string    `json:"form_type"`
	Version          int32     `json:"version"`
	Name             string    `json:"name"`
	Frequency        string    `json:"frequency"`
	IsActive         bool      `json:"is_active"`
	SchemaDef        []byte    `json:"schema_def"`
	CalculationRules []byte    `json:"calculation_rules"`
}

func (q *Queries) UpsertFormSchema(ctx context.Context, arg UpsertFormSchemaParams) error {
	_, err := q.db.Exec(ctx, upsertFormSchema,
		arg.ID,
		arg.FormType,
		arg.Version,
		arg.Name,
		arg.Frequency,
		arg.IsActive,
		arg.SchemaDef,
		arg.CalculationRules,
	)
	return err
}

const upsertUserPreference = `-- name: UpsertUserPreference :exec

INSERT INTO user_preferences (id, company_id, report_type, column_mappings, format_rules, auto_fill_rules, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (company_id, report_type) DO UPDATE SET
    column_mappings = EXCLUDED.column_mappings,
    format_rules = EXCLUDED.format_rules,
    auto_fill_rules = EXCLUDED.auto_fill_rules,
    updated_at = NOW()
`

type UpsertUserPreferenceParams struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	ReportType     string    `json:"report_type"`
	ColumnMappings []byte    `json:"column_mappings"`
	FormatRules    []byte    `json:"format_rules"`
	AutoFillRules  []byte    `json:"auto_fill_rules"`
}

// ---- User Preferences ----
func (q *Queries) UpsertUserPreference(ctx context.Context, arg UpsertUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertUserPreference,
		arg.ID,
		arg.CompanyID,
		arg.ReportType,
		arg.ColumnMappings,
		arg.FormatRules,
		arg.AutoFillRules,
	)
	return err
}
