// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type Account struct {
	ID               uuid.UUID   `json:"id"`
	CompanyID        uuid.UUID   `json:"company_id"`
	AccountNumber    string      `json:"account_number"`
	Name             string      `json:"name"`
	AccountType      string      `json:"account_type"`
	SubType          *string     `json:"sub_type"`
	ParentID         pgtype.UUID `json:"parent_id"`
	Description      *string     `json:"description"`
	IsActive         bool        `json:"is_active"`
	IsSystem         bool        `json:"is_system"`
	NormalBalance    string      `json:"normal_balance"`
	QboAccountID     *string     `json:"qbo_account_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	CurrencyCode     *string     `json:"currency_code"`
	DefaultTaxCode   *string     `json:"default_tax_code"`
	CashFlowCategory *string     `json:"cash_flow_category"`
}

type AccountingPeriod struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	Name       string             `json:"name"`
	PeriodType string             `json:"period_type"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	Status     string             `json:"status"`
	ClosedBy   pgtype.UUID        `json:"closed_by"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

type ActionPlan struct {
	ID           uuid.UUID          `json:"id"`
	ThreadID     uuid.UUID          `json:"thread_id"`
	AgentID      string             `json:"agent_id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	UserID       uuid.UUID          `json:"user_id"`
	ToolName     string             `json:"tool_name"`
	ToolArgs     []byte             `json:"tool_args"`
	Summary      string             `json:"summary"`
	Impact       []byte             `json:"impact"`
	Status       string             `json:"status"`
	Result       []byte             `json:"result"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	ConfirmedAt  pgtype.Timestamptz `json:"confirmed_at"`
	ExecutedAt   pgtype.Timestamptz `json:"executed_at"`
}

type AgentActionLog struct {
	ID           uuid.UUID   `json:"id"`
	ThreadID     pgtype.UUID `json:"thread_id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	UserID       uuid.UUID   `json:"user_id"`
	AgentID      string      `json:"agent_id"`
	ActionName   string      `json:"action_name"`
	ActionInput  []byte      `json:"action_input"`
	ActionResult []byte      `json:"action_result"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
}

type AgentThread struct {
	ID           uuid.UUID   `json:"id"`
	CompanyID    uuid.UUID   `json:"company_id"`
	UserID       uuid.UUID   `json:"user_id"`
	AgentID      string      `json:"agent_id"`
	WorkflowType *string     `json:"workflow_type"`
	EntityType   *string     `json:"entity_type"`
	EntityID     pgtype.UUID `json:"entity_id"`
	Title        *string     `json:"title"`
	Status       string      `json:"status"`
	ContextJson  []byte      `json:"context_json"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Anomaly struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	SessionID      uuid.UUID          `json:"session_id"`
	TransactionID  pgtype.UUID        `json:"transaction_id"`
	AnomalyType    string             `json:"anomaly_type"`
	Severity       string             `json:"severity"`
	Description    string             `json:"description"`
	Details        []byte             `json:"details"`
	Status         string             `json:"status"`
	ResolvedBy     pgtype.UUID        `json:"resolved_by"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ResolutionNote *string            `json:"resolution_note"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type AsyncTask struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	Payload      []byte             `json:"payload"`
	Result       []byte             `json:"result"`
	ErrorMessage *string            `json:"error_message"`
	Progress     int32              `json:"progress"`
	CreatedAt    time.Time          `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type AuditLog struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  uuid.UUID   `json:"company_id"`
	UserID     pgtype.UUID `json:"user_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Action     string      `json:"action"`
	Changes    []byte      `json:"changes"`
	Comment    *string     `json:"comment"`
	CreatedAt  time.Time   `json:"created_at"`
	EntryHash  *string     `json:"entry_hash"`
	PrevHash   *string     `json:"prev_hash"`
	IpAddress  *string     `json:"ip_address"`
	UserAgent  *string     `json:"user_agent"`
}

type BankReconciliationBatch struct {
	ID                uuid.UUID      `json:"id"`
	CompanyID         uuid.UUID      `json:"company_id"`
	CreatedBy         uuid.UUID      `json:"created_by"`
	SessionID         pgtype.UUID    `json:"session_id"`
	Status            string         `json:"status"`
	SourceFiles       []byte         `json:"source_files"`
	TotalEntries      int32          `json:"total_entries"`
	ParseSummary      []byte         `json:"parse_summary"`
	MatchResult       []byte         `json:"match_result"`
	AiSuggestions     []byte         `json:"ai_suggestions"`
	AiExplanations    []byte         `json:"ai_explanations"`
	AmountTolerance   pgtype.Numeric `json:"amount_tolerance"`
	DateToleranceDays int32          `json:"date_tolerance_days"`
	Period            string         `json:"period"`
	ErrorMessage      *string        `json:"error_message"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type CasComplianceCheck struct {
	ID                    uuid.UUID   `json:"id"`
	CompanyID             uuid.UUID   `json:"company_id"`
	CheckDate             time.Time   `json:"check_date"`
	OverallPass           bool        `json:"overall_pass"`
	SequentialNumberingOk bool        `json:"sequential_numbering_ok"`
	HashChainIntact       bool        `json:"hash_chain_intact"`
	DoubleEntryBalanced   bool        `json:"double_entry_balanced"`
	PeriodsProperlyClosed bool        `json:"periods_properly_closed"`
	AuditTrailComplete    bool        `json:"audit_trail_complete"`
	SubsidiaryLedgersOk   bool        `json:"subsidiary_ledgers_ok"`
	Details               []byte      `json:"details"`
	CheckedBy             pgtype.UUID `json:"checked_by"`
	CreatedAt             time.Time   `json:"created_at"`
}

type CasSequence struct {
	CompanyID    uuid.UUID `json:"company_id"`
	SequenceType string    `json:"sequence_type"`
	LastNumber   int64     `json:"last_number"`
	Prefix       string    `json:"prefix"`
}

type ChatMessage struct {
	ID                uuid.UUID   `json:"id"`
	CompanyID         uuid.UUID   `json:"company_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Role              string      `json:"role"`
	Content           string      `json:"content"`
	ToolCalls         []byte      `json:"tool_calls"`
	CreatedAt         time.Time   `json:"created_at"`
	ThreadID          pgtype.UUID `json:"thread_id"`
	AgentID           *string     `json:"agent_id"`
	MessageType       *string     `json:"message_type"`
	CitationsJson     []byte      `json:"citations_json"`
	ActionResultsJson []byte      `json:"action_results_json"`
}

type CleaningTemplate struct {
	ID              uuid.UUID `json:"id"`
	CompanyID       uuid.UUID `json:"company_id"`
	SignatureHash   string    `json:"signature_hash"`
	HeaderSignature []byte    `json:"header_signature"`
	AiResult        []byte    `json:"ai_result"`
	HitCount        int32     `json:"hit_count"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Company struct {
	ID                uuid.UUID   `json:"id"`
	OrganizationID    pgtype.UUID `json:"organization_id"`
	CompanyName       string      `json:"company_name"`
	TinNumber         *string     `json:"tin_number"`
	RdoCode           *string     `json:"rdo_code"`
	VatClassification string      `json:"vat_classification"`
	FiscalYearEnd     string      `json:"fiscal_year_end"`
	Industry          *string     `json:"industry"`
	Address           *string     `json:"address"`
	Plan              string      `json:"plan"`
	Settings          []byte      `json:"settings"`
	IsActive          bool        `json:"is_active"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	Jurisdiction      string      `json:"jurisdiction"`
	BaseCurrency      string      `json:"base_currency"`
}

type CompanyApprovalSetting struct {
	ID                       uuid.UUID      `json:"id"`
	CompanyID                uuid.UUID      `json:"company_id"`
	IsEnabled                bool           `json:"is_enabled"`
	AmountThreshold          pgtype.Numeric `json:"amount_threshold"`
	NewVendorReceipts        *int32         `json:"new_vendor_receipts"`
	RiskFlagsRequireApproval bool           `json:"risk_flags_require_approval"`
	ApproverUserID           pgtype.UUID    `json:"approver_user_id"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type CompanyMember struct {
	CompanyID uuid.UUID `json:"company_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	JoinedAt  time.Time `json:"joined_at"`
}

type ComplianceChecklist struct {
	ID           uuid.UUID          `json:"id"`
	FormType     string             `json:"form_type"`
	CheckID      string             `json:"check_id"`
	CheckName    string             `json:"check_name"`
	Severity     string             `json:"severity"`
	Description  *string            `json:"description"`
	RuleRef      *string            `json:"rule_ref"`
	IsActive     *bool              `json:"is_active"`
	SortOrder    *int32             `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Jurisdiction string             `json:"jurisdiction"`
}

type Correction struct {
	ID          uuid.UUID `json:"id"`
	CompanyID   uuid.UUID `json:"company_id"`
	UserID      uuid.UUID `json:"user_id"`
	EntityType  string    `json:"entity_type"`
	EntityID    uuid.UUID `json:"entity_id"`
	FieldName   string    `json:"field_name"`
	OldValue    *string   `json:"old_value"`
	NewValue    string    `json:"new_value"`
	Reason      *string   `json:"reason"`
	ContextData []byte    `json:"context_data"`
	CreatedAt   time.Time `json:"created_at"`
}

type CorrectionHistory struct {
	ID         uuid.UUID `json:"id"`
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
	FieldName  *string   `json:"field_name"`
	OldValue   *string   `json:"old_value"`
	NewValue   *string   `json:"new_value"`
	Reason     *string   `json:"reason"`
	CreatedAt  time.Time `json:"created_at"`
}

type CorrectionRule struct {
	ID                    uuid.UUID      `json:"id"`
	CompanyID             uuid.UUID      `json:"company_id"`
	RuleType              string         `json:"rule_type"`
	MatchCriteria         []byte         `json:"match_criteria"`
	CorrectionField       string         `json:"correction_field"`
	CorrectionValue       string         `json:"correction_value"`
	Confidence            pgtype.Numeric `json:"confidence"`
	SourceCorrectionCount int32          `json:"source_correction_count"`
	IsActive              bool           `json:"is_active"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type ExchangeRate struct {
	ID            uuid.UUID      `json:"id"`
	CompanyID     uuid.UUID      `json:"company_id"`
	FromCurrency  string         `json:"from_currency"`
	ToCurrency    string         `json:"to_currency"`
	Rate          pgtype.Numeric `json:"rate"`
	EffectiveDate pgtype.Date    `json:"effective_date"`
	Source        *string        `json:"source"`
	CreatedAt     time.Time      `json:"created_at"`
}

type ExpenseApprover struct {
	ID             uuid.UUID      `json:"id"`
	CompanyID      uuid.UUID      `json:"company_id"`
	DepartmentName string         `json:"department_name"`
	ApproverUserID uuid.UUID      `json:"approver_user_id"`
	MaxAmount      pgtype.Numeric `json:"max_amount"`
	Priority       int32          `json:"priority"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type ExpenseAuditLog struct {
	ID              uuid.UUID   `json:"id"`
	ExpenseReportID pgtype.UUID `json:"expense_report_id"`
	Action          string      `json:"action"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	ActorType       string      `json:"actor_type"`
	Details         []byte      `json:"details"`
	CreatedAt       time.Time   `json:"created_at"`
}

type ExpenseItem struct {
	ID                   uuid.UUID      `json:"id"`
	ExpenseReportID      uuid.UUID      `json:"expense_report_id"`
	Category             string         `json:"category"`
	Description          string         `json:"description"`
	Amount               pgtype.Numeric `json:"amount"`
	Currency             string         `json:"currency"`
	MerchantName         *string        `json:"merchant_name"`
	TransactionDate      pgtype.Date    `json:"transaction_date"`
	ReceiptUrl           *string        `json:"receipt_url"`
	ReceiptOcrData       []byte         `json:"receipt_ocr_data"`
	AiCategoryConfidence pgtype.Numeric `json:"ai_category_confidence"`
	GlAccountID          pgtype.UUID    `json:"gl_account_id"`
	PolicyID             pgtype.UUID    `json:"policy_id"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type ExpensePolicy struct {
	ID                   uuid.UUID      `json:"id"`
	CompanyID            uuid.UUID      `json:"company_id"`
	Name                 string         `json:"name"`
	Category             string         `json:"category"`
	MaxAmount            pgtype.Numeric `json:"max_amount"`
	RequiresReceiptAbove pgtype.Numeric `json:"requires_receipt_above"`
	AutoApproveBelow     pgtype.Numeric `json:"auto_approve_below"`
	AiAutoApprove        bool           `json:"ai_auto_approve"`
	Description          *string        `json:"description"`
	IsActive             bool           `json:"is_active"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type ExpenseReport struct {
	ID                    uuid.UUID          `json:"id"`
	CompanyID             uuid.UUID          `json:"company_id"`
	SubmitterUserID       uuid.UUID          `json:"submitter_user_id"`
	HrPayeeID             pgtype.UUID        `json:"hr_payee_id"`
	ReportNumber          string             `json:"report_number"`
	Title                 string             `json:"title"`
	Status                string             `json:"status"`
	TotalAmount           pgtype.Numeric     `json:"total_amount"`
	Currency              string             `json:"currency"`
	SubmittedAt           pgtype.Timestamptz `json:"submitted_at"`
	AiReviewedAt          pgtype.Timestamptz `json:"ai_reviewed_at"`
	AiRiskScore           *int32             `json:"ai_risk_score"`
	AiDecision            *string            `json:"ai_decision"`
	AiDecisionReason      *string            `json:"ai_decision_reason"`
	ApproverUserID        pgtype.UUID        `json:"approver_user_id"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	RejectionReason       *string            `json:"rejection_reason"`
	ReviewerUserID        pgtype.UUID        `json:"reviewer_user_id"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	PaymentReference      *string            `json:"payment_reference"`
	AccrualJournalEntryID pgtype.UUID        `json:"accrual_journal_entry_id"`
	PaymentJournalEntryID pgtype.UUID        `json:"payment_journal_entry_id"`
	Notes                 *string            `json:"notes"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
}

type FormSchema struct {
	ID               uuid.UUID `json:"id"`
	FormType         string    `json:"form_type"`
	Version          int32     `json:"version"`
	Name             string    `json:"name"`
	Frequency        string    `json:"frequency"`
	IsActive         bool      `json:"is_active"`
	SchemaDef        []byte    `json:"schema_def"`
	CalculationRules []byte    `json:"calculation_rules"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	Jurisdiction     string    `json:"jurisdiction"`
}

type GlMappingRule struct {
	ID              uuid.UUID   `json:"id"`
	CompanyID       uuid.UUID   `json:"company_id"`
	Jurisdiction    string      `json:"jurisdiction"`
	SourceDimension string      `json:"source_dimension"`
	SourceValue     string      `json:"source_value"`
	TargetAccountID uuid.UUID   `json:"target_account_id"`
	DebitCredit     string      `json:"debit_credit"`
	Priority        int32       `json:"priority"`
	EffectiveFrom   pgtype.Date `json:"effective_from"`
	EffectiveTo     pgtype.Date `json:"effective_to"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type HrPayee struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	HrEmployeeID   int64     `json:"hr_employee_id"`
	HrEmployeeNo   string    `json:"hr_employee_no"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          *string   `json:"email"`
	Tin            *string   `json:"tin"`
	Sss            *string   `json:"sss"`
	Philhealth     *string   `json:"philhealth"`
	Pagibig        *string   `json:"pagibig"`
	DepartmentName *string   `json:"department_name"`
	PositionTitle  *string   `json:"position_title"`
	Jurisdiction   string    `json:"jurisdiction"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type IntegrationEventInbox struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	SourceSystem string             `json:"source_system"`
	EventID      string             `json:"event_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	ErrorMessage *string            `json:"error_message"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type IntegrationSource struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	SourceSystem    string             `json:"source_system"`
	RemoteCompanyID string             `json:"remote_company_id"`
	ApiKeyHash      string             `json:"api_key_hash"`
	WebhookSecret   string             `json:"webhook_secret"`
	Status          string             `json:"status"`
	LastEventAt     pgtype.Timestamptz `json:"last_event_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type Invoice struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	InvoiceNumber   string             `json:"invoice_number"`
	InvoiceType     string             `json:"invoice_type"`
	Status          string             `json:"status"`
	CustomerName    string             `json:"customer_name"`
	CustomerTin     *string            `json:"customer_tin"`
	CustomerAddress *string            `json:"customer_address"`
	InvoiceDate     pgtype.Date        `json:"invoice_date"`
	DueDate         pgtype.Date        `json:"due_date"`
	Subtotal        pgtype.Numeric     `json:"subtotal"`
	VatAmount       pgtype.Numeric     `json:"vat_amount"`
	DiscountAmount  pgtype.Numeric     `json:"discount_amount"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	VatableSales    pgtype.Numeric     `json:"vatable_sales"`
	VatExemptSales  pgtype.Numeric     `json:"vat_exempt_sales"`
	ZeroRatedSales  pgtype.Numeric     `json:"zero_rated_sales"`
	EisSubmissionID *string            `json:"eis_submission_id"`
	EisStatus       *string            `json:"eis_status"`
	EisSubmittedAt  pgtype.Timestamptz `json:"eis_submitted_at"`
	EisResponse     []byte             `json:"eis_response"`
	ReferenceNumber *string            `json:"reference_number"`
	Notes           *string            `json:"notes"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type InvoiceItem struct {
	ID          uuid.UUID      `json:"id"`
	InvoiceID   uuid.UUID      `json:"invoice_id"`
	LineNumber  int32          `json:"line_number"`
	Description string         `json:"description"`
	Quantity    pgtype.Numeric `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	Amount      pgtype.Numeric `json:"amount"`
	VatType     string         `json:"vat_type"`
	VatRate     pgtype.Numeric `json:"vat_rate"`
	VatAmount   pgtype.Numeric `json:"vat_amount"`
	Discount    pgtype.Numeric `json:"discount"`
	AtcCode     *string        `json:"atc_code"`
	CreatedAt   time.Time      `json:"created_at"`
}

type JournalEntry struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	PeriodID     pgtype.UUID        `json:"period_id"`
	EntryNumber  *int32             `json:"entry_number"`
	EntryDate    pgtype.Date        `json:"entry_date"`
	Reference    *string            `json:"reference"`
	Description  *string            `json:"description"`
	SourceType   *string            `json:"source_type"`
	SourceID     pgtype.UUID        `json:"source_id"`
	Status       string             `json:"status"`
	PostedBy     pgtype.UUID        `json:"posted_by"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
	ReversedByID pgtype.UUID        `json:"reversed_by_id"`
	ReversesID   pgtype.UUID        `json:"reverses_id"`
	Memo         *string            `json:"memo"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
	CurrencyCode *string            `json:"currency_code"`
	// Per-company sequential number, gap-free, for BIR CAS compliance
	CompanySeqNo *int64 `json:"company_seq_no"`
	// SHA-256 hash of entry data for tamper detection
	EntryHash *string `json:"entry_hash"`
	// Hash of the previous entry in the chain (per company)
	PrevHash *string `json:"prev_hash"`
	// BIR journal classification: sales_journal, purchases_journal, cash_receipts, cash_disbursements, general_journal
	JournalBook *string `json:"journal_book"`
}

type JournalLine struct {
	ID             uuid.UUID      `json:"id"`
	JournalEntryID uuid.UUID      `json:"journal_entry_id"`
	AccountID      uuid.UUID      `json:"account_id"`
	LineNumber     int32          `json:"line_number"`
	Description    *string        `json:"description"`
	Debit          pgtype.Numeric `json:"debit"`
	Credit         pgtype.Numeric `json:"credit"`
	CurrencyCode   *string        `json:"currency_code"`
	ExchangeRate   pgtype.Numeric `json:"exchange_rate"`
	HomeDebit      pgtype.Numeric `json:"home_debit"`
	HomeCredit     pgtype.Numeric `json:"home_credit"`
	TaxCode        *string        `json:"tax_code"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
}

type KnowledgeChunk struct {
	ID            uuid.UUID        `json:"id"`
	Source        *string          `json:"source"`
	Category      *string          `json:"category"`
	Content       string           `json:"content"`
	Embedding     *pgvector.Vector `json:"embedding"`
	Metadata      []byte           `json:"metadata"`
	CreatedAt     time.Time        `json:"created_at"`
	SectionRef    *string          `json:"section_ref"`
	LawRef        *string          `json:"law_ref"`
	EffectiveDate pgtype.Date      `json:"effective_date"`
	ChunkType     *string          `json:"chunk_type"`
	Jurisdiction  string           `json:"jurisdiction"`
}

type LinkToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CompanyID uuid.UUID `json:"company_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID               uuid.UUID          `json:"id"`
	CompanyID        uuid.UUID          `json:"company_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	NotificationType string             `json:"notification_type"`
	Title            string             `json:"title"`
	Message          string             `json:"message"`
	Metadata         []byte             `json:"metadata"`
	IsRead           bool               `json:"is_read"`
	CreatedAt        time.Time          `json:"created_at"`
	ReadAt           pgtype.Timestamptz `json:"read_at"`
	DedupKey         *string            `json:"dedup_key"`
}

type OrgMember struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	JoinedAt       time.Time `json:"joined_at"`
}

type Organization struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	Plan         string    `json:"plan"`
	MaxCompanies int32     `json:"max_companies"`
	MaxUsers     int32     `json:"max_users"`
	Settings     []byte    `json:"settings"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type QboConnection struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	RealmID         string             `json:"realm_id"`
	AccessTokenEnc  []byte             `json:"access_token_enc"`
	RefreshTokenEnc []byte             `json:"refresh_token_enc"`
	TokenExpiry     time.Time          `json:"token_expiry"`
	RefreshExpiry   time.Time          `json:"refresh_expiry"`
	Scope           *string            `json:"scope"`
	IsActive        bool               `json:"is_active"`
	LastSyncAt      pgtype.Timestamptz `json:"last_sync_at"`
	LastSyncStatus  *string            `json:"last_sync_status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type QboSyncLog struct {
	ID            uuid.UUID          `json:"id"`
	ConnectionID  uuid.UUID          `json:"connection_id"`
	CompanyID     uuid.UUID          `json:"company_id"`
	EntityType    string             `json:"entity_type"`
	SyncType      string             `json:"sync_type"`
	SyncDirection string             `json:"sync_direction"`
	StartedAt     time.Time          `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	RecordsSynced int32              `json:"records_synced"`
	RecordsFailed int32              `json:"records_failed"`
	ErrorDetails  []byte             `json:"error_details"`
	Status        string             `json:"status"`
}

type ReceiptApproval struct {
	ID            uuid.UUID   `json:"id"`
	BatchID       uuid.UUID   `json:"batch_id"`
	CompanyID     uuid.UUID   `json:"company_id"`
	Status        string      `json:"status"`
	TriggerReason string      `json:"trigger_reason"`
	RequestedBy   pgtype.UUID `json:"requested_by"`
	ApprovedBy    pgtype.UUID `json:"approved_by"`
	Notes         *string     `json:"notes"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type ReceiptBatch struct {
	ID             uuid.UUID   `json:"id"`
	CompanyID      uuid.UUID   `json:"company_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Status         string      `json:"status"`
	TotalImages    int32       `json:"total_images"`
	ProcessedCount int32       `json:"processed_count"`
	SessionID      pgtype.UUID `json:"session_id"`
	ReportID       pgtype.UUID `json:"report_id"`
	ReportType     string      `json:"report_type"`
	Period         string      `json:"period"`
	Results        []byte      `json:"results"`
	ErrorMessage   *string     `json:"error_message"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	TransactionIds []uuid.UUID `json:"transaction_ids"`
	ImagePath      *string     `json:"image_path"`
	ImageHash      *string     `json:"image_hash"`
	ApprovalStatus *string     `json:"approval_status"`
}

type ReconciliationSession struct {
	ID                   uuid.UUID          `json:"id"`
	CompanyID            uuid.UUID          `json:"company_id"`
	CreatedBy            uuid.UUID          `json:"created_by"`
	Period               string             `json:"period"`
	Status               string             `json:"status"`
	ReportID             pgtype.UUID        `json:"report_id"`
	SourceFiles          []byte             `json:"source_files"`
	Summary              []byte             `json:"summary"`
	ReconciliationResult []byte             `json:"reconciliation_result"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	OpeningBalance       pgtype.Numeric     `json:"opening_balance"`
	ClosingBalance       pgtype.Numeric     `json:"closing_balance"`
	BankClosingBalance   pgtype.Numeric     `json:"bank_closing_balance"`
}

type Report struct {
	ID                     uuid.UUID          `json:"id"`
	CompanyID              uuid.UUID          `json:"company_id"`
	ReportType             string             `json:"report_type"`
	Period                 string             `json:"period"`
	Status                 string             `json:"status"`
	InputData              []byte             `json:"input_data"`
	CalculatedData         []byte             `json:"calculated_data"`
	FilePath               *string            `json:"file_path"`
	CreatedAt              time.Time          `json:"created_at"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Version                int32              `json:"version"`
	Overrides              []byte             `json:"overrides"`
	OriginalCalculatedData []byte             `json:"original_calculated_data"`
	Notes                  *string            `json:"notes"`
	ComplianceScore        *int32             `json:"compliance_score"`
	AmendmentNumber        int32              `json:"amendment_number"`
	OriginalReportID       pgtype.UUID        `json:"original_report_id"`
}

type ReportApproval struct {
	ID         uuid.UUID `json:"id"`
	ReportID   uuid.UUID `json:"report_id"`
	UserID     uuid.UUID `json:"user_id"`
	FromStatus string    `json:"from_status"`
	ToStatus   string    `json:"to_status"`
	Action     string    `json:"action"`
	Comment    *string   `json:"comment"`
	CreatedAt  time.Time `json:"created_at"`
}

type RevokedToken struct {
	ID        uuid.UUID `json:"id"`
	Jti       string    `json:"jti"`
	UserID    uuid.UUID `json:"user_id"`
	RevokedAt time.Time `json:"revoked_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	IsProject bool      `json:"is_project"`
}

type TaxCode struct {
	ID               uuid.UUID      `json:"id"`
	CompanyID        uuid.UUID      `json:"company_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	TaxType          string         `json:"tax_type"`
	Rate             pgtype.Numeric `json:"rate"`
	IsInclusive      bool           `json:"is_inclusive"`
	AffectsAccountID pgtype.UUID    `json:"affects_account_id"`
	Jurisdiction     string         `json:"jurisdiction"`
	IsActive         bool           `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type TaxDraft struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	FormType    string             `json:"form_type"`
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	Result      []byte             `json:"result"`
	TriggeredBy *string            `json:"triggered_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TaxRule struct {
	ID            uuid.UUID          `json:"id"`
	RuleType      string             `json:"rule_type"`
	RuleKey       string             `json:"rule_key"`
	Value         []byte             `json:"value"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	SourceRef     *string            `json:"source_ref"`
	Description   *string            `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Jurisdiction  string             `json:"jurisdiction"`
}

type TelegramUser struct {
	TelegramID int64     `json:"telegram_id"`
	UserID     uuid.UUID `json:"user_id"`
	CompanyID  uuid.UUID `json:"company_id"`
	ChatID     int64     `json:"chat_id"`
	Username   *string   `json:"username"`
	FullName   *string   `json:"full_name"`
	CreatedAt  time.Time `json:"created_at"`
}

type Transaction struct {
	ID                   uuid.UUID      `json:"id"`
	CompanyID            uuid.UUID      `json:"company_id"`
	SessionID            uuid.UUID      `json:"session_id"`
	SourceType           string         `json:"source_type"`
	SourceFileID         string         `json:"source_file_id"`
	RowIndex             int32          `json:"row_index"`
	Date                 pgtype.Date    `json:"date"`
	Description          *string        `json:"description"`
	Amount               pgtype.Numeric `json:"amount"`
	VatAmount            pgtype.Numeric `json:"vat_amount"`
	VatType              string         `json:"vat_type"`
	Category             string         `json:"category"`
	Tin                  *string        `json:"tin"`
	Confidence           pgtype.Numeric `json:"confidence"`
	ClassificationSource string         `json:"classification_source"`
	RawData              []byte         `json:"raw_data"`
	MatchGroupID         pgtype.UUID    `json:"match_group_id"`
	MatchStatus          string         `json:"match_status"`
	EwtRate              pgtype.Numeric `json:"ewt_rate"`
	EwtAmount            pgtype.Numeric `json:"ewt_amount"`
	AtcCode              *string        `json:"atc_code"`
	VendorID             pgtype.UUID    `json:"vendor_id"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	JournalEntryID       pgtype.UUID    `json:"journal_entry_id"`
	ProjectTag           *string        `json:"project_tag"`
	FromCurrency         *string        `json:"from_currency"`
	ToCurrency           *string        `json:"to_currency"`
	ExchangeRate         pgtype.Numeric `json:"exchange_rate"`
	FromAmount           pgtype.Numeric `json:"from_amount"`
	SubmittedBy          pgtype.UUID    `json:"submitted_by"`
	RefNumber            *int32         `json:"ref_number"`
	AccountCode          *string        `json:"account_code"`
	TaxCode              *string        `json:"tax_code"`
	Department           *string        `json:"department"`
	Project              *string        `json:"project"`
}

type TransactionTag struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	TagID         uuid.UUID `json:"tag_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type User struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	CreatedAt        time.Time `json:"created_at"`
	TelegramUsername *string   `json:"telegram_username"`
}

type UserPreference struct {
	ID             uuid.UUID `json:"id"`
	CompanyID      uuid.UUID `json:"company_id"`
	ReportType     string    `json:"report_type"`
	ColumnMappings []byte    `json:"column_mappings"`
	FormatRules    []byte    `json:"format_rules"`
	AutoFillRules  []byte    `json:"auto_fill_rules"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ValidationResult struct {
	ID           uuid.UUID `json:"id"`
	ReportID     uuid.UUID `json:"report_id"`
	CompanyID    uuid.UUID `json:"company_id"`
	OverallScore int32     `json:"overall_score"`
	CheckResults []byte    `json:"check_results"`
	RagFindings  []byte    `json:"rag_findings"`
	ValidatedAt  time.Time `json:"validated_at"`
}

type Vendor struct {
	ID               uuid.UUID      `json:"id"`
	CompanyID        uuid.UUID      `json:"company_id"`
	Tin              string         `json:"tin"`
	Name             string         `json:"name"`
	Address          *string        `json:"address"`
	VendorType       string         `json:"vendor_type"`
	DefaultEwtRate   pgtype.Numeric `json:"default_ewt_rate"`
	DefaultAtcCode   *string        `json:"default_atc_code"`
	IsVatRegistered  bool           `json:"is_vat_registered"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	Email            *string        `json:"email"`
	Phone            *string        `json:"phone"`
	PaymentTermsDays *int32         `json:"payment_terms_days"`
	CurrencyCode     *string        `json:"currency_code"`
	DefaultAccountID pgtype.UUID    `json:"default_account_id"`
	IsActive         bool           `json:"is_active"`
	Notes            *string        `json:"notes"`
}

type VendorPostingPolicy struct {
	ID                 uuid.UUID          `json:"id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	VendorNormalized   string             `json:"vendor_normalized"`
	Aliases            []byte             `json:"aliases"`
	DefaultCategory    *string            `json:"default_category"`
	DefaultAccountCode *string            `json:"default_account_code"`
	DefaultTaxCode     *string            `json:"default_tax_code"`
	DefaultDepartment  *string            `json:"default_department"`
	DefaultProject     *string            `json:"default_project"`
	UsageCount         int32              `json:"usage_count"`
	AcceptCount        int32              `json:"accept_count"`
	CorrectionCount    int32              `json:"correction_count"`
	ConfidenceScore    pgtype.Numeric     `json:"confidence_score"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type WithholdingCertificate struct {
	ID           uuid.UUID      `json:"id"`
	CompanyID    uuid.UUID      `json:"company_id"`
	SessionID    pgtype.UUID    `json:"session_id"`
	VendorID     uuid.UUID      `json:"vendor_id"`
	Period       string         `json:"period"`
	Quarter      string         `json:"quarter"`
	AtcCode      string         `json:"atc_code"`
	IncomeType   string         `json:"income_type"`
	IncomeAmount pgtype.Numeric `json:"income_amount"`
	EwtRate      pgtype.Numeric `json:"ewt_rate"`
	TaxWithheld  pgtype.Numeric `json:"tax_withheld"`
	Status       string         `json:"status"`
	FilePath     *string        `json:"file_path"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
