// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_dashboard.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgMembers = `-- name: CountOrgMembers :one
SELECT COUNT(*) FROM org_members WHERE organization_id = $1
`

func (q *Queries) CountOrgMembers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrgCompanyIDs = `-- name: GetOrgCompanyIDs :many
SELECT id FROM companies
WHERE organization_id = $1 AND is_active = true
`

func (q *Queries) GetOrgCompanyIDs(ctx context.Context, organizationID pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getOrgCompanyIDs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgCompanySummaries = `-- name: GetOrgCompanySummaries :many
SELECT
    c.id,
    c.company_name,
    c.tin_number,
    c.jurisdiction,
    c.plan,
    c.is_active,
    c.created_at,
    COALESCE(r.report_count, 0)::bigint AS report_count,
    COALESCE(r.draft_count, 0)::bigint AS draft_count,
    COALESCE(v.vendor_count, 0)::bigint AS vendor_count,
    cas.last_check_at,
    cas.overall_pass
FROM companies c
LEFT JOIN LATERAL (
    SELECT
        COUNT(*) AS report_count,
        COUNT(*) FILTER (WHERE status = 'draft') AS draft_count
    FROM reports WHERE company_id = c.id
) r ON true
LEFT JOIN LATERAL (
    SELECT COUNT(*) AS vendor_count
    FROM vendors WHERE company_id = c.id
) v ON true
LEFT JOIN LATERAL (
    SELECT check_date AS last_check_at, overall_pass
    FROM cas_compliance_checks
    WHERE company_id = c.id
    ORDER BY check_date DESC
    LIMIT 1
) cas ON true
WHERE c.organization_id = $1 AND c.is_active = true
ORDER BY c.company_name
`

type GetOrgCompanySummariesRow struct {
	ID           uuid.UUID `json:"id"`
	CompanyName  string    `json:"company_name"`
	TinNumber    *string   `json:"tin_number"`
	Jurisdiction string    `json:"jurisdiction"`
	Plan         string    `json:"plan"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	ReportCount  int64     `json:"report_count"`
	DraftCount   int64     `json:"draft_count"`
	VendorCount  int64     `json:"vendor_count"`
	LastCheckAt  time.Time `json:"last_check_at"`
	OverallPass  bool      `json:"overall_pass"`
}

func (q *Queries) GetOrgCompanySummaries(ctx context.Context, organizationID pgtype.UUID) ([]GetOrgCompanySummariesRow, error) {
	rows, err := q.db.Query(ctx, getOrgCompanySummaries, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrgCompanySummariesRow{}
	for rows.Next() {
		var i GetOrgCompanySummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.TinNumber,
			&i.Jurisdiction,
			&i.Plan,
			&i.IsActive,
			&i.CreatedAt,
			&i.ReportCount,
			&i.DraftCount,
			&i.VendorCount,
			&i.LastCheckAt,
			&i.OverallPass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
