// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addOrgMember = `-- name: AddOrgMember :exec
INSERT INTO org_members (organization_id, user_id, role, joined_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (organization_id, user_id) DO NOTHING
`

type AddOrgMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const countOrganizationsByUser = `-- name: CountOrganizationsByUser :one
SELECT COUNT(*) FROM organizations o
JOIN org_members om ON o.id = om.organization_id
WHERE om.user_id = $1 AND o.is_active = true
`

func (q *Queries) CountOrganizationsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug, plan, max_companies, max_users, settings, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, name, slug, plan, max_companies, max_users, settings, is_active, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	Plan         string    `json:"plan"`
	MaxCompanies int32     `json:"max_companies"`
	MaxUsers     int32     `json:"max_users"`
	Settings     []byte    `json:"settings"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.MaxCompanies,
		arg.MaxUsers,
		arg.Settings,
		arg.IsActive,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxCompanies,
		&i.MaxUsers,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgMemberRole = `-- name: GetOrgMemberRole :one
SELECT role FROM org_members WHERE organization_id = $1 AND user_id = $2
`

type GetOrgMemberRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMemberRole(ctx context.Context, arg GetOrgMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getOrgMemberRole, arg.OrganizationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, plan, max_companies, max_users, settings, is_active, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxCompanies,
		&i.MaxUsers,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, plan, max_companies, max_users, settings, is_active, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.MaxCompanies,
		&i.MaxUsers,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.organization_id, om.user_id, om.role, om.joined_at, u.email, u.full_name
FROM org_members om
JOIN users u ON om.user_id = u.id
WHERE om.organization_id = $1
ORDER BY om.joined_at
`

type ListOrgMembersRow struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	JoinedAt       time.Time `json:"joined_at"`
	Email          string    `json:"email"`
	FullName       *string   `json:"full_name"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByUser = `-- name: ListOrganizationsByUser :many
SELECT o.id, o.name, o.slug, o.plan, o.max_companies, o.max_users, o.settings, o.is_active, o.created_at, o.updated_at FROM organizations o
JOIN org_members om ON o.id = om.organization_id
WHERE om.user_id = $1 AND o.is_active = true
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListOrganizationsByUser(ctx context.Context, arg ListOrganizationsByUserParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.MaxCompanies,
			&i.MaxUsers,
			&i.Settings,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members WHERE organization_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrgMember, arg.OrganizationID, arg.UserID)
	return err
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :exec
UPDATE org_members SET role = $3 WHERE organization_id = $1 AND user_id = $2
`

type UpdateOrgMemberRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateOrgMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations SET
    name = $2,
    slug = $3,
    plan = $4,
    max_companies = $5,
    max_users = $6,
    settings = $7,
    is_active = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOrganizationParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	Plan         string    `json:"plan"`
	MaxCompanies int32     `json:"max_companies"`
	MaxUsers     int32     `json:"max_users"`
	Settings     []byte    `json:"settings"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.MaxCompanies,
		arg.MaxUsers,
		arg.Settings,
		arg.IsActive,
	)
	return err
}
