// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reconciliation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReconciliationSessionsByCompany = `-- name: CountReconciliationSessionsByCompany :one
SELECT COUNT(*) FROM reconciliation_sessions WHERE company_id = $1
`

func (q *Queries) CountReconciliationSessionsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReconciliationSessionsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReconciliationSession = `-- name: CreateReconciliationSession :one
INSERT INTO reconciliation_sessions (id, company_id, created_by, period, status, report_id, source_files, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, company_id, created_by, period, status, report_id, source_files, summary, reconciliation_result, completed_at, created_at, updated_at
`

type CreateReconciliationSessionParams struct {
	ID          uuid.UUID   `json:"id"`
	CompanyID   uuid.UUID   `json:"company_id"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	Period      string      `json:"period"`
	Status      string      `json:"status"`
	ReportID    pgtype.UUID `json:"report_id"`
	SourceFiles []byte      `json:"source_files"`
}

func (q *Queries) CreateReconciliationSession(ctx context.Context, arg CreateReconciliationSessionParams) (ReconciliationSession, error) {
	row := q.db.QueryRow(ctx, createReconciliationSession,
		arg.ID,
		arg.CompanyID,
		arg.CreatedBy,
		arg.Period,
		arg.Status,
		arg.ReportID,
		arg.SourceFiles,
	)
	var i ReconciliationSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.Period,
		&i.Status,
		&i.ReportID,
		&i.SourceFiles,
		&i.Summary,
		&i.ReconciliationResult,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReconciliationSessionByID = `-- name: GetReconciliationSessionByID :one
SELECT id, company_id, created_by, period, status, report_id, source_files, summary, reconciliation_result, completed_at, created_at, updated_at FROM reconciliation_sessions WHERE id = $1
`

func (q *Queries) GetReconciliationSessionByID(ctx context.Context, id uuid.UUID) (ReconciliationSession, error) {
	row := q.db.QueryRow(ctx, getReconciliationSessionByID, id)
	var i ReconciliationSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.Period,
		&i.Status,
		&i.ReportID,
		&i.SourceFiles,
		&i.Summary,
		&i.ReconciliationResult,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReconciliationSessionsByCompany = `-- name: ListReconciliationSessionsByCompany :many
SELECT id, company_id, created_by, period, status, report_id, source_files, summary, reconciliation_result, completed_at, created_at, updated_at FROM reconciliation_sessions
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReconciliationSessionsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListReconciliationSessionsByCompany(ctx context.Context, arg ListReconciliationSessionsByCompanyParams) ([]ReconciliationSession, error) {
	rows, err := q.db.Query(ctx, listReconciliationSessionsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconciliationSession{}
	for rows.Next() {
		var i ReconciliationSession
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CreatedBy,
			&i.Period,
			&i.Status,
			&i.ReportID,
			&i.SourceFiles,
			&i.Summary,
			&i.ReconciliationResult,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReconciliationSession = `-- name: UpdateReconciliationSession :exec
UPDATE reconciliation_sessions SET
    status = COALESCE($2, status),
    report_id = $3,
    source_files = COALESCE($4, source_files),
    summary = $5,
    reconciliation_result = $6,
    completed_at = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateReconciliationSessionParams struct {
	ID                   uuid.UUID          `json:"id"`
	Status               string             `json:"status"`
	ReportID             pgtype.UUID        `json:"report_id"`
	SourceFiles          []byte             `json:"source_files"`
	Summary              []byte             `json:"summary"`
	ReconciliationResult []byte             `json:"reconciliation_result"`
	CompletedAt          pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateReconciliationSession(ctx context.Context, arg UpdateReconciliationSessionParams) error {
	_, err := q.db.Exec(ctx, updateReconciliationSession,
		arg.ID,
		arg.Status,
		arg.ReportID,
		arg.SourceFiles,
		arg.Summary,
		arg.ReconciliationResult,
		arg.CompletedAt,
	)
	return err
}
