// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_approvals.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countReportApprovals = `-- name: CountReportApprovals :one
SELECT COUNT(*) FROM report_approvals WHERE report_id = $1
`

func (q *Queries) CountReportApprovals(ctx context.Context, reportID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReportApprovals, reportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReportApproval = `-- name: CreateReportApproval :one
INSERT INTO report_approvals (id, report_id, user_id, from_status, to_status, action, comment)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, report_id, user_id, from_status, to_status, action, comment, created_at
`

type CreateReportApprovalParams struct {
	ID         uuid.UUID `json:"id"`
	ReportID   uuid.UUID `json:"report_id"`
	UserID     uuid.UUID `json:"user_id"`
	FromStatus string    `json:"from_status"`
	ToStatus   string    `json:"to_status"`
	Action     string    `json:"action"`
	Comment    *string   `json:"comment"`
}

func (q *Queries) CreateReportApproval(ctx context.Context, arg CreateReportApprovalParams) (ReportApproval, error) {
	row := q.db.QueryRow(ctx, createReportApproval,
		arg.ID,
		arg.ReportID,
		arg.UserID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Action,
		arg.Comment,
	)
	var i ReportApproval
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.UserID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Action,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listReportApprovals = `-- name: ListReportApprovals :many
SELECT ra.id, ra.report_id, ra.user_id, ra.from_status, ra.to_status, ra.action, ra.comment, ra.created_at, u.full_name AS user_name, u.email AS user_email
FROM report_approvals ra
JOIN users u ON ra.user_id = u.id
WHERE ra.report_id = $1
ORDER BY ra.created_at DESC
`

type ListReportApprovalsRow struct {
	ID         uuid.UUID `json:"id"`
	ReportID   uuid.UUID `json:"report_id"`
	UserID     uuid.UUID `json:"user_id"`
	FromStatus string    `json:"from_status"`
	ToStatus   string    `json:"to_status"`
	Action     string    `json:"action"`
	Comment    *string   `json:"comment"`
	CreatedAt  time.Time `json:"created_at"`
	UserName   *string   `json:"user_name"`
	UserEmail  string    `json:"user_email"`
}

func (q *Queries) ListReportApprovals(ctx context.Context, reportID uuid.UUID) ([]ListReportApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listReportApprovals, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportApprovalsRow{}
	for rows.Next() {
		var i ListReportApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.UserID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Action,
			&i.Comment,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
