// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveDuplicateReports = `-- name: ArchiveDuplicateReports :exec
UPDATE reports SET status = 'archived', updated_at = NOW()
WHERE company_id = $1
  AND report_type = $2
  AND period = $3
  AND id != $4
  AND status IN ('draft', 'rejected')
`

type ArchiveDuplicateReportsParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
	Period     string    `json:"period"`
	ID         uuid.UUID `json:"id"`
}

// Archives all draft/rejected reports for the same company+type+period except the given report ID.
func (q *Queries) ArchiveDuplicateReports(ctx context.Context, arg ArchiveDuplicateReportsParams) error {
	_, err := q.db.Exec(ctx, archiveDuplicateReports,
		arg.CompanyID,
		arg.ReportType,
		arg.Period,
		arg.ID,
	)
	return err
}

const countReportsByCompany = `-- name: CountReportsByCompany :one
SELECT COUNT(*) FROM reports WHERE company_id = $1
`

func (q *Queries) CountReportsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReportsByCompanyAndType = `-- name: CountReportsByCompanyAndType :one
SELECT COUNT(*) FROM reports WHERE company_id = $1 AND report_type = $2
`

type CountReportsByCompanyAndTypeParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
}

func (q *Queries) CountReportsByCompanyAndType(ctx context.Context, arg CountReportsByCompanyAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByCompanyAndType, arg.CompanyID, arg.ReportType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, created_by, version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), $9, 1)
RETURNING id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, confirmed_at, created_by, updated_by, updated_at, version, overrides, original_calculated_data, notes, compliance_score, amendment_number, original_report_id
`

type CreateReportParams struct {
	ID             uuid.UUID   `json:"id"`
	CompanyID      uuid.UUID   `json:"company_id"`
	ReportType     string      `json:"report_type"`
	Period         string      `json:"period"`
	Status         string      `json:"status"`
	InputData      []byte      `json:"input_data"`
	CalculatedData []byte      `json:"calculated_data"`
	FilePath       *string     `json:"file_path"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.CompanyID,
		arg.ReportType,
		arg.Period,
		arg.Status,
		arg.InputData,
		arg.CalculatedData,
		arg.FilePath,
		arg.CreatedBy,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReportType,
		&i.Period,
		&i.Status,
		&i.InputData,
		&i.CalculatedData,
		&i.FilePath,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Version,
		&i.Overrides,
		&i.OriginalCalculatedData,
		&i.Notes,
		&i.ComplianceScore,
		&i.AmendmentNumber,
		&i.OriginalReportID,
	)
	return i, err
}

const createReportWithAmendment = `-- name: CreateReportWithAmendment :one
INSERT INTO reports (id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, created_by, version, amendment_number, original_report_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), $9, 1, $10, $11)
RETURNING id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, confirmed_at, created_by, updated_by, updated_at, version, overrides, original_calculated_data, notes, compliance_score, amendment_number, original_report_id
`

type CreateReportWithAmendmentParams struct {
	ID               uuid.UUID   `json:"id"`
	CompanyID        uuid.UUID   `json:"company_id"`
	ReportType       string      `json:"report_type"`
	Period           string      `json:"period"`
	Status           string      `json:"status"`
	InputData        []byte      `json:"input_data"`
	CalculatedData   []byte      `json:"calculated_data"`
	FilePath         *string     `json:"file_path"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	AmendmentNumber  int32       `json:"amendment_number"`
	OriginalReportID pgtype.UUID `json:"original_report_id"`
}

func (q *Queries) CreateReportWithAmendment(ctx context.Context, arg CreateReportWithAmendmentParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReportWithAmendment,
		arg.ID,
		arg.CompanyID,
		arg.ReportType,
		arg.Period,
		arg.Status,
		arg.InputData,
		arg.CalculatedData,
		arg.FilePath,
		arg.CreatedBy,
		arg.AmendmentNumber,
		arg.OriginalReportID,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReportType,
		&i.Period,
		&i.Status,
		&i.InputData,
		&i.CalculatedData,
		&i.FilePath,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Version,
		&i.Overrides,
		&i.OriginalCalculatedData,
		&i.Notes,
		&i.ComplianceScore,
		&i.AmendmentNumber,
		&i.OriginalReportID,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getMaxAmendmentNumber = `-- name: GetMaxAmendmentNumber :one
SELECT COALESCE(MAX(amendment_number), 0)::int AS max_amendment
FROM reports
WHERE original_report_id = $1 OR id = $1
`

func (q *Queries) GetMaxAmendmentNumber(ctx context.Context, originalReportID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxAmendmentNumber, originalReportID)
	var max_amendment int32
	err := row.Scan(&max_amendment)
	return max_amendment, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, confirmed_at, created_by, updated_by, updated_at, version, overrides, original_calculated_data, notes, compliance_score, amendment_number, original_report_id FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReportType,
		&i.Period,
		&i.Status,
		&i.InputData,
		&i.CalculatedData,
		&i.FilePath,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Version,
		&i.Overrides,
		&i.OriginalCalculatedData,
		&i.Notes,
		&i.ComplianceScore,
		&i.AmendmentNumber,
		&i.OriginalReportID,
	)
	return i, err
}

const listAmendmentChain = `-- name: ListAmendmentChain :many
SELECT id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, confirmed_at, created_by, updated_by, updated_at, version, overrides, original_calculated_data, notes, compliance_score, amendment_number, original_report_id FROM reports
WHERE (id = $1 OR original_report_id = $1)
ORDER BY amendment_number ASC
`

func (q *Queries) ListAmendmentChain(ctx context.Context, id uuid.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listAmendmentChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReportType,
			&i.Period,
			&i.Status,
			&i.InputData,
			&i.CalculatedData,
			&i.FilePath,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Version,
			&i.Overrides,
			&i.OriginalCalculatedData,
			&i.Notes,
			&i.ComplianceScore,
			&i.AmendmentNumber,
			&i.OriginalReportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByCompany = `-- name: ListReportsByCompany :many
SELECT id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, confirmed_at, created_by, updated_by, updated_at, version, overrides, original_calculated_data, notes, compliance_score, amendment_number, original_report_id FROM reports
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListReportsByCompany(ctx context.Context, arg ListReportsByCompanyParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReportType,
			&i.Period,
			&i.Status,
			&i.InputData,
			&i.CalculatedData,
			&i.FilePath,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Version,
			&i.Overrides,
			&i.OriginalCalculatedData,
			&i.Notes,
			&i.ComplianceScore,
			&i.AmendmentNumber,
			&i.OriginalReportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByCompanyAndType = `-- name: ListReportsByCompanyAndType :many
SELECT id, company_id, report_type, period, status, input_data, calculated_data, file_path, created_at, confirmed_at, created_by, updated_by, updated_at, version, overrides, original_calculated_data, notes, compliance_score, amendment_number, original_report_id FROM reports
WHERE company_id = $1 AND report_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListReportsByCompanyAndTypeParams struct {
	CompanyID  uuid.UUID `json:"company_id"`
	ReportType string    `json:"report_type"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListReportsByCompanyAndType(ctx context.Context, arg ListReportsByCompanyAndTypeParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByCompanyAndType,
		arg.CompanyID,
		arg.ReportType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReportType,
			&i.Period,
			&i.Status,
			&i.InputData,
			&i.CalculatedData,
			&i.FilePath,
			&i.CreatedAt,
			&i.ConfirmedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Version,
			&i.Overrides,
			&i.OriginalCalculatedData,
			&i.Notes,
			&i.ComplianceScore,
			&i.AmendmentNumber,
			&i.OriginalReportID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :exec
UPDATE reports SET
    status = COALESCE($2, status),
    calculated_data = COALESCE($3, calculated_data),
    file_path = COALESCE($4, file_path),
    confirmed_at = $5,
    updated_by = $6,
    updated_at = NOW(),
    version = version + 1,
    overrides = COALESCE($7, overrides),
    original_calculated_data = COALESCE($8, original_calculated_data),
    notes = COALESCE($9, notes),
    compliance_score = $10
WHERE id = $1 AND version = $11
`

type UpdateReportParams struct {
	ID                     uuid.UUID          `json:"id"`
	Status                 string             `json:"status"`
	CalculatedData         []byte             `json:"calculated_data"`
	FilePath               *string            `json:"file_path"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	Overrides              []byte             `json:"overrides"`
	OriginalCalculatedData []byte             `json:"original_calculated_data"`
	Notes                  *string            `json:"notes"`
	ComplianceScore        *int32             `json:"compliance_score"`
	Version                int32              `json:"version"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) error {
	_, err := q.db.Exec(ctx, updateReport,
		arg.ID,
		arg.Status,
		arg.CalculatedData,
		arg.FilePath,
		arg.ConfirmedAt,
		arg.UpdatedBy,
		arg.Overrides,
		arg.OriginalCalculatedData,
		arg.Notes,
		arg.ComplianceScore,
		arg.Version,
	)
	return err
}
