// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSuppliersByCompany = `-- name: CountSuppliersByCompany :one
SELECT COUNT(*) FROM suppliers WHERE company_id = $1
`

func (q *Queries) CountSuppliersByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliersByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (id, company_id, tin, name, address, supplier_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, company_id, tin, name, address, supplier_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at
`

type CreateSupplierParams struct {
	ID              uuid.UUID      `json:"id"`
	CompanyID       uuid.UUID      `json:"company_id"`
	Tin             string         `json:"tin"`
	Name            string         `json:"name"`
	Address         *string        `json:"address"`
	SupplierType    string         `json:"supplier_type"`
	DefaultEwtRate  pgtype.Numeric `json:"default_ewt_rate"`
	DefaultAtcCode  *string        `json:"default_atc_code"`
	IsVatRegistered bool           `json:"is_vat_registered"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.ID,
		arg.CompanyID,
		arg.Tin,
		arg.Name,
		arg.Address,
		arg.SupplierType,
		arg.DefaultEwtRate,
		arg.DefaultAtcCode,
		arg.IsVatRegistered,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Tin,
		&i.Name,
		&i.Address,
		&i.SupplierType,
		&i.DefaultEwtRate,
		&i.DefaultAtcCode,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, company_id, tin, name, address, supplier_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Tin,
		&i.Name,
		&i.Address,
		&i.SupplierType,
		&i.DefaultEwtRate,
		&i.DefaultAtcCode,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByTIN = `-- name: GetSupplierByTIN :one
SELECT id, company_id, tin, name, address, supplier_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at FROM suppliers WHERE company_id = $1 AND tin = $2
`

type GetSupplierByTINParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Tin       string    `json:"tin"`
}

func (q *Queries) GetSupplierByTIN(ctx context.Context, arg GetSupplierByTINParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByTIN, arg.CompanyID, arg.Tin)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Tin,
		&i.Name,
		&i.Address,
		&i.SupplierType,
		&i.DefaultEwtRate,
		&i.DefaultAtcCode,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuppliersByCompany = `-- name: ListSuppliersByCompany :many
SELECT id, company_id, tin, name, address, supplier_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at FROM suppliers WHERE company_id = $1
ORDER BY name LIMIT $2 OFFSET $3
`

type ListSuppliersByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListSuppliersByCompany(ctx context.Context, arg ListSuppliersByCompanyParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliersByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Tin,
			&i.Name,
			&i.Address,
			&i.SupplierType,
			&i.DefaultEwtRate,
			&i.DefaultAtcCode,
			&i.IsVatRegistered,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :exec
UPDATE suppliers SET
    tin = $2, name = $3, address = $4, supplier_type = $5,
    default_ewt_rate = $6, default_atc_code = $7, is_vat_registered = $8,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSupplierParams struct {
	ID              uuid.UUID      `json:"id"`
	Tin             string         `json:"tin"`
	Name            string         `json:"name"`
	Address         *string        `json:"address"`
	SupplierType    string         `json:"supplier_type"`
	DefaultEwtRate  pgtype.Numeric `json:"default_ewt_rate"`
	DefaultAtcCode  *string        `json:"default_atc_code"`
	IsVatRegistered bool           `json:"is_vat_registered"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error {
	_, err := q.db.Exec(ctx, updateSupplier,
		arg.ID,
		arg.Tin,
		arg.Name,
		arg.Address,
		arg.SupplierType,
		arg.DefaultEwtRate,
		arg.DefaultAtcCode,
		arg.IsVatRegistered,
	)
	return err
}
