// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram_users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getActiveSessionByCompanyAndPeriod = `-- name: GetActiveSessionByCompanyAndPeriod :one
SELECT id, company_id, created_by, period, status, report_id, source_files, summary, reconciliation_result, completed_at, created_at, updated_at, opening_balance, closing_balance, bank_closing_balance FROM reconciliation_sessions
WHERE company_id = $1 AND period = $2 AND status IN ('active', 'in_progress')
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveSessionByCompanyAndPeriodParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Period    string    `json:"period"`
}

func (q *Queries) GetActiveSessionByCompanyAndPeriod(ctx context.Context, arg GetActiveSessionByCompanyAndPeriodParams) (ReconciliationSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByCompanyAndPeriod, arg.CompanyID, arg.Period)
	var i ReconciliationSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CreatedBy,
		&i.Period,
		&i.Status,
		&i.ReportID,
		&i.SourceFiles,
		&i.Summary,
		&i.ReconciliationResult,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.BankClosingBalance,
	)
	return i, err
}

const getFirstCompanyByUser = `-- name: GetFirstCompanyByUser :one
SELECT c.id, c.organization_id, c.company_name, c.tin_number, c.rdo_code, c.vat_classification, c.fiscal_year_end, c.industry, c.address, c.plan, c.settings, c.is_active, c.created_at, c.updated_at FROM companies c
JOIN company_members cm ON c.id = cm.company_id
WHERE cm.user_id = $1 AND c.is_active = true
ORDER BY cm.joined_at ASC
LIMIT 1
`

func (q *Queries) GetFirstCompanyByUser(ctx context.Context, userID uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getFirstCompanyByUser, userID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CompanyName,
		&i.TinNumber,
		&i.RdoCode,
		&i.VatClassification,
		&i.FiscalYearEnd,
		&i.Industry,
		&i.Address,
		&i.Plan,
		&i.Settings,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTelegramUser = `-- name: GetTelegramUser :one
SELECT telegram_id, user_id, company_id, chat_id, username, full_name, created_at FROM telegram_users WHERE telegram_id = $1
`

func (q *Queries) GetTelegramUser(ctx context.Context, telegramID int64) (TelegramUser, error) {
	row := q.db.QueryRow(ctx, getTelegramUser, telegramID)
	var i TelegramUser
	err := row.Scan(
		&i.TelegramID,
		&i.UserID,
		&i.CompanyID,
		&i.ChatID,
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionStatsSince = `-- name: GetTransactionStatsSince :one
SELECT
    COUNT(*) AS count,
    COALESCE(SUM(amount), 0::numeric) AS total_amount
FROM transactions
WHERE company_id = $1 AND created_at >= $2
`

type GetTransactionStatsSinceParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetTransactionStatsSinceRow struct {
	Count       int64       `json:"count"`
	TotalAmount interface{} `json:"total_amount"`
}

func (q *Queries) GetTransactionStatsSince(ctx context.Context, arg GetTransactionStatsSinceParams) (GetTransactionStatsSinceRow, error) {
	row := q.db.QueryRow(ctx, getTransactionStatsSince, arg.CompanyID, arg.CreatedAt)
	var i GetTransactionStatsSinceRow
	err := row.Scan(&i.Count, &i.TotalAmount)
	return i, err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO telegram_users (telegram_id, user_id, company_id, chat_id, username, full_name)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (telegram_id) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    company_id = EXCLUDED.company_id,
    chat_id = EXCLUDED.chat_id,
    username = EXCLUDED.username,
    full_name = EXCLUDED.full_name
RETURNING telegram_id, user_id, company_id, chat_id, username, full_name, created_at
`

type UpsertTelegramUserParams struct {
	TelegramID int64     `json:"telegram_id"`
	UserID     uuid.UUID `json:"user_id"`
	CompanyID  uuid.UUID `json:"company_id"`
	ChatID     int64     `json:"chat_id"`
	Username   *string   `json:"username"`
	FullName   *string   `json:"full_name"`
}

func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (TelegramUser, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.TelegramID,
		arg.UserID,
		arg.CompanyID,
		arg.ChatID,
		arg.Username,
		arg.FullName,
	)
	var i TelegramUser
	err := row.Scan(
		&i.TelegramID,
		&i.UserID,
		&i.CompanyID,
		&i.ChatID,
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}
