// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateTransactionClassification = `-- name: BulkUpdateTransactionClassification :exec
UPDATE transactions SET
    vat_type = $2, category = $3, confidence = $4, classification_source = $5, updated_at = NOW()
WHERE id = $1
`

type BulkUpdateTransactionClassificationParams struct {
	ID                   uuid.UUID      `json:"id"`
	VatType              string         `json:"vat_type"`
	Category             string         `json:"category"`
	Confidence           pgtype.Numeric `json:"confidence"`
	ClassificationSource string         `json:"classification_source"`
}

func (q *Queries) BulkUpdateTransactionClassification(ctx context.Context, arg BulkUpdateTransactionClassificationParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateTransactionClassification,
		arg.ID,
		arg.VatType,
		arg.Category,
		arg.Confidence,
		arg.ClassificationSource,
	)
	return err
}

const countTransactionsByCompany = `-- name: CountTransactionsByCompany :one
SELECT COUNT(*) FROM transactions WHERE company_id = $1
`

func (q *Queries) CountTransactionsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsBySession = `-- name: CountTransactionsBySession :one
SELECT COUNT(*) FROM transactions WHERE session_id = $1
`

func (q *Queries) CountTransactionsBySession(ctx context.Context, sessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionsBySessionFiltered = `-- name: CountTransactionsBySessionFiltered :one
SELECT COUNT(*) FROM transactions
WHERE session_id = $1
  AND ($2::varchar = '' OR vat_type = $2)
  AND ($3::varchar = '' OR category = $3)
  AND ($4::varchar = '' OR source_type = $4)
  AND ($5::varchar = '' OR match_status = $5)
  AND ($6::numeric IS NULL OR confidence >= $6)
  AND ($7::text = '' OR description ILIKE '%' || $7 || '%')
`

type CountTransactionsBySessionFilteredParams struct {
	SessionID uuid.UUID      `json:"session_id"`
	Column2   string         `json:"column_2"`
	Column3   string         `json:"column_3"`
	Column4   string         `json:"column_4"`
	Column5   string         `json:"column_5"`
	Column6   pgtype.Numeric `json:"column_6"`
	Column7   string         `json:"column_7"`
}

func (q *Queries) CountTransactionsBySessionFiltered(ctx context.Context, arg CountTransactionsBySessionFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsBySessionFiltered,
		arg.SessionID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, company_id, session_id, source_type, source_file_id, row_index,
    date, description, amount, vat_amount, vat_type, category, tin,
    confidence, classification_source, raw_data, match_group_id, match_status,
    ewt_rate, ewt_amount, atc_code, supplier_id, project_tag,
    from_currency, to_currency, exchange_rate, from_amount,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22, $23,
    $24, $25, $26, $27,
    NOW(), NOW()
) RETURNING id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount
`

type CreateTransactionParams struct {
	ID                   uuid.UUID      `json:"id"`
	CompanyID            uuid.UUID      `json:"company_id"`
	SessionID            uuid.UUID      `json:"session_id"`
	SourceType           string         `json:"source_type"`
	SourceFileID         string         `json:"source_file_id"`
	RowIndex             int32          `json:"row_index"`
	Date                 pgtype.Date    `json:"date"`
	Description          *string        `json:"description"`
	Amount               pgtype.Numeric `json:"amount"`
	VatAmount            pgtype.Numeric `json:"vat_amount"`
	VatType              string         `json:"vat_type"`
	Category             string         `json:"category"`
	Tin                  *string        `json:"tin"`
	Confidence           pgtype.Numeric `json:"confidence"`
	ClassificationSource string         `json:"classification_source"`
	RawData              []byte         `json:"raw_data"`
	MatchGroupID         pgtype.UUID    `json:"match_group_id"`
	MatchStatus          string         `json:"match_status"`
	EwtRate              pgtype.Numeric `json:"ewt_rate"`
	EwtAmount            pgtype.Numeric `json:"ewt_amount"`
	AtcCode              *string        `json:"atc_code"`
	SupplierID           pgtype.UUID    `json:"supplier_id"`
	ProjectTag           *string        `json:"project_tag"`
	FromCurrency         *string        `json:"from_currency"`
	ToCurrency           *string        `json:"to_currency"`
	ExchangeRate         pgtype.Numeric `json:"exchange_rate"`
	FromAmount           pgtype.Numeric `json:"from_amount"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.CompanyID,
		arg.SessionID,
		arg.SourceType,
		arg.SourceFileID,
		arg.RowIndex,
		arg.Date,
		arg.Description,
		arg.Amount,
		arg.VatAmount,
		arg.VatType,
		arg.Category,
		arg.Tin,
		arg.Confidence,
		arg.ClassificationSource,
		arg.RawData,
		arg.MatchGroupID,
		arg.MatchStatus,
		arg.EwtRate,
		arg.EwtAmount,
		arg.AtcCode,
		arg.SupplierID,
		arg.ProjectTag,
		arg.FromCurrency,
		arg.ToCurrency,
		arg.ExchangeRate,
		arg.FromAmount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SessionID,
		&i.SourceType,
		&i.SourceFileID,
		&i.RowIndex,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.VatAmount,
		&i.VatType,
		&i.Category,
		&i.Tin,
		&i.Confidence,
		&i.ClassificationSource,
		&i.RawData,
		&i.MatchGroupID,
		&i.MatchStatus,
		&i.EwtRate,
		&i.EwtAmount,
		&i.AtcCode,
		&i.SupplierID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JournalEntryID,
		&i.ProjectTag,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.ExchangeRate,
		&i.FromAmount,
	)
	return i, err
}

const deleteTransactionsBySession = `-- name: DeleteTransactionsBySession :exec
DELETE FROM transactions WHERE session_id = $1
`

func (q *Queries) DeleteTransactionsBySession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionsBySession, sessionID)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SessionID,
		&i.SourceType,
		&i.SourceFileID,
		&i.RowIndex,
		&i.Date,
		&i.Description,
		&i.Amount,
		&i.VatAmount,
		&i.VatType,
		&i.Category,
		&i.Tin,
		&i.Confidence,
		&i.ClassificationSource,
		&i.RawData,
		&i.MatchGroupID,
		&i.MatchStatus,
		&i.EwtRate,
		&i.EwtAmount,
		&i.AtcCode,
		&i.SupplierID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JournalEntryID,
		&i.ProjectTag,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.ExchangeRate,
		&i.FromAmount,
	)
	return i, err
}

const getTransactionsByIDs = `-- name: GetTransactionsByIDs :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions
WHERE id = ANY($1::uuid[]) AND company_id = $2
ORDER BY date ASC, row_index ASC
`

type GetTransactionsByIDsParams struct {
	Ids       []uuid.UUID `json:"ids"`
	CompanyID uuid.UUID   `json:"company_id"`
}

func (q *Queries) GetTransactionsByIDs(ctx context.Context, arg GetTransactionsByIDsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByIDs, arg.Ids, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnlinkedTransactions = `-- name: GetUnlinkedTransactions :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions
WHERE company_id = $1 AND journal_entry_id IS NULL
ORDER BY date ASC, row_index ASC
LIMIT $2 OFFSET $3
`

type GetUnlinkedTransactionsParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetUnlinkedTransactions(ctx context.Context, arg GetUnlinkedTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUnlinkedTransactions, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTransactionToJournalEntry = `-- name: LinkTransactionToJournalEntry :exec
UPDATE transactions SET
    journal_entry_id = $2, updated_at = NOW()
WHERE id = $1
`

type LinkTransactionToJournalEntryParams struct {
	ID             uuid.UUID   `json:"id"`
	JournalEntryID pgtype.UUID `json:"journal_entry_id"`
}

func (q *Queries) LinkTransactionToJournalEntry(ctx context.Context, arg LinkTransactionToJournalEntryParams) error {
	_, err := q.db.Exec(ctx, linkTransactionToJournalEntry, arg.ID, arg.JournalEntryID)
	return err
}

const listAllTransactionsBySession = `-- name: ListAllTransactionsBySession :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions WHERE session_id = $1 ORDER BY row_index
`

func (q *Queries) ListAllTransactionsBySession(ctx context.Context, sessionID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listAllTransactionsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCompany = `-- name: ListTransactionsByCompany :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByCompany(ctx context.Context, arg ListTransactionsByCompanyParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCompanyAndDateRange = `-- name: ListTransactionsByCompanyAndDateRange :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions
WHERE company_id = $1
  AND date >= $2
  AND date <= $3
ORDER BY date DESC, created_at DESC
LIMIT 10000
`

type ListTransactionsByCompanyAndDateRangeParams struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Date      pgtype.Date `json:"date"`
	Date_2    pgtype.Date `json:"date_2"`
}

func (q *Queries) ListTransactionsByCompanyAndDateRange(ctx context.Context, arg ListTransactionsByCompanyAndDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCompanyAndDateRange, arg.CompanyID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySession = `-- name: ListTransactionsBySession :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions
WHERE session_id = $1
ORDER BY row_index
LIMIT $2 OFFSET $3
`

type ListTransactionsBySessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListTransactionsBySession(ctx context.Context, arg ListTransactionsBySessionParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsBySession, arg.SessionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsBySessionFiltered = `-- name: ListTransactionsBySessionFiltered :many
SELECT id, company_id, session_id, source_type, source_file_id, row_index, date, description, amount, vat_amount, vat_type, category, tin, confidence, classification_source, raw_data, match_group_id, match_status, ewt_rate, ewt_amount, atc_code, supplier_id, created_at, updated_at, journal_entry_id, project_tag, from_currency, to_currency, exchange_rate, from_amount FROM transactions
WHERE session_id = $1
  AND ($4::varchar = '' OR vat_type = $4)
  AND ($5::varchar = '' OR category = $5)
  AND ($6::varchar = '' OR source_type = $6)
  AND ($7::varchar = '' OR match_status = $7)
  AND ($8::numeric IS NULL OR confidence >= $8)
  AND ($9::text = '' OR description ILIKE '%' || $9 || '%')
ORDER BY row_index
LIMIT $2 OFFSET $3
`

type ListTransactionsBySessionFilteredParams struct {
	SessionID uuid.UUID      `json:"session_id"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
	Column4   string         `json:"column_4"`
	Column5   string         `json:"column_5"`
	Column6   string         `json:"column_6"`
	Column7   string         `json:"column_7"`
	Column8   pgtype.Numeric `json:"column_8"`
	Column9   string         `json:"column_9"`
}

func (q *Queries) ListTransactionsBySessionFiltered(ctx context.Context, arg ListTransactionsBySessionFilteredParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsBySessionFiltered,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SourceType,
			&i.SourceFileID,
			&i.RowIndex,
			&i.Date,
			&i.Description,
			&i.Amount,
			&i.VatAmount,
			&i.VatType,
			&i.Category,
			&i.Tin,
			&i.Confidence,
			&i.ClassificationSource,
			&i.RawData,
			&i.MatchGroupID,
			&i.MatchStatus,
			&i.EwtRate,
			&i.EwtAmount,
			&i.AtcCode,
			&i.SupplierID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JournalEntryID,
			&i.ProjectTag,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.ExchangeRate,
			&i.FromAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions SET
    vat_type = COALESCE($2, vat_type),
    category = COALESCE($3, category),
    confidence = COALESCE($4, confidence),
    classification_source = COALESCE($5, classification_source),
    match_group_id = $6,
    match_status = COALESCE($7, match_status),
    ewt_rate = $8,
    ewt_amount = $9,
    atc_code = $10,
    supplier_id = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionParams struct {
	ID                   uuid.UUID      `json:"id"`
	VatType              string         `json:"vat_type"`
	Category             string         `json:"category"`
	Confidence           pgtype.Numeric `json:"confidence"`
	ClassificationSource string         `json:"classification_source"`
	MatchGroupID         pgtype.UUID    `json:"match_group_id"`
	MatchStatus          string         `json:"match_status"`
	EwtRate              pgtype.Numeric `json:"ewt_rate"`
	EwtAmount            pgtype.Numeric `json:"ewt_amount"`
	AtcCode              *string        `json:"atc_code"`
	SupplierID           pgtype.UUID    `json:"supplier_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction,
		arg.ID,
		arg.VatType,
		arg.Category,
		arg.Confidence,
		arg.ClassificationSource,
		arg.MatchGroupID,
		arg.MatchStatus,
		arg.EwtRate,
		arg.EwtAmount,
		arg.AtcCode,
		arg.SupplierID,
	)
	return err
}

const updateTransactionDescription = `-- name: UpdateTransactionDescription :exec
UPDATE transactions SET description = $2, updated_at = NOW() WHERE id = $1
`

type UpdateTransactionDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateTransactionDescription(ctx context.Context, arg UpdateTransactionDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateTransactionDescription, arg.ID, arg.Description)
	return err
}

const updateTransactionMatch = `-- name: UpdateTransactionMatch :exec
UPDATE transactions SET
    match_group_id = $2, match_status = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionMatchParams struct {
	ID           uuid.UUID   `json:"id"`
	MatchGroupID pgtype.UUID `json:"match_group_id"`
	MatchStatus  string      `json:"match_status"`
}

func (q *Queries) UpdateTransactionMatch(ctx context.Context, arg UpdateTransactionMatchParams) error {
	_, err := q.db.Exec(ctx, updateTransactionMatch, arg.ID, arg.MatchGroupID, arg.MatchStatus)
	return err
}
