// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, hashed_password, full_name, api_key, is_active, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, email, hashed_password, full_name, api_key, is_active, created_at
`

type CreateUserParams struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	FullName       *string   `json:"full_name"`
	ApiKey         *string   `json:"api_key"`
	IsActive       bool      `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.FullName,
		arg.ApiKey,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, hashed_password, full_name, api_key, is_active, created_at FROM users WHERE api_key = $1 AND is_active = true
`

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, full_name, api_key, is_active, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, full_name, api_key, is_active, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const setAPIKey = `-- name: SetAPIKey :exec
UPDATE users SET api_key = $2 WHERE id = $1
`

type SetAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	ApiKey *string   `json:"api_key"`
}

func (q *Queries) SetAPIKey(ctx context.Context, arg SetAPIKeyParams) error {
	_, err := q.db.Exec(ctx, setAPIKey, arg.ID, arg.ApiKey)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    full_name = COALESCE($2, full_name),
    api_key = COALESCE($3, api_key),
    is_active = COALESCE($4, is_active)
WHERE id = $1
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	FullName *string   `json:"full_name"`
	ApiKey   *string   `json:"api_key"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.ApiKey,
		arg.IsActive,
	)
	return err
}
