// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, hashed_password, full_name, api_key, is_active, telegram_username, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, email, hashed_password, full_name, api_key, is_active, telegram_username, created_at
`

type CreateUserParams struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	TelegramUsername *string   `json:"telegram_username"`
}

type CreateUserRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	TelegramUsername *string   `json:"telegram_username"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.HashedPassword,
		arg.FullName,
		arg.ApiKey,
		arg.IsActive,
		arg.TelegramUsername,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.TelegramUsername,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT id, email, hashed_password, full_name, api_key, is_active, telegram_username, created_at FROM users WHERE api_key = $1 AND is_active = true
`

type GetUserByAPIKeyRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	TelegramUsername *string   `json:"telegram_username"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey *string) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i GetUserByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.TelegramUsername,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, hashed_password, full_name, api_key, is_active, telegram_username, created_at FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	TelegramUsername *string   `json:"telegram_username"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.TelegramUsername,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, hashed_password, full_name, api_key, is_active, telegram_username, created_at FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	HashedPassword   string    `json:"hashed_password"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	TelegramUsername *string   `json:"telegram_username"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.TelegramUsername,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTelegramUsername = `-- name: GetUserByTelegramUsername :one
SELECT u.id, u.email, u.full_name, u.api_key, u.is_active, u.telegram_username, cm.company_id
FROM users u
JOIN company_members cm ON u.id = cm.user_id
WHERE LOWER(u.telegram_username) = LOWER($1)
  AND u.is_active = true
ORDER BY cm.joined_at ASC
LIMIT 1
`

type GetUserByTelegramUsernameRow struct {
	ID               uuid.UUID `json:"id"`
	Email            string    `json:"email"`
	FullName         *string   `json:"full_name"`
	ApiKey           *string   `json:"api_key"`
	IsActive         bool      `json:"is_active"`
	TelegramUsername *string   `json:"telegram_username"`
	CompanyID        uuid.UUID `json:"company_id"`
}

func (q *Queries) GetUserByTelegramUsername(ctx context.Context, lower string) (GetUserByTelegramUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramUsername, lower)
	var i GetUserByTelegramUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.ApiKey,
		&i.IsActive,
		&i.TelegramUsername,
		&i.CompanyID,
	)
	return i, err
}

const setAPIKey = `-- name: SetAPIKey :exec
UPDATE users SET api_key = $2 WHERE id = $1
`

type SetAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	ApiKey *string   `json:"api_key"`
}

func (q *Queries) SetAPIKey(ctx context.Context, arg SetAPIKeyParams) error {
	_, err := q.db.Exec(ctx, setAPIKey, arg.ID, arg.ApiKey)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    full_name = COALESCE($2, full_name),
    api_key = COALESCE($3, api_key),
    is_active = COALESCE($4, is_active)
WHERE id = $1
`

type UpdateUserParams struct {
	ID       uuid.UUID `json:"id"`
	FullName *string   `json:"full_name"`
	ApiKey   *string   `json:"api_key"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.ApiKey,
		arg.IsActive,
	)
	return err
}
