// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendor_policies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countVendorPolicies = `-- name: CountVendorPolicies :one
SELECT COUNT(*) FROM vendor_posting_policies
WHERE company_id = $1
`

func (q *Queries) CountVendorPolicies(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorPolicies, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVendorPolicy = `-- name: DeleteVendorPolicy :exec
DELETE FROM vendor_posting_policies
WHERE id = $1 AND company_id = $2
`

type DeleteVendorPolicyParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteVendorPolicy(ctx context.Context, arg DeleteVendorPolicyParams) error {
	_, err := q.db.Exec(ctx, deleteVendorPolicy, arg.ID, arg.CompanyID)
	return err
}

const getVendorPolicy = `-- name: GetVendorPolicy :one
SELECT id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at FROM vendor_posting_policies
WHERE company_id = $1 AND vendor_normalized = $2
`

type GetVendorPolicyParams struct {
	CompanyID        uuid.UUID `json:"company_id"`
	VendorNormalized string    `json:"vendor_normalized"`
}

func (q *Queries) GetVendorPolicy(ctx context.Context, arg GetVendorPolicyParams) (VendorPostingPolicy, error) {
	row := q.db.QueryRow(ctx, getVendorPolicy, arg.CompanyID, arg.VendorNormalized)
	var i VendorPostingPolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VendorNormalized,
		&i.Aliases,
		&i.DefaultCategory,
		&i.DefaultAccountCode,
		&i.DefaultTaxCode,
		&i.DefaultDepartment,
		&i.DefaultProject,
		&i.UsageCount,
		&i.AcceptCount,
		&i.CorrectionCount,
		&i.ConfidenceScore,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorPolicyByAlias = `-- name: GetVendorPolicyByAlias :one
SELECT id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at FROM vendor_posting_policies
WHERE company_id = $1 AND aliases @> to_jsonb($2::text)
LIMIT 1
`

type GetVendorPolicyByAliasParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Column2   string    `json:"column_2"`
}

func (q *Queries) GetVendorPolicyByAlias(ctx context.Context, arg GetVendorPolicyByAliasParams) (VendorPostingPolicy, error) {
	row := q.db.QueryRow(ctx, getVendorPolicyByAlias, arg.CompanyID, arg.Column2)
	var i VendorPostingPolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VendorNormalized,
		&i.Aliases,
		&i.DefaultCategory,
		&i.DefaultAccountCode,
		&i.DefaultTaxCode,
		&i.DefaultDepartment,
		&i.DefaultProject,
		&i.UsageCount,
		&i.AcceptCount,
		&i.CorrectionCount,
		&i.ConfidenceScore,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorPolicyByID = `-- name: GetVendorPolicyByID :one
SELECT id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at FROM vendor_posting_policies
WHERE id = $1 AND company_id = $2
`

type GetVendorPolicyByIDParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) GetVendorPolicyByID(ctx context.Context, arg GetVendorPolicyByIDParams) (VendorPostingPolicy, error) {
	row := q.db.QueryRow(ctx, getVendorPolicyByID, arg.ID, arg.CompanyID)
	var i VendorPostingPolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VendorNormalized,
		&i.Aliases,
		&i.DefaultCategory,
		&i.DefaultAccountCode,
		&i.DefaultTaxCode,
		&i.DefaultDepartment,
		&i.DefaultProject,
		&i.UsageCount,
		&i.AcceptCount,
		&i.CorrectionCount,
		&i.ConfidenceScore,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementVendorAcceptance = `-- name: IncrementVendorAcceptance :exec
UPDATE vendor_posting_policies
SET accept_count = accept_count + 1,
    usage_count = usage_count + 1,
    confidence_score = (accept_count + 1)::numeric / GREATEST(accept_count + correction_count + 1, 1),
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE company_id = $1 AND vendor_normalized = $2
`

type IncrementVendorAcceptanceParams struct {
	CompanyID        uuid.UUID `json:"company_id"`
	VendorNormalized string    `json:"vendor_normalized"`
}

func (q *Queries) IncrementVendorAcceptance(ctx context.Context, arg IncrementVendorAcceptanceParams) error {
	_, err := q.db.Exec(ctx, incrementVendorAcceptance, arg.CompanyID, arg.VendorNormalized)
	return err
}

const incrementVendorCorrection = `-- name: IncrementVendorCorrection :exec
UPDATE vendor_posting_policies
SET correction_count = correction_count + 1,
    usage_count = usage_count + 1,
    confidence_score = accept_count::numeric / GREATEST(accept_count + correction_count + 1, 1),
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE company_id = $1 AND vendor_normalized = $2
`

type IncrementVendorCorrectionParams struct {
	CompanyID        uuid.UUID `json:"company_id"`
	VendorNormalized string    `json:"vendor_normalized"`
}

func (q *Queries) IncrementVendorCorrection(ctx context.Context, arg IncrementVendorCorrectionParams) error {
	_, err := q.db.Exec(ctx, incrementVendorCorrection, arg.CompanyID, arg.VendorNormalized)
	return err
}

const incrementVendorUsage = `-- name: IncrementVendorUsage :exec
UPDATE vendor_posting_policies
SET usage_count = usage_count + 1,
    last_seen_at = NOW(),
    updated_at = NOW()
WHERE company_id = $1 AND vendor_normalized = $2
`

type IncrementVendorUsageParams struct {
	CompanyID        uuid.UUID `json:"company_id"`
	VendorNormalized string    `json:"vendor_normalized"`
}

func (q *Queries) IncrementVendorUsage(ctx context.Context, arg IncrementVendorUsageParams) error {
	_, err := q.db.Exec(ctx, incrementVendorUsage, arg.CompanyID, arg.VendorNormalized)
	return err
}

const listRuleSuggestions = `-- name: ListRuleSuggestions :many
SELECT id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at FROM vendor_posting_policies
WHERE company_id = $1
  AND correction_count >= $2
  AND confidence_score < 0.70
ORDER BY correction_count DESC
LIMIT 20
`

type ListRuleSuggestionsParams struct {
	CompanyID       uuid.UUID `json:"company_id"`
	CorrectionCount int32     `json:"correction_count"`
}

func (q *Queries) ListRuleSuggestions(ctx context.Context, arg ListRuleSuggestionsParams) ([]VendorPostingPolicy, error) {
	rows, err := q.db.Query(ctx, listRuleSuggestions, arg.CompanyID, arg.CorrectionCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorPostingPolicy{}
	for rows.Next() {
		var i VendorPostingPolicy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorNormalized,
			&i.Aliases,
			&i.DefaultCategory,
			&i.DefaultAccountCode,
			&i.DefaultTaxCode,
			&i.DefaultDepartment,
			&i.DefaultProject,
			&i.UsageCount,
			&i.AcceptCount,
			&i.CorrectionCount,
			&i.ConfidenceScore,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorPolicies = `-- name: ListVendorPolicies :many
SELECT id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at FROM vendor_posting_policies
WHERE company_id = $1
ORDER BY usage_count DESC
LIMIT $2 OFFSET $3
`

type ListVendorPoliciesParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListVendorPolicies(ctx context.Context, arg ListVendorPoliciesParams) ([]VendorPostingPolicy, error) {
	rows, err := q.db.Query(ctx, listVendorPolicies, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorPostingPolicy{}
	for rows.Next() {
		var i VendorPostingPolicy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorNormalized,
			&i.Aliases,
			&i.DefaultCategory,
			&i.DefaultAccountCode,
			&i.DefaultTaxCode,
			&i.DefaultDepartment,
			&i.DefaultProject,
			&i.UsageCount,
			&i.AcceptCount,
			&i.CorrectionCount,
			&i.ConfidenceScore,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVendorByName = `-- name: SearchVendorByName :many
SELECT id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at FROM vendor_posting_policies
WHERE company_id = $1
  AND (vendor_normalized ILIKE '%' || $2 || '%'
       OR aliases::text ILIKE '%' || $2 || '%')
ORDER BY usage_count DESC
LIMIT 10
`

type SearchVendorByNameParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Column2   *string   `json:"column_2"`
}

func (q *Queries) SearchVendorByName(ctx context.Context, arg SearchVendorByNameParams) ([]VendorPostingPolicy, error) {
	rows, err := q.db.Query(ctx, searchVendorByName, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorPostingPolicy{}
	for rows.Next() {
		var i VendorPostingPolicy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorNormalized,
			&i.Aliases,
			&i.DefaultCategory,
			&i.DefaultAccountCode,
			&i.DefaultTaxCode,
			&i.DefaultDepartment,
			&i.DefaultProject,
			&i.UsageCount,
			&i.AcceptCount,
			&i.CorrectionCount,
			&i.ConfidenceScore,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorDefaults = `-- name: UpdateVendorDefaults :exec
UPDATE vendor_posting_policies
SET default_category = COALESCE(NULLIF($3, ''), default_category),
    default_account_code = COALESCE(NULLIF($4, ''), default_account_code),
    default_tax_code = COALESCE(NULLIF($5, ''), default_tax_code),
    default_department = COALESCE(NULLIF($6, ''), default_department),
    default_project = COALESCE(NULLIF($7, ''), default_project),
    updated_at = NOW()
WHERE company_id = $1 AND vendor_normalized = $2
`

type UpdateVendorDefaultsParams struct {
	CompanyID        uuid.UUID   `json:"company_id"`
	VendorNormalized string      `json:"vendor_normalized"`
	Column3          interface{} `json:"column_3"`
	Column4          interface{} `json:"column_4"`
	Column5          interface{} `json:"column_5"`
	Column6          interface{} `json:"column_6"`
	Column7          interface{} `json:"column_7"`
}

func (q *Queries) UpdateVendorDefaults(ctx context.Context, arg UpdateVendorDefaultsParams) error {
	_, err := q.db.Exec(ctx, updateVendorDefaults,
		arg.CompanyID,
		arg.VendorNormalized,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const upsertVendorPolicy = `-- name: UpsertVendorPolicy :one
INSERT INTO vendor_posting_policies (
    company_id, vendor_normalized, aliases,
    default_category, default_account_code, default_tax_code,
    default_department, default_project,
    usage_count, accept_count, confidence_score, last_seen_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
ON CONFLICT (company_id, vendor_normalized) DO UPDATE SET
    aliases = CASE
        WHEN NOT vendor_posting_policies.aliases @> EXCLUDED.aliases
        THEN vendor_posting_policies.aliases || EXCLUDED.aliases
        ELSE vendor_posting_policies.aliases
    END,
    default_category = COALESCE(NULLIF(EXCLUDED.default_category, ''), vendor_posting_policies.default_category),
    default_account_code = COALESCE(NULLIF(EXCLUDED.default_account_code, ''), vendor_posting_policies.default_account_code),
    default_tax_code = COALESCE(NULLIF(EXCLUDED.default_tax_code, ''), vendor_posting_policies.default_tax_code),
    default_department = COALESCE(NULLIF(EXCLUDED.default_department, ''), vendor_posting_policies.default_department),
    default_project = COALESCE(NULLIF(EXCLUDED.default_project, ''), vendor_posting_policies.default_project),
    usage_count = vendor_posting_policies.usage_count + EXCLUDED.usage_count,
    accept_count = vendor_posting_policies.accept_count + EXCLUDED.accept_count,
    confidence_score = EXCLUDED.confidence_score,
    last_seen_at = NOW(),
    updated_at = NOW()
RETURNING id, company_id, vendor_normalized, aliases, default_category, default_account_code, default_tax_code, default_department, default_project, usage_count, accept_count, correction_count, confidence_score, last_seen_at, created_at, updated_at
`

type UpsertVendorPolicyParams struct {
	CompanyID          uuid.UUID      `json:"company_id"`
	VendorNormalized   string         `json:"vendor_normalized"`
	Aliases            []byte         `json:"aliases"`
	DefaultCategory    *string        `json:"default_category"`
	DefaultAccountCode *string        `json:"default_account_code"`
	DefaultTaxCode     *string        `json:"default_tax_code"`
	DefaultDepartment  *string        `json:"default_department"`
	DefaultProject     *string        `json:"default_project"`
	UsageCount         int32          `json:"usage_count"`
	AcceptCount        int32          `json:"accept_count"`
	ConfidenceScore    pgtype.Numeric `json:"confidence_score"`
}

func (q *Queries) UpsertVendorPolicy(ctx context.Context, arg UpsertVendorPolicyParams) (VendorPostingPolicy, error) {
	row := q.db.QueryRow(ctx, upsertVendorPolicy,
		arg.CompanyID,
		arg.VendorNormalized,
		arg.Aliases,
		arg.DefaultCategory,
		arg.DefaultAccountCode,
		arg.DefaultTaxCode,
		arg.DefaultDepartment,
		arg.DefaultProject,
		arg.UsageCount,
		arg.AcceptCount,
		arg.ConfidenceScore,
	)
	var i VendorPostingPolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VendorNormalized,
		&i.Aliases,
		&i.DefaultCategory,
		&i.DefaultAccountCode,
		&i.DefaultTaxCode,
		&i.DefaultDepartment,
		&i.DefaultProject,
		&i.UsageCount,
		&i.AcceptCount,
		&i.CorrectionCount,
		&i.ConfidenceScore,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
