// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countVendorsByCompany = `-- name: CountVendorsByCompany :one
SELECT COUNT(*) FROM vendors WHERE company_id = $1
`

func (q *Queries) CountVendorsByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (id, company_id, tin, name, address, vendor_type, default_ewt_rate, default_atc_code, is_vat_registered,
    email, phone, payment_terms_days, currency_code, default_account_id, is_active, notes,
    created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16,
    NOW(), NOW())
RETURNING id, company_id, tin, name, address, vendor_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at, email, phone, payment_terms_days, currency_code, default_account_id, is_active, notes
`

type CreateVendorParams struct {
	ID               uuid.UUID      `json:"id"`
	CompanyID        uuid.UUID      `json:"company_id"`
	Tin              string         `json:"tin"`
	Name             string         `json:"name"`
	Address          *string        `json:"address"`
	VendorType       string         `json:"vendor_type"`
	DefaultEwtRate   pgtype.Numeric `json:"default_ewt_rate"`
	DefaultAtcCode   *string        `json:"default_atc_code"`
	IsVatRegistered  bool           `json:"is_vat_registered"`
	Email            *string        `json:"email"`
	Phone            *string        `json:"phone"`
	PaymentTermsDays *int32         `json:"payment_terms_days"`
	CurrencyCode     *string        `json:"currency_code"`
	DefaultAccountID pgtype.UUID    `json:"default_account_id"`
	IsActive         bool           `json:"is_active"`
	Notes            *string        `json:"notes"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.ID,
		arg.CompanyID,
		arg.Tin,
		arg.Name,
		arg.Address,
		arg.VendorType,
		arg.DefaultEwtRate,
		arg.DefaultAtcCode,
		arg.IsVatRegistered,
		arg.Email,
		arg.Phone,
		arg.PaymentTermsDays,
		arg.CurrencyCode,
		arg.DefaultAccountID,
		arg.IsActive,
		arg.Notes,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Tin,
		&i.Name,
		&i.Address,
		&i.VendorType,
		&i.DefaultEwtRate,
		&i.DefaultAtcCode,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Phone,
		&i.PaymentTermsDays,
		&i.CurrencyCode,
		&i.DefaultAccountID,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors WHERE id = $1 AND company_id = $2
`

type DeleteVendorParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

func (q *Queries) DeleteVendor(ctx context.Context, arg DeleteVendorParams) error {
	_, err := q.db.Exec(ctx, deleteVendor, arg.ID, arg.CompanyID)
	return err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, company_id, tin, name, address, vendor_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at, email, phone, payment_terms_days, currency_code, default_account_id, is_active, notes FROM vendors WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Tin,
		&i.Name,
		&i.Address,
		&i.VendorType,
		&i.DefaultEwtRate,
		&i.DefaultAtcCode,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Phone,
		&i.PaymentTermsDays,
		&i.CurrencyCode,
		&i.DefaultAccountID,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const getVendorByTIN = `-- name: GetVendorByTIN :one
SELECT id, company_id, tin, name, address, vendor_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at, email, phone, payment_terms_days, currency_code, default_account_id, is_active, notes FROM vendors WHERE company_id = $1 AND tin = $2
`

type GetVendorByTINParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Tin       string    `json:"tin"`
}

func (q *Queries) GetVendorByTIN(ctx context.Context, arg GetVendorByTINParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByTIN, arg.CompanyID, arg.Tin)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Tin,
		&i.Name,
		&i.Address,
		&i.VendorType,
		&i.DefaultEwtRate,
		&i.DefaultAtcCode,
		&i.IsVatRegistered,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Phone,
		&i.PaymentTermsDays,
		&i.CurrencyCode,
		&i.DefaultAccountID,
		&i.IsActive,
		&i.Notes,
	)
	return i, err
}

const listVendorsByCompany = `-- name: ListVendorsByCompany :many
SELECT id, company_id, tin, name, address, vendor_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at, email, phone, payment_terms_days, currency_code, default_account_id, is_active, notes FROM vendors WHERE company_id = $1
ORDER BY name LIMIT $2 OFFSET $3
`

type ListVendorsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListVendorsByCompany(ctx context.Context, arg ListVendorsByCompanyParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendorsByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Tin,
			&i.Name,
			&i.Address,
			&i.VendorType,
			&i.DefaultEwtRate,
			&i.DefaultAtcCode,
			&i.IsVatRegistered,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Phone,
			&i.PaymentTermsDays,
			&i.CurrencyCode,
			&i.DefaultAccountID,
			&i.IsActive,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVendorsByCompany = `-- name: SearchVendorsByCompany :many
SELECT id, company_id, tin, name, address, vendor_type, default_ewt_rate, default_atc_code, is_vat_registered, created_at, updated_at, email, phone, payment_terms_days, currency_code, default_account_id, is_active, notes FROM vendors
WHERE company_id = $1
  AND (name ILIKE '%' || $2 || '%' OR tin ILIKE '%' || $2 || '%')
ORDER BY name LIMIT $3 OFFSET $4
`

type SearchVendorsByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Column2   *string   `json:"column_2"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) SearchVendorsByCompany(ctx context.Context, arg SearchVendorsByCompanyParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, searchVendorsByCompany,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Tin,
			&i.Name,
			&i.Address,
			&i.VendorType,
			&i.DefaultEwtRate,
			&i.DefaultAtcCode,
			&i.IsVatRegistered,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Phone,
			&i.PaymentTermsDays,
			&i.CurrencyCode,
			&i.DefaultAccountID,
			&i.IsActive,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :exec
UPDATE vendors SET
    tin = $2, name = $3, address = $4, vendor_type = $5,
    default_ewt_rate = $6, default_atc_code = $7, is_vat_registered = $8,
    email = $9, phone = $10, payment_terms_days = $11, currency_code = $12,
    default_account_id = $13, is_active = $14, notes = $15,
    updated_at = NOW()
WHERE id = $1
`

type UpdateVendorParams struct {
	ID               uuid.UUID      `json:"id"`
	Tin              string         `json:"tin"`
	Name             string         `json:"name"`
	Address          *string        `json:"address"`
	VendorType       string         `json:"vendor_type"`
	DefaultEwtRate   pgtype.Numeric `json:"default_ewt_rate"`
	DefaultAtcCode   *string        `json:"default_atc_code"`
	IsVatRegistered  bool           `json:"is_vat_registered"`
	Email            *string        `json:"email"`
	Phone            *string        `json:"phone"`
	PaymentTermsDays *int32         `json:"payment_terms_days"`
	CurrencyCode     *string        `json:"currency_code"`
	DefaultAccountID pgtype.UUID    `json:"default_account_id"`
	IsActive         bool           `json:"is_active"`
	Notes            *string        `json:"notes"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) error {
	_, err := q.db.Exec(ctx, updateVendor,
		arg.ID,
		arg.Tin,
		arg.Name,
		arg.Address,
		arg.VendorType,
		arg.DefaultEwtRate,
		arg.DefaultAtcCode,
		arg.IsVatRegistered,
		arg.Email,
		arg.Phone,
		arg.PaymentTermsDays,
		arg.CurrencyCode,
		arg.DefaultAccountID,
		arg.IsActive,
		arg.Notes,
	)
	return err
}
