// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withholding.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWithholdingByCompany = `-- name: CountWithholdingByCompany :one
SELECT COUNT(*) FROM withholding_certificates WHERE company_id = $1
`

func (q *Queries) CountWithholdingByCompany(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWithholdingByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWithholdingCertificate = `-- name: CreateWithholdingCertificate :one
INSERT INTO withholding_certificates (id, company_id, session_id, supplier_id, period, quarter, atc_code, income_type, income_amount, ewt_rate, tax_withheld, status, file_path, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW(), NOW())
RETURNING id, company_id, session_id, supplier_id, period, quarter, atc_code, income_type, income_amount, ewt_rate, tax_withheld, status, file_path, created_at, updated_at
`

type CreateWithholdingCertificateParams struct {
	ID           uuid.UUID      `json:"id"`
	CompanyID    uuid.UUID      `json:"company_id"`
	SessionID    pgtype.UUID    `json:"session_id"`
	SupplierID   uuid.UUID      `json:"supplier_id"`
	Period       string         `json:"period"`
	Quarter      string         `json:"quarter"`
	AtcCode      string         `json:"atc_code"`
	IncomeType   string         `json:"income_type"`
	IncomeAmount pgtype.Numeric `json:"income_amount"`
	EwtRate      pgtype.Numeric `json:"ewt_rate"`
	TaxWithheld  pgtype.Numeric `json:"tax_withheld"`
	Status       string         `json:"status"`
	FilePath     *string        `json:"file_path"`
}

func (q *Queries) CreateWithholdingCertificate(ctx context.Context, arg CreateWithholdingCertificateParams) (WithholdingCertificate, error) {
	row := q.db.QueryRow(ctx, createWithholdingCertificate,
		arg.ID,
		arg.CompanyID,
		arg.SessionID,
		arg.SupplierID,
		arg.Period,
		arg.Quarter,
		arg.AtcCode,
		arg.IncomeType,
		arg.IncomeAmount,
		arg.EwtRate,
		arg.TaxWithheld,
		arg.Status,
		arg.FilePath,
	)
	var i WithholdingCertificate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SessionID,
		&i.SupplierID,
		&i.Period,
		&i.Quarter,
		&i.AtcCode,
		&i.IncomeType,
		&i.IncomeAmount,
		&i.EwtRate,
		&i.TaxWithheld,
		&i.Status,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWithholdingCertificateByID = `-- name: GetWithholdingCertificateByID :one
SELECT id, company_id, session_id, supplier_id, period, quarter, atc_code, income_type, income_amount, ewt_rate, tax_withheld, status, file_path, created_at, updated_at FROM withholding_certificates WHERE id = $1
`

func (q *Queries) GetWithholdingCertificateByID(ctx context.Context, id uuid.UUID) (WithholdingCertificate, error) {
	row := q.db.QueryRow(ctx, getWithholdingCertificateByID, id)
	var i WithholdingCertificate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SessionID,
		&i.SupplierID,
		&i.Period,
		&i.Quarter,
		&i.AtcCode,
		&i.IncomeType,
		&i.IncomeAmount,
		&i.EwtRate,
		&i.TaxWithheld,
		&i.Status,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWithholdingByCompany = `-- name: ListWithholdingByCompany :many
SELECT id, company_id, session_id, supplier_id, period, quarter, atc_code, income_type, income_amount, ewt_rate, tax_withheld, status, file_path, created_at, updated_at FROM withholding_certificates WHERE company_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListWithholdingByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListWithholdingByCompany(ctx context.Context, arg ListWithholdingByCompanyParams) ([]WithholdingCertificate, error) {
	rows, err := q.db.Query(ctx, listWithholdingByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithholdingCertificate{}
	for rows.Next() {
		var i WithholdingCertificate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SupplierID,
			&i.Period,
			&i.Quarter,
			&i.AtcCode,
			&i.IncomeType,
			&i.IncomeAmount,
			&i.EwtRate,
			&i.TaxWithheld,
			&i.Status,
			&i.FilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWithholdingBySupplier = `-- name: ListWithholdingBySupplier :many
SELECT id, company_id, session_id, supplier_id, period, quarter, atc_code, income_type, income_amount, ewt_rate, tax_withheld, status, file_path, created_at, updated_at FROM withholding_certificates
WHERE supplier_id = $1 AND period = $2
ORDER BY created_at
`

type ListWithholdingBySupplierParams struct {
	SupplierID uuid.UUID `json:"supplier_id"`
	Period     string    `json:"period"`
}

func (q *Queries) ListWithholdingBySupplier(ctx context.Context, arg ListWithholdingBySupplierParams) ([]WithholdingCertificate, error) {
	rows, err := q.db.Query(ctx, listWithholdingBySupplier, arg.SupplierID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WithholdingCertificate{}
	for rows.Next() {
		var i WithholdingCertificate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SessionID,
			&i.SupplierID,
			&i.Period,
			&i.Quarter,
			&i.AtcCode,
			&i.IncomeType,
			&i.IncomeAmount,
			&i.EwtRate,
			&i.TaxWithheld,
			&i.Status,
			&i.FilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWithholdingCertificate = `-- name: UpdateWithholdingCertificate :exec
UPDATE withholding_certificates SET
    status = COALESCE($2, status), file_path = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateWithholdingCertificateParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	FilePath *string   `json:"file_path"`
}

func (q *Queries) UpdateWithholdingCertificate(ctx context.Context, arg UpdateWithholdingCertificateParams) error {
	_, err := q.db.Exec(ctx, updateWithholdingCertificate, arg.ID, arg.Status, arg.FilePath)
	return err
}
