FROM golang:1.23-alpine AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o api ./cmd/api

FROM gcr.io/distroless/static-debian12
COPY --from=builder /build/api /api
COPY --from=builder /build/migrations /migrations
EXPOSE 8000
ENTRYPOINT ["/api"]
