package service

import (
	"encoding/csv"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/go-pdf/fpdf"
	"github.com/tonypk/aistarlight-go/internal/service/birpdf"
	"github.com/tonypk/aistarlight-go/internal/service/iraspdf"
	"github.com/tonypk/aistarlight-go/pkg/birforms"
	"github.com/tonypk/aistarlight-go/pkg/irasforms"
)

// CompanyInfo holds company metadata for PDF report headers.
type CompanyInfo struct {
	CompanyName string
	TINNumber   string
	RDOCode     string
}

// GeneratePDFReport generates a tax form PDF using the appropriate layout.
func GeneratePDFReport(w io.Writer, reportType string, data map[string]string, company CompanyInfo) error {
	// Singapore IRAS forms
	if strings.HasPrefix(reportType, "IRAS_") {
		sgCo := iraspdf.CompanyData{
			Name: company.CompanyName,
			UEN:  company.TINNumber,
		}
		switch reportType {
		case irasforms.FormGSTF5:
			return iraspdf.GenerateGSTF5(w, data, sgCo)
		case irasforms.FormFormC:
			return iraspdf.GenerateFormC(w, data, sgCo)
		case irasforms.FormFormCS:
			return iraspdf.GenerateFormCS(w, data, sgCo)
		case irasforms.FormFormB:
			return iraspdf.GenerateFormB(w, data, sgCo)
		case irasforms.FormIR8A:
			return iraspdf.GenerateIR8A(w, data, sgCo)
		case irasforms.FormS45:
			return iraspdf.GenerateS45(w, data, sgCo)
		case irasforms.FormECI:
			return iraspdf.GenerateECI(w, data, sgCo)
		default:
			return generateGenericPDF(w, reportType, data, company)
		}
	}

	// Philippine BIR forms
	co := birpdf.CompanyData{
		Name:    company.CompanyName,
		TIN:     company.TINNumber,
		RDOCode: company.RDOCode,
	}

	switch reportType {
	case birforms.FormBIR2550M:
		return birpdf.Generate2550M(w, data, co)
	case birforms.FormBIR2550Q:
		return birpdf.Generate2550Q(w, data, co)
	case birforms.FormBIR1601C:
		return birpdf.Generate1601C(w, data, co)
	case birforms.FormBIR0619E:
		return birpdf.Generate0619E(w, data, co)
	case birforms.FormBIR1701:
		return birpdf.Generate1701(w, data, co)
	case birforms.FormBIR1702:
		return birpdf.Generate1702(w, data, co)
	case birforms.FormBIR2316:
		return birpdf.Generate2316(w, data, co)
	case birforms.FormBIR2307:
		return birpdf.Generate2307(w, data, co)
	default:
		return generateGenericPDF(w, reportType, data, company)
	}
}

// PDF layout constants (Letter: 612 x 792 pt).
const (
	pdfPageW    = 612.0
	pdfPageH    = 792.0
	pdfMarginL  = 54.0
	pdfMarginR  = 54.0
	pdfContentW = pdfPageW - pdfMarginL - pdfMarginR // 504
)

// pdfBuilder wraps fpdf with BIR-specific layout helpers.
type pdfBuilder struct {
	pdf *fpdf.Fpdf
	y   float64
}

func newPDF() *pdfBuilder {
	pdf := fpdf.New("P", "pt", "Letter", "")
	pdf.SetAutoPageBreak(true, 40)
	pdf.SetFooterFunc(func() {
		pdf.SetY(-20)
		pdf.SetTextColor(136, 136, 136)
		pdf.SetFont("Helvetica", "", 6)
		pdf.CellFormat(0, 10,
			"Generated by AIStarlight | This is a draft report for review purposes \u2014 not for official filing",
			"", 0, "C", false, 0, "")
	})
	pdf.AddPage()
	return &pdfBuilder{pdf: pdf, y: 0}
}

// titleBanner draws the dark-blue title banner at the top.
func (b *pdfBuilder) titleBanner(formNo, subtitle string) {
	b.pdf.SetFillColor(30, 58, 95)
	b.pdf.Rect(0, 0, pdfPageW, 70, "F")

	b.pdf.SetTextColor(255, 255, 255)
	b.pdf.SetFont("Helvetica", "B", 18)
	b.centeredCell(16, 20, formNo)

	b.pdf.SetFont("Helvetica", "", 10)
	b.centeredCell(36, 14, subtitle)

	b.pdf.SetFont("Helvetica", "", 7)
	b.centeredCell(52, 12, "Republic of the Philippines - Department of Finance - Bureau of Internal Revenue")

	b.y = 90
}

// centeredCell draws centered text at the given y position across the page width.
func (b *pdfBuilder) centeredCell(y, h float64, text string) {
	b.pdf.SetXY(0, y)
	b.pdf.CellFormat(pdfPageW, h, text, "", 0, "C", false, 0, "")
}

// sectionHeader draws a gray section header bar.
func (b *pdfBuilder) sectionHeader(text string) {
	b.pdf.SetFillColor(232, 237, 242)
	b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 18, "F")
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont("Helvetica", "B", 9)
	b.pdf.SetXY(pdfMarginL+6, b.y+2)
	b.pdf.CellFormat(pdfContentW-12, 14, text, "", 0, "L", false, 0, "")
	b.y += 22
}

// infoBlock draws labeled info rows (Part I background).
func (b *pdfBuilder) infoBlock(items [][2]string) {
	b.pdf.SetTextColor(0, 0, 0)
	for _, item := range items {
		b.pdf.SetFont("Helvetica", "", 8)
		b.pdf.SetXY(pdfMarginL+6, b.y)
		b.pdf.CellFormat(134, 14, item[0]+":", "", 0, "L", false, 0, "")
		b.pdf.SetFont("Helvetica", "B", 8)
		b.pdf.SetXY(pdfMarginL+146, b.y)
		b.pdf.CellFormat(pdfContentW-152, 14, item[1], "", 0, "L", false, 0, "")
		b.y += 14
	}
	b.y += 6
}

// lineItem draws a single line item (line number, label, PHP amount).
func (b *pdfBuilder) lineItem(lineNo, label, value string, bold bool) {
	style := ""
	if bold {
		style = "B"
	}
	b.pdf.SetFont("Helvetica", style, 8)
	b.pdf.SetTextColor(0, 0, 0)

	if lineNo != "" {
		b.pdf.SetXY(pdfMarginL+6, b.y)
		b.pdf.CellFormat(24, 12, lineNo, "", 0, "L", false, 0, "")
	}
	b.pdf.SetXY(pdfMarginL+36, b.y)
	b.pdf.CellFormat(pdfContentW-156, 12, label, "", 0, "L", false, 0, "")
	b.pdf.SetXY(pdfPageW-pdfMarginR-120, b.y)
	b.pdf.CellFormat(120, 12, "PHP "+formatPDFAmount(value), "", 0, "R", false, 0, "")

	// Light separator line
	b.pdf.SetDrawColor(204, 204, 204)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Line(pdfMarginL, b.y+12, pdfPageW-pdfMarginR, b.y+12)
	b.y += 16
}

// totalDueHighlight draws the highlighted "TOTAL AMOUNT DUE" box.
func (b *pdfBuilder) totalDueHighlight(lineNo, label, value string) {
	b.y += 4
	b.pdf.SetFillColor(240, 244, 255)
	b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 22, "F")
	b.pdf.SetDrawColor(37, 99, 235)
	b.pdf.SetLineWidth(1)
	b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 22, "D")

	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont("Helvetica", "B", 10)
	b.pdf.SetXY(pdfMarginL+6, b.y+3)
	b.pdf.CellFormat(24, 16, lineNo, "", 0, "L", false, 0, "")
	b.pdf.SetXY(pdfMarginL+36, b.y+3)
	b.pdf.CellFormat(pdfContentW-156, 16, label, "", 0, "L", false, 0, "")

	b.pdf.SetTextColor(37, 99, 235)
	b.pdf.SetXY(pdfPageW-pdfMarginR-120, b.y+3)
	b.pdf.CellFormat(120, 16, "PHP "+formatPDFAmount(value), "", 0, "R", false, 0, "")
	b.y += 28
}

// refundHighlight draws the year-end adjustment box (green for refund, blue for due).
func (b *pdfBuilder) refundHighlight(lineNo string, refund, due string) {
	b.y += 4
	refundVal, _ := strconv.ParseFloat(refund, 64)
	isRefund := refundVal > 0

	if isRefund {
		b.pdf.SetFillColor(240, 253, 244)
		b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 22, "F")
		b.pdf.SetDrawColor(22, 163, 74)
	} else {
		b.pdf.SetFillColor(240, 244, 255)
		b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 22, "F")
		b.pdf.SetDrawColor(37, 99, 235)
	}
	b.pdf.SetLineWidth(1)
	b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 22, "D")

	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont("Helvetica", "B", 10)
	b.pdf.SetXY(pdfMarginL+6, b.y+3)
	b.pdf.CellFormat(24, 16, lineNo, "", 0, "L", false, 0, "")

	if isRefund {
		b.pdf.SetXY(pdfMarginL+36, b.y+3)
		b.pdf.CellFormat(pdfContentW-156, 16, "AMOUNT REFUNDED TO EMPLOYEE", "", 0, "L", false, 0, "")
		b.pdf.SetTextColor(22, 163, 74)
		b.pdf.SetXY(pdfPageW-pdfMarginR-120, b.y+3)
		b.pdf.CellFormat(120, 16, "PHP "+formatPDFAmount(refund), "", 0, "R", false, 0, "")
	} else {
		b.pdf.SetXY(pdfMarginL+36, b.y+3)
		b.pdf.CellFormat(pdfContentW-156, 16, "AMOUNT STILL DUE FROM EMPLOYEE", "", 0, "L", false, 0, "")
		b.pdf.SetTextColor(37, 99, 235)
		b.pdf.SetXY(pdfPageW-pdfMarginR-120, b.y+3)
		b.pdf.CellFormat(120, 16, "PHP "+formatPDFAmount(due), "", 0, "R", false, 0, "")
	}
	b.y += 28
}

// taxCreditNote draws the amber tax-credit-carried-forward notice.
func (b *pdfBuilder) taxCreditNote(value string) {
	f, _ := strconv.ParseFloat(value, 64)
	if f <= 0 {
		return
	}
	b.y += 8
	b.pdf.SetFillColor(254, 243, 199)
	b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 18, "F")
	b.pdf.SetTextColor(146, 64, 14)
	b.pdf.SetFont("Helvetica", "", 8)
	b.pdf.SetXY(pdfMarginL+6, b.y+2)
	b.pdf.CellFormat(pdfContentW-12, 14,
		"Excess Input VAT / Tax Credit Carried Forward: PHP "+formatPDFAmount(value),
		"", 0, "L", false, 0, "")
	b.y += 22
}

// complianceScore draws the compliance score badge.
func (b *pdfBuilder) complianceScore(score int) {
	b.y += 12
	b.sectionHeader("Compliance Validation")
	b.y += 2

	var bgR, bgG, bgB, fgR, fgG, fgB int
	var label string
	switch {
	case score >= 80:
		bgR, bgG, bgB = 209, 250, 229
		fgR, fgG, fgB = 6, 95, 70
		label = "Compliant"
	case score >= 60:
		bgR, bgG, bgB = 254, 243, 199
		fgR, fgG, fgB = 146, 64, 14
		label = "Needs Review"
	default:
		bgR, bgG, bgB = 254, 226, 226
		fgR, fgG, fgB = 153, 27, 27
		label = "Non-Compliant"
	}

	b.pdf.SetFillColor(bgR, bgG, bgB)
	b.pdf.Rect(pdfMarginL, b.y, pdfContentW, 22, "F")
	b.pdf.SetTextColor(fgR, fgG, fgB)
	b.pdf.SetFont("Helvetica", "B", 12)
	b.pdf.SetXY(pdfMarginL+6, b.y+3)
	b.pdf.CellFormat(100, 16, fmt.Sprintf("Score: %d/100", score), "", 0, "L", false, 0, "")
	b.pdf.SetFont("Helvetica", "", 9)
	b.pdf.SetXY(pdfMarginL+110, b.y+5)
	b.pdf.CellFormat(100, 14, "\u2014 "+label, "", 0, "L", false, 0, "")
	b.y += 28
}

// notes draws the IMPORTANT NOTES section.
func (b *pdfBuilder) notes(lines []string) {
	b.y += 16
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetFont("Helvetica", "", 7)
	for _, line := range lines {
		b.pdf.SetXY(pdfMarginL+6, b.y)
		b.pdf.CellFormat(pdfContentW-12, 10, line, "", 0, "L", false, 0, "")
		b.y += 10
	}
}

// gap adds vertical spacing.
func (b *pdfBuilder) gap(pts float64) {
	b.y += pts
}

// output writes the PDF to w.
func (b *pdfBuilder) output(w io.Writer) error {
	return b.pdf.Output(w)
}

// formatPDFAmount formats a decimal string as "1,234.56".
func formatPDFAmount(value string) string {
	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return value
	}

	neg := f < 0
	if neg {
		f = -f
	}

	s := fmt.Sprintf("%.2f", f)
	parts := strings.Split(s, ".")
	integer, frac := parts[0], parts[1]

	// Insert comma separators.
	n := len(integer)
	if n > 3 {
		var buf strings.Builder
		for i, ch := range integer {
			if i > 0 && (n-i)%3 == 0 {
				buf.WriteByte(',')
			}
			buf.WriteRune(ch)
		}
		integer = buf.String()
	}

	formatted := integer + "." + frac
	if neg {
		return "(" + formatted + ")"
	}
	return formatted
}

// getD safely retrieves a value from data, trying multiple keys with "0" fallback.
func getD(data map[string]string, keys ...string) string {
	for _, k := range keys {
		if v, ok := data[k]; ok && v != "" {
			return v
		}
	}
	return "0"
}

// GenerateCSVExport writes report data as a CSV to w.
func GenerateCSVExport(w io.Writer, data map[string]string) error {
	cw := csv.NewWriter(w)
	defer cw.Flush()

	if err := cw.Write([]string{"Line", "Field", "Value (PHP)"}); err != nil {
		return err
	}

	for key, value := range data {
		if !strings.HasPrefix(key, "line_") {
			continue
		}
		parts := strings.SplitN(key, "_", 3)
		lineNo := ""
		label := key
		if len(parts) > 1 {
			lineNo = parts[1]
		}
		if len(parts) > 2 {
			label = strings.ReplaceAll(parts[2], "_", " ")
		}
		if err := cw.Write([]string{lineNo, label, value}); err != nil {
			return err
		}
	}
	return cw.Error()
}
