package birpdf

import (
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/go-pdf/fpdf"
)

// BIR official form visual constants (extracted from official PDFs).
const (
	birFontFamily = "Arial"
	birFontSize   = 8.0
	birTitleSize  = 14.0
	birSmallSize  = 6.5
	birTinySize   = 5.5

	birLineWidth  = 0.4
	birBoxHeight  = 14.0
	birTINBoxSize = 10.0

	defaultMarginL = 36.0
	defaultMarginR = 36.0
	defaultMarginT = 28.0
)

// birFormBuilder provides official BIR form layout primitives.
type birFormBuilder struct {
	pdf     *fpdf.Fpdf
	y       float64
	pageW   float64
	pageH   float64
	marginL float64
	marginR float64
	formNo  string
	version string
	pageNum int
}

// PageSize represents a PDF page size in points.
type PageSize struct {
	W, H float64
}

// Common BIR form page sizes (in points).
var (
	SizeLegal     = PageSize{612, 1008} // 8.5 x 14 in
	SizeLetter    = PageSize{612, 792}  // 8.5 x 11 in
	SizeFolio     = PageSize{612, 936}  // 8.5 x 13 in
)

// newBuilder creates a new birFormBuilder with the given page size.
func newBuilder(size PageSize, formNo, version string) *birFormBuilder {
	pdf := fpdf.NewCustom(&fpdf.InitType{
		OrientationStr: "P",
		UnitStr:        "pt",
		Size:           fpdf.SizeType{Wd: size.W, Ht: size.H},
	})
	pdf.SetAutoPageBreak(false, 0)
	pdf.SetMargins(0, 0, 0)

	b := &birFormBuilder{
		pdf:     pdf,
		pageW:   size.W,
		pageH:   size.H,
		marginL: defaultMarginL,
		marginR: defaultMarginR,
		formNo:  formNo,
		version: version,
		pageNum: 0,
	}

	return b
}

// contentW returns the usable content width.
func (b *birFormBuilder) contentW() float64 {
	return b.pageW - b.marginL - b.marginR
}

// addPage adds a new page and draws the standard footer.
func (b *birFormBuilder) addPage() {
	b.pageNum++
	b.pdf.AddPage()
	b.y = defaultMarginT
}

// output writes the finished PDF to w.
func (b *birFormBuilder) output(w io.Writer) error {
	// Draw footers on all pages
	totalPages := b.pdf.PageCount()
	for i := 1; i <= totalPages; i++ {
		b.pdf.SetPage(i)
		b.drawPageFooter(i, totalPages)
	}
	return b.pdf.Output(w)
}

// drawPageFooter draws the footer on a specific page.
func (b *birFormBuilder) drawPageFooter(pageNo, totalPages int) {
	y := b.pageH - 20
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Line(b.marginL, y, b.pageW-b.marginR, y)

	b.pdf.SetFont(birFontFamily, "", birTinySize)
	b.pdf.SetTextColor(100, 100, 100)
	b.pdf.SetXY(b.marginL, y+2)
	b.pdf.CellFormat(b.contentW()/2, 10, b.formNo+" "+b.version, "", 0, "L", false, 0, "")
	b.pdf.SetXY(b.marginL+b.contentW()/2, y+2)
	b.pdf.CellFormat(b.contentW()/2, 10,
		fmt.Sprintf("Page %d of %d", pageNo, totalPages), "", 0, "R", false, 0, "")

	b.pdf.SetFont(birFontFamily, "", birTinySize-1)
	b.pdf.SetTextColor(130, 130, 130)
	b.pdf.SetXY(b.marginL, y+10)
	b.pdf.CellFormat(b.contentW(), 8,
		"Generated by AIStarlight - Draft for review purposes only, not for official filing",
		"", 0, "C", false, 0, "")
}

// -------------------------------------------------------------------
// Header & Title primitives
// -------------------------------------------------------------------

// formHeader draws the official BIR form header block.
// Republic of the Philippines / Department of Finance / Bureau of Internal Revenue
// BIR Form No. XXXX (large, centered)
// Title (centered)
func (b *birFormBuilder) formHeader(formNo, title, subtitle string) {
	cw := b.contentW()
	startY := b.y

	// Top border line
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(1.5)
	b.pdf.Line(b.marginL, startY, b.marginL+cw, startY)

	b.y += 4

	// "Republic of the Philippines"
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(cw, 9, "Republic of the Philippines", "", 0, "C", false, 0, "")
	b.y += 9

	// "Department of Finance"
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(cw, 9, "Department of Finance", "", 0, "C", false, 0, "")
	b.y += 9

	// "Bureau of Internal Revenue"
	b.pdf.SetFont(birFontFamily, "B", birSmallSize+1)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(cw, 9, "Bureau of Internal Revenue", "", 0, "C", false, 0, "")
	b.y += 12

	// Form number in large font
	b.pdf.SetFont(birFontFamily, "B", birTitleSize+2)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(cw, 18, "BIR Form No. "+formNo, "", 0, "C", false, 0, "")
	b.y += 18

	// Form title
	b.pdf.SetFont(birFontFamily, "B", birFontSize+1)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(cw, 12, title, "", 0, "C", false, 0, "")
	b.y += 12

	// Subtitle if present
	if subtitle != "" {
		b.pdf.SetFont(birFontFamily, "", birSmallSize)
		b.pdf.SetXY(b.marginL, b.y)
		b.pdf.CellFormat(cw, 9, subtitle, "", 0, "C", false, 0, "")
		b.y += 9
	}

	// Bottom border line
	b.y += 2
	b.pdf.SetLineWidth(1.5)
	b.pdf.Line(b.marginL, b.y, b.marginL+cw, b.y)
	b.y += 6
}

// -------------------------------------------------------------------
// Part headers & section dividers
// -------------------------------------------------------------------

// partHeader draws "Part I - Background Information" style headers with black fill.
func (b *birFormBuilder) partHeader(text string) {
	cw := b.contentW()
	h := 16.0

	b.pdf.SetFillColor(0, 0, 0)
	b.pdf.Rect(b.marginL, b.y, cw, h, "F")

	b.pdf.SetTextColor(255, 255, 255)
	b.pdf.SetFont(birFontFamily, "B", birFontSize)
	b.pdf.SetXY(b.marginL+4, b.y+2)
	b.pdf.CellFormat(cw-8, h-4, text, "", 0, "L", false, 0, "")

	b.pdf.SetTextColor(0, 0, 0)
	b.y += h
}

// -------------------------------------------------------------------
// TIN boxes
// -------------------------------------------------------------------

// tinBoxes draws TIN number in separated digit boxes: [1][2][3]-[4][5][6]-[7][8][9]-[0][0][0]
func (b *birFormBuilder) tinBoxes(label, tin string) {
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL+4, b.y+2)
	b.pdf.CellFormat(30, birBoxHeight-4, label, "", 0, "L", false, 0, "")

	// Parse TIN: remove dashes, pad to 12 digits
	digits := strings.ReplaceAll(tin, "-", "")
	digits = strings.ReplaceAll(digits, " ", "")
	for len(digits) < 12 {
		digits += "0"
	}

	boxSize := birTINBoxSize
	startX := b.marginL + 38
	b.pdf.SetFont(birFontFamily, "B", birFontSize)
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)

	for i := 0; i < 12; i++ {
		x := startX + float64(i)*boxSize
		// Add dash separators at positions 3, 6, 9
		if i == 3 || i == 6 || i == 9 {
			b.pdf.SetFont(birFontFamily, "B", birFontSize+2)
			b.pdf.SetXY(x-2, b.y)
			b.pdf.CellFormat(6, birBoxHeight, "-", "", 0, "C", false, 0, "")
			startX += 4
			x = startX + float64(i)*boxSize
			b.pdf.SetFont(birFontFamily, "B", birFontSize)
		}

		// Draw box
		b.pdf.Rect(x, b.y, boxSize, birBoxHeight, "D")
		// Draw digit
		if i < len(digits) {
			b.pdf.SetXY(x, b.y)
			b.pdf.CellFormat(boxSize, birBoxHeight, string(digits[i]), "", 0, "C", false, 0, "")
		}
	}

	b.y += birBoxHeight + 2
}

// -------------------------------------------------------------------
// Checkbox
// -------------------------------------------------------------------

// checkbox draws a checkbox with label: [X] Yes  [ ] No
func (b *birFormBuilder) checkbox(label string, checked bool) {
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL+4, b.y+1)
	b.pdf.CellFormat(100, 10, label, "", 0, "L", false, 0, "")

	x := b.marginL + 110

	// Yes checkbox
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Rect(x, b.y+1, 8, 8, "D")
	if checked {
		b.pdf.SetFont(birFontFamily, "B", 7)
		b.pdf.SetXY(x, b.y+1)
		b.pdf.CellFormat(8, 8, "X", "", 0, "C", false, 0, "")
	}
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetXY(x+10, b.y+1)
	b.pdf.CellFormat(20, 8, "Yes", "", 0, "L", false, 0, "")

	// No checkbox
	x += 36
	b.pdf.Rect(x, b.y+1, 8, 8, "D")
	if !checked {
		b.pdf.SetFont(birFontFamily, "B", 7)
		b.pdf.SetXY(x, b.y+1)
		b.pdf.CellFormat(8, 8, "X", "", 0, "C", false, 0, "")
	}
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetXY(x+10, b.y+1)
	b.pdf.CellFormat(20, 8, "No", "", 0, "L", false, 0, "")

	b.y += 12
}

// -------------------------------------------------------------------
// Text fields (labeled input with underline)
// -------------------------------------------------------------------

// textField draws a label + value with underline, like official form fill-in fields.
func (b *birFormBuilder) textField(label, value string, labelW float64) {
	cw := b.contentW()
	h := birBoxHeight

	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL+4, b.y+1)
	b.pdf.CellFormat(labelW, h-2, label, "", 0, "L", false, 0, "")

	// Value with underline
	valueX := b.marginL + 4 + labelW
	valueW := cw - labelW - 12
	b.pdf.SetFont(birFontFamily, "B", birFontSize)
	b.pdf.SetXY(valueX, b.y+1)
	b.pdf.CellFormat(valueW, h-2, value, "", 0, "L", false, 0, "")

	// Underline
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Line(valueX, b.y+h-1, valueX+valueW, b.y+h-1)

	b.y += h + 1
}

// textFieldHalf draws two label+value pairs side by side.
func (b *birFormBuilder) textFieldHalf(label1, value1, label2, value2 string) {
	halfW := b.contentW() / 2
	h := birBoxHeight

	// Left field
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL+4, b.y+1)
	b.pdf.CellFormat(60, h-2, label1, "", 0, "L", false, 0, "")
	b.pdf.SetFont(birFontFamily, "B", birFontSize)
	b.pdf.SetXY(b.marginL+66, b.y+1)
	b.pdf.CellFormat(halfW-72, h-2, value1, "", 0, "L", false, 0, "")
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Line(b.marginL+66, b.y+h-1, b.marginL+halfW-6, b.y+h-1)

	// Right field
	rightX := b.marginL + halfW
	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetXY(rightX+4, b.y+1)
	b.pdf.CellFormat(60, h-2, label2, "", 0, "L", false, 0, "")
	b.pdf.SetFont(birFontFamily, "B", birFontSize)
	b.pdf.SetXY(rightX+66, b.y+1)
	b.pdf.CellFormat(halfW-72, h-2, value2, "", 0, "L", false, 0, "")
	b.pdf.Line(rightX+66, b.y+h-1, rightX+halfW-6, b.y+h-1)

	b.y += h + 1
}

// -------------------------------------------------------------------
// Line items & amount boxes (core of BIR computation sections)
// -------------------------------------------------------------------

// fieldRow draws a computation line: line number | description | amount box
func (b *birFormBuilder) fieldRow(lineNo, label, value string, bold bool) {
	cw := b.contentW()
	h := birBoxHeight
	lineNoW := 28.0
	amtW := 100.0
	labelW := cw - lineNoW - amtW - 4

	// Draw border
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Rect(b.marginL, b.y, cw, h, "D")

	// Line number cell (left)
	b.pdf.Rect(b.marginL, b.y, lineNoW, h, "D")
	b.pdf.SetFont(birFontFamily, "B", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(lineNoW, h, lineNo, "", 0, "C", false, 0, "")

	// Label
	style := ""
	if bold {
		style = "B"
	}
	b.pdf.SetFont(birFontFamily, style, birSmallSize)
	b.pdf.SetXY(b.marginL+lineNoW+2, b.y+1)
	b.pdf.CellFormat(labelW, h-2, label, "", 0, "L", false, 0, "")

	// Amount box (right)
	amtX := b.marginL + cw - amtW
	b.pdf.Rect(amtX, b.y, amtW, h, "D")
	b.pdf.SetFont(birFontFamily, style, birFontSize)
	b.pdf.SetXY(amtX+2, b.y)
	b.pdf.CellFormat(amtW-4, h, formatAmount(value), "", 0, "R", false, 0, "")

	b.y += h
}

// fieldRowNoAmt draws a line row without an amount box (for labels only).
func (b *birFormBuilder) fieldRowNoAmt(lineNo, label string) {
	cw := b.contentW()
	h := birBoxHeight
	lineNoW := 28.0

	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Rect(b.marginL, b.y, cw, h, "D")
	b.pdf.Rect(b.marginL, b.y, lineNoW, h, "D")

	b.pdf.SetFont(birFontFamily, "B", birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(lineNoW, h, lineNo, "", 0, "C", false, 0, "")

	b.pdf.SetFont(birFontFamily, "", birSmallSize)
	b.pdf.SetXY(b.marginL+lineNoW+2, b.y+1)
	b.pdf.CellFormat(cw-lineNoW-4, h-2, label, "", 0, "L", false, 0, "")

	b.y += h
}

// totalRow draws a highlighted total row (slightly taller, bold).
func (b *birFormBuilder) totalRow(lineNo, label, value string) {
	cw := b.contentW()
	h := birBoxHeight + 2
	lineNoW := 28.0
	amtW := 100.0
	labelW := cw - lineNoW - amtW - 4

	// Light gray background for totals
	b.pdf.SetFillColor(235, 235, 235)
	b.pdf.Rect(b.marginL, b.y, cw, h, "F")

	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.5)
	b.pdf.Rect(b.marginL, b.y, cw, h, "D")
	b.pdf.Rect(b.marginL, b.y, lineNoW, h, "D")

	// Line number
	b.pdf.SetFont(birFontFamily, "B", birSmallSize+1)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL, b.y)
	b.pdf.CellFormat(lineNoW, h, lineNo, "", 0, "C", false, 0, "")

	// Label
	b.pdf.SetFont(birFontFamily, "B", birSmallSize+0.5)
	b.pdf.SetXY(b.marginL+lineNoW+2, b.y+1)
	b.pdf.CellFormat(labelW, h-2, label, "", 0, "L", false, 0, "")

	// Amount
	amtX := b.marginL + cw - amtW
	b.pdf.Rect(amtX, b.y, amtW, h, "D")
	b.pdf.SetFont(birFontFamily, "B", birFontSize+1)
	b.pdf.SetXY(amtX+2, b.y)
	b.pdf.CellFormat(amtW-4, h, formatAmount(value), "", 0, "R", false, 0, "")

	b.y += h
}

// -------------------------------------------------------------------
// Grid rows (for schedules / multi-column tables)
// -------------------------------------------------------------------

// GridCell represents one cell in a grid row.
type GridCell struct {
	Text    string
	Width   float64
	Align   string // "L", "C", "R"
	Bold    bool
	Fill    bool
	FillR   int
	FillG   int
	FillB   int
}

// gridHeaderRow draws a header row for schedule/grid tables.
func (b *birFormBuilder) gridHeaderRow(cells []GridCell) {
	h := birBoxHeight
	x := b.marginL

	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)

	for _, cell := range cells {
		if cell.Fill {
			b.pdf.SetFillColor(cell.FillR, cell.FillG, cell.FillB)
		} else {
			b.pdf.SetFillColor(220, 220, 220)
		}
		b.pdf.Rect(x, b.y, cell.Width, h, "FD")

		style := ""
		if cell.Bold {
			style = "B"
		}
		b.pdf.SetFont(birFontFamily, style, birTinySize)
		b.pdf.SetTextColor(0, 0, 0)
		b.pdf.SetXY(x+1, b.y+1)
		align := cell.Align
		if align == "" {
			align = "C"
		}
		b.pdf.CellFormat(cell.Width-2, h-2, cell.Text, "", 0, align, false, 0, "")
		x += cell.Width
	}
	b.y += h
}

// gridRow draws a data row in schedule/grid tables.
func (b *birFormBuilder) gridRow(cells []GridCell) {
	h := birBoxHeight
	x := b.marginL

	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)

	for _, cell := range cells {
		if cell.Fill {
			b.pdf.SetFillColor(cell.FillR, cell.FillG, cell.FillB)
			b.pdf.Rect(x, b.y, cell.Width, h, "FD")
		} else {
			b.pdf.Rect(x, b.y, cell.Width, h, "D")
		}

		style := ""
		if cell.Bold {
			style = "B"
		}
		b.pdf.SetFont(birFontFamily, style, birTinySize)
		b.pdf.SetTextColor(0, 0, 0)
		b.pdf.SetXY(x+1, b.y+1)
		align := cell.Align
		if align == "" {
			align = "L"
		}
		b.pdf.CellFormat(cell.Width-2, h-2, cell.Text, "", 0, align, false, 0, "")
		x += cell.Width
	}
	b.y += h
}

// -------------------------------------------------------------------
// Signature block
// -------------------------------------------------------------------

// signatureBlock draws the declaration and signature area.
func (b *birFormBuilder) signatureBlock(declarationText string) {
	cw := b.contentW()
	b.y += 4

	if declarationText == "" {
		declarationText = "I declare, under the penalties of perjury, that this return has been made in good faith, verified by me, and to the best of my knowledge and belief, is true, correct, and complete."
	}

	// Declaration text
	b.pdf.SetFont(birFontFamily, "", birTinySize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL+4, b.y)
	b.pdf.MultiCell(cw-8, 8, declarationText, "", "L", false)
	b.y += 20

	halfW := cw / 2

	// Left: Taxpayer/Authorized Representative
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	sigY := b.y + 20
	b.pdf.Line(b.marginL+10, sigY, b.marginL+halfW-20, sigY)
	b.pdf.SetFont(birFontFamily, "", birTinySize)
	b.pdf.SetXY(b.marginL+10, sigY+2)
	b.pdf.CellFormat(halfW-30, 8, "Taxpayer/Authorized Representative", "", 0, "C", false, 0, "")

	// Right: Date
	b.pdf.Line(b.marginL+halfW+20, sigY, b.marginL+cw-10, sigY)
	b.pdf.SetXY(b.marginL+halfW+20, sigY+2)
	b.pdf.CellFormat(halfW-30, 8, "Date", "", 0, "C", false, 0, "")

	b.y = sigY + 14

	// Title/Position
	sigY2 := b.y + 16
	b.pdf.Line(b.marginL+10, sigY2, b.marginL+halfW-20, sigY2)
	b.pdf.SetXY(b.marginL+10, sigY2+2)
	b.pdf.CellFormat(halfW-30, 8, "Title/Position", "", 0, "C", false, 0, "")

	// TIN
	b.pdf.Line(b.marginL+halfW+20, sigY2, b.marginL+cw-10, sigY2)
	b.pdf.SetXY(b.marginL+halfW+20, sigY2+2)
	b.pdf.CellFormat(halfW-30, 8, "TIN", "", 0, "C", false, 0, "")

	b.y = sigY2 + 14
}

// -------------------------------------------------------------------
// Payment details section
// -------------------------------------------------------------------

// paymentDetails draws the payment method section (for forms that need it).
func (b *birFormBuilder) paymentDetails() {
	b.partHeader("Payment Details")
	b.y += 2

	cw := b.contentW()

	// Drawee Bank
	b.textField("Drawee Bank / Agency", "", 100)
	// Number and Date
	b.textFieldHalf("Number", "", "Date", "")
	// Amount
	b.textField("Amount", "", 100)

	// Machine Validation box
	b.y += 4
	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.5)
	b.pdf.Rect(b.marginL+cw*0.6, b.y, cw*0.4, 40, "D")
	b.pdf.SetFont(birFontFamily, "", birTinySize)
	b.pdf.SetXY(b.marginL+cw*0.6+2, b.y+2)
	b.pdf.CellFormat(cw*0.4-4, 8, "Machine Validation / Revenue Official Receipt", "", 0, "C", false, 0, "")
	b.y += 44
}

// -------------------------------------------------------------------
// Utility helpers
// -------------------------------------------------------------------

// gap adds vertical spacing.
func (b *birFormBuilder) gap(pts float64) {
	b.y += pts
}

// checkPageBreak adds a new page if remaining space is less than needed.
func (b *birFormBuilder) checkPageBreak(needed float64) {
	if b.y+needed > b.pageH-30 {
		b.addPage()
	}
}

// labelRow draws a simple label row spanning full width (no line number, no amount).
func (b *birFormBuilder) labelRow(text string, bold bool) {
	cw := b.contentW()
	h := birBoxHeight

	b.pdf.SetDrawColor(0, 0, 0)
	b.pdf.SetLineWidth(0.3)
	b.pdf.Rect(b.marginL, b.y, cw, h, "D")

	style := ""
	if bold {
		style = "B"
	}
	b.pdf.SetFont(birFontFamily, style, birSmallSize)
	b.pdf.SetTextColor(0, 0, 0)
	b.pdf.SetXY(b.marginL+4, b.y+1)
	b.pdf.CellFormat(cw-8, h-2, text, "", 0, "L", false, 0, "")

	b.y += h
}

// -------------------------------------------------------------------
// Format helpers
// -------------------------------------------------------------------

// formatAmount formats a numeric string as "1,234.56".
func formatAmount(value string) string {
	if value == "" || value == "0" {
		return "-"
	}

	f, err := strconv.ParseFloat(value, 64)
	if err != nil {
		return value
	}

	if f == 0 {
		return "-"
	}

	neg := f < 0
	if neg {
		f = -f
	}

	s := fmt.Sprintf("%.2f", f)
	parts := strings.Split(s, ".")
	integer, frac := parts[0], parts[1]

	n := len(integer)
	if n > 3 {
		var buf strings.Builder
		for i, ch := range integer {
			if i > 0 && (n-i)%3 == 0 {
				buf.WriteByte(',')
			}
			buf.WriteRune(ch)
		}
		integer = buf.String()
	}

	formatted := integer + "." + frac
	if neg {
		return "(" + formatted + ")"
	}
	return formatted
}

// getVal safely retrieves a value from data, trying multiple keys.
func getVal(data map[string]string, keys ...string) string {
	for _, k := range keys {
		if v, ok := data[k]; ok && v != "" {
			return v
		}
	}
	return "0"
}
